### ISSUE TITLE
Documentation on list of inputs for loop

### ISSUE THREAD

**Issue by ekeric13** [benthosdev/benthos#1011]
So I have a list of SQS queues, and for each queue I want to do the exact same process

```
input:
  aws_sqs:
    url: ${DIFFERENT_QUUE}
    region: us-east-1
    endpoint: sqs.us-east-1.amazonaws.com


pipeline:
  processors:
    - log:
        level: INFO
        message: "sqs_message"
        fields:
          meta: ${! meta() }
          content: ${! content() }


output:
  http_client:
    url: 'http://localhost:9000/${! meta("URL") }
    verb: POST
```

This only thing that changes is the input queue url.

I see there are loops: https://www.benthos.dev/docs/components/processors/while/#fields
and the broker input: https://www.benthos.dev/docs/components/inputs/broker
but I don't think either of those is exactly what I am looking for.

Is there a way I can pass in a list of queues as an environment variable (`${LIST_OF_QUEUES}`), and use only one benthos config for all of them that runs all together in one container?
If this does exist could we think of a way to document this more clearly?

**Comment by mihaitodor** [comment]
Would [Streams Mode](https://www.benthos.dev/docs/guides/streams_mode/about) help?

**Comment by ekeric13** [comment]
That definitely helps with running multiple different configs in one container. Thank you!

But is there a way to just have 1 config that could take a list and iterative over said list? 
Like a for_each: https://www.benthos.dev/docs/components/processors/for_each
but for inputs

```
input:
  for_each: ${QUEUES}
    aws_sqs:
      url: ${each.value}
      region: us-east-1
      endpoint: sqs.us-east-1.amazonaws.com


pipeline:
  processors:
    - log:
        level: INFO
        message: "sqs_message"
        fields:
          meta: ${! meta() }
          content: ${! content() }


output:
  http_client:
    url: 'http://localhost:9000/${! meta("URL") }
    verb: POST
```

**Comment by Jeffail** [comment]
Hey @ekeric13 if you're willing to try an experimental feature then you can do this with templating: https://www.benthos.dev/docs/configuration/templating

What you'd do is define an input template where you convert a list of queues into a broker containing an sqs input for each queue:

```yaml
name: custom_sqses
type: input

fields:
  - name: queues_csv
    type: string
  - name: region
    type: string
    default: us-east-1
  - name: endpoint
    type: string
    default: ""

mapping: |
  root.broker.inputs = this.queues_csv.split(",").map_each(queue -> {
    "aws_sqs": {
      "url": queue,
      "region": this.region,
      "endpoint": this.endpoint,
    }
  })
```

Template `fields` don't currently support string array types but it's easy enough to add if you want to try templating out.

**Comment by Jeffail** [comment]
If we add a `string_list` type they'd look like this:

```yaml
name: custom_sqses
type: input

fields:
  - name: queues
    type: string_list
  - name: region
    type: string
    default: us-east-1
  - name: endpoint
    type: string
    default: ""

mapping: |
  root.broker.inputs = this.queues.map_each(queue -> {
    "aws_sqs": {
      "url": queue,
      "region": this.region,
      "endpoint": this.endpoint,
    }
  })
```

And this:

```yaml
input:
  custom_sqses:
    queues:
      - https://sqs.us-east-2.amazonaws.com/123456789012/MyQueue1
      - https://sqs.us-east-2.amazonaws.com/123456789012/MyQueue2

pipeline:
  processors:
    - log:
        level: INFO
        message: "sqs_message"
        fields:
          meta: ${! meta() }
          content: ${! content() }


output:
  http_client:
    url: 'http://localhost:9000/${! meta("URL") }
    verb: POST
```

**Comment by Jeffail** [comment]
Hey @ekeric13, you can add processors to the individual inputs in the config, so maybe have your template generate a structure that looks like this:

```yaml
input:
  broker:
    inputs:
      - aws_sqs:
          url: TODO
        processors:
          - bloblang: meta input_index = "0"
      - aws_sqs:
          url: TODO
        processors:
          - bloblang: meta input_index = "1"
```

And then in your pipeline you can reference the metadata fields set:

```yaml
pipeline:
  processors:
    - log:
        level: INFO
        message: "sqs_message"
        fields:
          meta: ${! meta() }
          input_index: ${! meta("input_index") }
          content: ${! content() }
          queue: this.url or this.queue
```

**Comment by ekeric13** [comment]
Thank you for the swift response! I guess now I have question about the mapping syntax.
I couldn't find much docs around it:
https://www.benthos.dev/docs/components/inputs/bloblang/#mapping

But I did find this issue you made:
https://github.com/Jeffail/benthos/issues/590

My first instinct was to build something like this:
```
mapping: |
  root.broker.inputs = this.queues.split(",").map_each(queue -> {
    "aws_sqs": {
      "url": queue,
      "region": this.region,
      "endpoint": this.endpoint,
      "reset_visibility": false,
      "delete_message": true
    },
    "processors": {
        "bloblang": meta input_queue = queue
      }
  })
```

but it wouldn't compile because the mapping doesn't like what i am doing in the map_each `parse mapping: line 11 char 24: required: expected query`.


Something like this compiled but didn't parse the `queue`

```
mapping: |
  root.broker.inputs = this.queues.split(",").map_each(queue -> {
    "aws_sqs": {
      "url": queue,
      "region": this.region,
      "endpoint": this.endpoint
    },
    "processors": [
      {
        "bloblang": """
           meta input_queue = queue
          """
      }
    ]
  })
```
as the queue is always defined as null.

I tried
```
 "bloblang": """
           meta input_queue = %v
          """.format(queue)
```
but that just gave me another error of `failed to create processor 'bloblang': line 2 char 33: expected line break`

Any ideas of how the parsing of the bloblang mapping might work?

**Comment by Jeffail** [comment]
Hey @ekeric13, the mapping language is called bloblang: https://www.benthos.dev/docs/guides/bloblang/about, it's going to be a bit confusing because you need to use bloblang in order to generate a bloblang mapping, but this should work:

```yaml
mapping: |
  root.broker.inputs = this.queues.split(",").map_each(queue -> {
    "aws_sqs": {
      "url": queue,
      "region": this.region,
      "endpoint": this.endpoint
    },
    "processors": [
      {
        "bloblang": """meta input_queue = "%v"""".format(queue)
      }
    ]
  })
```

**Comment by ekeric13** [comment]
Still hitting errors. I am using benthos version 3.60. Maybe newer versions had a breaking change?

```
Template file read error: template /benthos/template.yaml: parse mapping: line 11 char 47: required: expected query
 "bloblang": """meta input_queue = "%v"""".format(queue)
```

Same error when trying `"bloblang": """"meta input_queue = %v"""".format(queue)`

Also tried
```
"bloblang": """"meta input_queue = %v".format(queue)"""
```

which compiled but then gave me a run time error of `,"message":"Failed to execute fields mapping: failed assignment (line 2): invalid character 'm' looking for beginning of value"`

Also tried:
```
"""meta input_queue = %v""".format(queue)
```
which gave me a runtime error of `,"message":"Service closing due to: failed to create processor 'bloblang': line 1 char 24: expected line break"`

Lastly tried:
```
"""meta input_queue = "%v".format(queue)"""
```

which resulted in printing an non-sensical queue name
```
input_queue":"\u003cnil\u003e",
```

**Comment by Jeffail** [comment]
Whoops my bad, I didn't actually try it locally. The string literal with triple quotes there is mangled as it can't end with a quote, using backslash escapes works:

```yaml
mapping: |
  root.broker.inputs = this.urls.map_each(url -> {
    "aws_sqs": {
      "url": url,
      "region": this.region,
    },
    "processors": [
      {
        "bloblang": "meta input_queue = \"%v\"".format(url)
      }
    ]
  })
```
