### ISSUE TITLE
`cork` higher order input

### ISSUE THREAD

**Issue by disintegrator** [benthosdev/benthos#1069]
This is a proposal for a higher-order input called `cork` that controls reading from an underlying input.

```yaml
input:
  cork:
    initially_open: false
    signal_path: "/pubsub" 
    input:
      label: foo_input
      gcp_pub_sub: {}

output:
  drop: {}
```

In the example above, no messages are read from `foo_input`. A signal is required to "uncork" the input and start reading messages and likewise to "cork" and stop reads. In this example, the signal source is an http endpoint:

```
POST <benthos_prefix>/uncork/pubsub
```

… causes the pipeline to start reading messages from the input.

```
POST <benthos_prefix>/cork/pubsub
```

… causes the pipeline to stop reading messages from the input.

## Open questions

* I'm not sure if an http endpoint is the best fit for a signal source. Any other ideas?

## Example use-case

_This not real production use case so I'm quite interested if others have ones that benefit from this feature._

As part of a load test, I want to prepare a pubsub topic by loading it with messages with benthos instances deployed in kubernetes _on standby_. When I've completed loading the topic, I want to trigger the instances to start consuming.
