### ISSUE TITLE
Is it possible to catch the error in fallback output?

### ISSUE THREAD

**Issue by guiguan** [benthosdev/benthos#1079]
The fallback output type can define some fallback outputs, but it doesn't look like the `error()` is propagated to those outputs. Any other workarounds to catch them so those fallback outputs can record why the first output has failed?

**Comment by Jeffail** [comment]
Hey @guiguan, unfortunately right now there's no way to obtain that info from the message. However, it would be relatively low effort to enrich messages with some sort of metadata regarding the error of the last failed output.

We can't rely on populating a processor error (which determines the result of `error()` and `errored()`) as that would break processing error handling in subsequent outputs, but we could choose a metadata key to add to messages and document it, maybe something like `benthos_output_failed`, which would allow you to do stuff like this:

```
output:
  fallback:
    - foo: {}
    - bar: {}
      processors:
        - bloblang: |
            root = this
            root.routing_error = meta("benthos_output_failed")
```
