### ISSUE TITLE
Add Interpolation/dynamic routing support for redis streams

### ISSUE THREAD

**Issue by agrawalravi90** [benthosdev/benthos#1083]
For Kafka, benthos supports dynamic routing, e.g:
```
output:
  kafka:
    addresses: [ TODO ]
    topic: ${! meta("output_topic") }
    key: ${! meta("key") }
```

It would be great if similar support could be added for redis streams, if possible.
