### ISSUE TITLE
Azure authentication via managed identity

### ISSUE THREAD

**Issue by sthussey** [benthosdev/benthos#1084]
Any interest in supporting [managed identity](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview) authentication for the Azure components? I'd be happy to attempt a PR to implement it.

**Comment by Jeffail** [comment]
Hey @sthussey, yeah absolutely. It might be worth doing a tidy-up of the azure authentication fields as they're getting a bit unwieldy. If you let me know what new fields would be necessary for this I'll draw up a new config spec we could try out.

**Comment by sthussey** [comment]
I don't see a great way to clean it up too much, but maybe it would improve the UX a bit if we segregated the authn stuff like below. However the connection string straddles service addressing and authentication, so not sure what the best option is there. Possibly ignore the entire authentication stanza if `storage_connection_string` is set?

```
azure_blob_storage:
    storage_account: ""
    storage_connection_string: ""
    authentication:
        type: "SAS |  SharedKey | ServicePrincipal | ManagedIdentity"
        access_key: ""
        sas_token: ""
        identity_principal_id: ""
        identity_principal_secret: ""
    container: ""
    prefix: ""
    codec: all-bytes
```
