### ISSUE TITLE
Allow caching the result of a series of processors

### ISSUE THREAD

**Issue by disintegrator** [benthosdev/benthos#1099]
This a proposal for a higher-order `cached` processor that can wrap a series of processors and cache their results if they successfully process messages batches. The proposed API looks like this:

```yaml
pipeline:
  processors:
    cached:
      resource: foocache
      key: '${! json("message.id") }'
      ttl: 5m
      processors:
        - resource: expensive_processor_1
        - resource: expensive_processor_2
        - resource: expensive_processor_3
```
