### ISSUE TITLE
Performing aggregation across multiple Kafka partitions

### ISSUE THREAD

**Issue by Archanian** [benthosdev/benthos#1156]
Hello there! I'm working on a benthos config to generate aggregated counts (as a json document) from a stream of events (Kafka topic). The topic has 30 partitions, and the events within it take the following shape (irrelevant properties omitted):
```
{ "AccountID": 1, Count: 3 }
```

I'm trying to generate a summary that is an aggregation of the counts for all accounts, ie:
```
{
  "Account-1": 4,
  "Account-2": 1,
  "Account-3": 6,
}
```
I'm able to get what I want, but isolated to each partition. I'm struggling to combine everything into a single output document. So far I've come up with this:
```
input:
  kafka:
    addresses:
      - ${KAFKA_BROKER}
    batching:
      period: 10s
    checkpoint_limit: 100000
    consumer_group: ""
    start_from_oldest: false
    topics:
      - my-topic:0-29

pipeline:
  threads: 20
  processors:
    - bloblang: |
        root = { this.AccountID.string(): this.Count }
    - archive:
        format: json_array
    - bloblang: |
        root = this.fold({}, x -> x.tally.merge(x.value)).map_each(x -> x.value.sum())

output:
  file:
    path: ./test/output-${! uuid_v4() }.json
```
This produces what I want, but one document _for each partition_, so every 10s I get 30 output documents. What I want is to produce a _single_ document with totals for events across all partitions, every 10 seconds. Maybe what I'm attempting to do isn't even possible, since the partitions are being processed in parallel?

> Note I am using a file output for ease of testing, the final/production output is going to be sending these blobs off to a message queue.

I played around with removing batching from the input, and using a broker for the output so I could specify batching there (since a file output doesn't have that option), but I'm a little unsure as to what I should do. Any suggestions would be greatly appreciated, thanks!

**Comment by Jeffail** [comment]
Hey @Archanian, yeah what you're seeing here is that the batching is done independently for each topic/partition. I'd say the easiest set up is to remove batching from the input and use a [`system_window` buffer](https://www.benthos.dev/docs/components/buffers/system_window):

```yaml
input:
  kafka:
    addresses:
      - ${KAFKA_BROKER}
    checkpoint_limit: 100000
    consumer_group: ""
    start_from_oldest: false
    topics:
      - my-topic:0-29

buffer:
  system_window:
    timestamp_mapping: root = now()
    size: 10s

pipeline:
  threads: 20
  processors:
    - bloblang: |
        root = { this.AccountID.string(): this.Count }
    - archive:
        format: json_array
    - bloblang: |
        root = this.fold({}, x -> x.tally.merge(x.value)).map_each(x -> x.value.sum())

output:
  file:
    path: ./test/output-${! uuid_v4() }.json
```
