### ISSUE TITLE
Expose connection sql settings as config fields

### ISSUE THREAD

**Issue by pcha** [benthosdev/benthos#1158]
Such as we speak in [slack](https://gophers.slack.com/archives/CLWCBK7FY/p1646757016622569) would be great if benthos support the [sql connection settings](https://github.com/go-sql-driver/mysql#dsn-data-source-name).

I thing that it could be setted in the keys `conns_max_lifetime`, `max_open_conns` and `max_iddle_conns`.

Full config example:

```yaml
# All config fields, showing default values
label: ""
sql_select:
  driver: ""
  dsn: ""
  table: ""
  columns: []
  where: ""
  args_mapping: ""
  prefix: ""
  suffix: ""
  conns_max_lifetime: 0
  max_open_conns: 0
  max_iddle_conns: 0
```
