### ISSUE TITLE
subprocess with bash script

### ISSUE THREAD

**Issue by mohamed--abdel-maksoud** [benthosdev/benthos#1171]
Hi,
I'm trying to execute a complex shell script under `subprocess` processor. It seems any thing except just `cat`ing the piped input hangs the whole pipeline (example below). I'd appreciate any help.
Thanks

```
input:
  label: ""
  generate:
    mapping: root = {"id":uuid_v4()}
    interval: 1s
pipeline:
  threads: 1
  processors:
    - subprocess:
        name: bash
        args: [ "-c", "cat" ]   # this works
        #args: [ "-c", "x=$(cat); stdbuf -o0 echo $x" ] # this doesn't work
output:
  label: ""
  stdout:
    codec: lines
    delimiter: ""
```
