### ISSUE TITLE
Prometheus: prefix option got removed in v4

### ISSUE THREAD

**Issue by benschoch** [benthosdev/benthos#1187]
In v3 there was a config option for prometheus metrics to get a prefix set on the metrics:
https://github.com/benthosdev/benthos/blob/c82f93ec164b0b97c39e54a8815547f582b5b716/lib/metrics/prometheus.go#L153

It seems like this feature got removed in v4. Is there a reason for that? I'd be happy to re-introduce it and create a PR for it. Just want to make sure that there wasn't a good reason for the removal.

**Comment by Jeffail** [comment]
Hey @benschoch it's because it overlaps with the `mapping` field, in v4 you can do

```yaml
metrics:
  mapping: 'root = "someprefix_" + this'
  prometheus: {}
```
