### ISSUE TITLE
Incrementing offset value is not working while running cron jobs inside input_resources

### ISSUE THREAD

**Issue by yubraj-ghimire** [benthosdev/benthos#1189]
Hello @Jeffail

I am having an issue incrementing the offset value attached to the endpoint while running the cronjobs.

Current Use Case:
- The instance gets triggered every 5 min to read data from the `PRODUCT_API_ENDPOINT` with  some `limit` and `offset` values as a parameters

Problem:
- The instance triggers every 5 min and calls the endpoints with `offset=0`and it would again wait another 5 min call the endpoint with  `offset=0`, it would never get increased by 2 in the second call rather it would always start from the beginning which is again `offset=0`

Expected Behaviour:
- The instance triggers every 5 min, it reads the data from the `PRODUCT_API_ENDPOINT` with a `limit = 2 ` and `offset = 0` since there would be no offset value in the initial call. And on the second call to the endpoint, the offset should increase by 2
-  I can achieve the above-expected behavior if I remove cron jobs from the input_resources.

```
1st call -> offset = 0
2nd call -> offset = 2
3rd call -> offset = 4
```
Here below is how my `input_resources` is looking

```yaml
input_resources:
  - label: ct_product_projections
    read_until:
      restart_input: true
      check: this.results.length() == 0
      input:
        generate:
          interval: '@every 5m'
          mapping: 'root = ""'
        processors:
          - http:
              url: https://PRODUCT_API_ENDPOINT/?limit=2&offset=${! (json("offset") + 2).not_null() | 0 }
              verb: GET
              headers:
                Content-Type: application/json
```

Is there a way to run the cron jobs and also address the offset increment while calling the endpoint? 

Thanks. 

Cheers 
Yub

**Comment by mihaitodor** [comment]
Hey @yubraj-ghimire, thanks for raising this issue! I think you're looking for the bloblang [`count`](https://www.benthos.dev/docs/guides/bloblang/functions#count) function in combination with [metadata](https://www.benthos.dev/docs/guides/bloblang/about#metadata). Try the pipeline below and let me know if that helps:

```yaml
input_resources:
  - label: ct_product_projections
    read_until:
      restart_input: true
      check: this.results.length() == 0
      input:
        generate:
          interval: "@every 5m"
          mapping: 'root = ""'
        processors:
          - http:
              url: https://PRODUCT_API_ENDPOINT/?limit=2&offset=${! (meta("counter").number() + 2).not_null() | 0 }
              verb: GET
              headers:
                Content-Type: application/json
          - bloblang: |
              meta counter = count("input_counter")
          - log:
              message: ${! meta("counter") }

input:
  resource: ct_product_projections

output:
  stdout: {}
```

Hope there aren't any errors in it.

**Comment by Jeffail** [comment]
Unfortunately that won't work as the `http` processor references the message being processed (the message generated by the `generate` input) for interpolation functions, rather than the last response received. 

You have a couple of options, the first would be to replace the generate input and http processor with an `http_client` input, but replace the generate 5m interval for a rate limit that limits to 5 minutes instead:

```yaml
input_resources:
  - label: ct_product_projections
    read_until:
      restart_input: true
      check: this.results.length() == 0
      input:
        http:
          url: https://PRODUCT_API_ENDPOINT/?limit=2&offset=${! (json("offset") + 2).not_null() | 0 }
          verb: GET
          rate_limit: product_requests
        headers:
          Content-Type: application/json

rate_limit_resources:
  - label: product_requests
    local:
      count: 1
      interval: 5m
```

The other option is to sandwich your `http` processor with cache processors that attempt to obtain a cached offset (defaulting to zero if no cache item yet) and then after the `http` request caches the current offset for the next request. You can see an example of this kind of pattern in the discord input template: https://github.com/benthosdev/benthos/blob/main/template/inputs/discord.yaml#L121
