### ISSUE TITLE
Confusing error message when parsing blobl map with unquoted key

### ISSUE THREAD

**Issue by mihaitodor** [benthosdev/benthos#1191]
This came up on Discord and thought I'd open an issue to not forget about it. The following config:

```yaml
input:
  generate:
    mapping: |
      root = {
        id: count("foo")
      }
    interval: 0s
    count: 1

output:
  stdout:
    codec: lines
```

Produces `"Failed to read message: failed assignment (line 1): unable to reference message as structured (with 'this'): message is empty"`, which can be confusing, since `this` is implicit, so it tries to find the field `id` on it.
