### ISSUE TITLE
How to resolve branch error - stream error: stream ID 1; PROTOCOL_ERROR; received from peer

### ISSUE THREAD

**Issue by yubraj-ghimire** [benthosdev/benthos#1192]
Hey @Jeffail,

I am using altogether two `branch` within my `processors` to fetch some data and create a final payload to pass on to the output, but the last branch is throwing some branching error, I have included the snippet of processors as well as the error log.

**Processors**

```
pipeline:
  processors:
    - bloblang: root = if (this.results.length() == 0) {
        deleted()
        }
    - bloblang:
        | # get array of variants (which may be empty) and append the masterVariant
        root.items = this.results.map_each(item -> item.variants.map_each(
            variant -> variant.without("assets", "images", "prices", "attributes","sku", "id")
          ).flatten().append(
            item.masterVariant.without("assets", "images", "prices", "attributes", "sku", "id")
          )).flatten()
      label: flatten_variants
    - log:
        message: ${! json("items")}
    - branch:
        request_map: root.articleShopIds = json("items").map_each(variant -> variant.key) # in branch content is byte again, you need to parse it again!
        processors:
          - http:
              url: http://article-shop-quantity-reader.prod.zooplus.net/api/v1/quantity
              verb: POST
              headers:
                Content-Type: application/json
                X-Caller: swagger-ui
            label: call_zoo_inventory
        result_map: |
          root.zooQuantity = this.map_each(item -> {"key": item.asId.string(), "zooStock": item.availableQuantity}).flatten() # bubble up to parent and need to decide what would be the threshold
    - bloblang: |
        root.items = this.items.map_each(item -> this.zooQuantity.filter(zoo -> zoo.key == item.key).index(0).assign(item)) # merge zooQuantity with items
      label: merge_zoo_inventory
    - bloblang: |
        root = this.items.filter(item -> item.zooStock != item.availability.availableQuantity)
      label: filter_unchanged
    - bloblang: root = if (this.length() == 0) { deleted() }
    - unarchive:
        format: json_array
      label: split_messages
    - bloblang: meta inventoryId = this.availability.id
    - branch:
        request_map: 'root = ""'
        processors:
          - http:
              url: https://api.europe-west1.gcp.commercetools.com/zooplus-dev/inventory/${! meta("inventoryId")}
              verb: GET
              headers:
                Content-Type: application/json
              oauth2:
                enabled: true
                client_key: 'key'
                client_secret: 'secret'
                token_url: 'token_url'
            label: call_zoo_inventory_version
        result_map: |
          root.inventoryVersion = this.version
    - bloblang: |
        root.id = this.availability.id
        root.version = this.inventoryVersion
        root.actions = [{"action": "changeQuantity", "quantity": this.zooStock}]
      label: assemble_payload

output:
  stdout: {}
```

**Log:**

`{"@timestamp":"2022-03-31T12:44:38+02:00","@service":"benthos","component":"benthos.pipeline.processor.10","level":"ERROR","message":"Branch error: processors failed: https://api.europe-west1.gcp.commercetools.com/zooplus-dev/inventory/02b6dd5f-a8a4-4a7f-9ba0-d35736a601a5: stream error: stream ID 1; PROTOCOL_ERROR; received from peer"}`

I would really look forward to knowing where I am doing wrong.

Thanks.
Cheers. 
Yub

**Comment by Jeffail** [comment]
Hey @yubraj-ghimire, the error message `stream error: stream ID 1; PROTOCOL_ERROR; received from peer` is actually coming from the http server being accessed rather than a problem with your config.

Some hints on the issue here: https://github.com/grpc/grpc-go/issues/576, but without knowing what the server is it's impossible to say what the problem is.

**Comment by yubraj-ghimire** [comment]
Hey @Jeffail, well, I double-check with the oauth2, it works just fine if I put the second branch just beneath the first one, it doesn't throw any error, this is really weird to me. 

```
processors:
    - bloblang: root = if (this.results.length() == 0) {
        deleted()
        }
    - bloblang:
        | # get array of variants (which may be empty) and append the masterVariant
        root.items = this.results.map_each(item -> item.variants.map_each(
            variant -> variant.without("assets", "images", "prices", "attributes","sku", "id")
          ).flatten().append(
            item.masterVariant.without("assets", "images", "prices", "attributes", "sku", "id")
          )).flatten()
      label: flatten_variants
    # - log:
    #     message: ${! json("items")}
    - branch:
        request_map: root.articleShopIds = json("items").map_each(variant -> variant.key) # in branch content is byte again, you need to parse it again!
        processors:
          - http:
              url: http://article-shop-quantity-reader.prod.zooplus.net/api/v1/quantity
              verb: POST
              headers:
                Content-Type: application/json
                X-Caller: swagger-ui
            label: call_zoo_inventory
        result_map: |
          root.zooQuantity = this.map_each(item -> {"key": item.asId.string(), "zooStock": item.availableQuantity}).flatten() # bubble up to parent and need to decide what would be the threshold
    - branch:
        request_map: 'root = ""'
        processors:
          - http:
              url: https://api.europe-west1.gcp.commercetools.com/zooplus-dev/inventory/8a621fa6-7702-4c1f-91e3-13e0adb85bc0
              verb: GET
              headers:
                Content-Type: application/json
              oauth2:
                enabled: true
                client_key: 'key'
                client_secret: 'secret'
                token_url: 'token_url'
            label: call_zoo_inventory_version
          - log:
              message: ${! content()}
        result_map: |
          root.inventoryVersion = this.version
    # - log:
    #     message: ${! json("zooQuantity")}
    - bloblang: |
        root.items = this.items.map_each(item -> this.zooQuantity.filter(zoo -> zoo.key == item.key).index(0).assign(item)) # merge zooQuantity with items
      label: merge_zoo_inventory
    - bloblang: |
        root = this.items.filter(item -> item.zooStock != item.availability.availableQuantity)
      label: filter_unchanged
    - bloblang: root = if (this.length() == 0) { deleted() }
    - log:
        message: '------------------'
    - unarchive:
        format: json_array
      label: split_messages
    - bloblang: |
        root.id = this.availability.id
        root.oldVersion = this.availability.version
        root.version = this.inventoryVersion
        root.actions = [{"action": "changeQuantity", "quantity": this.zooStock}]
      label: assemble_payload
output:
  stdout: {}
```
