### ISSUE TITLE
sql insert output with clickhouse driver may cause benthos panic

### ISSUE THREAD

**Issue by derekwu0101** [benthosdev/benthos#1194]
Hi there,

I found an issue may cause benthos panic, maybe needs to add some error handling for this? 

below is my testing clickhouse table schema,
```sql
CREATE TABLE test
(
    `time` DateTime32,
    `array_field` Array(String)
)
ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(time)
ORDER BY (time);
```

and my benthos config
```yaml
pipeline:
  processors:
  - for_each:
    - bloblang: |
        root.time = this.time.parse_timestamp_unix().format_timestamp("2006-01-02 15:04:05", "UTC")
        root.array_field = this.array_field
output:
  sql_insert:
    driver: clickhouse
    dsn: "${CLICKHOUSE_DSN}"
    table: "test"
    columns: [
        'time',
        'array_field'
    ]
    args_mapping: '[
        this.time,
        this.array_field
    ]'
```

it works well but if `array_field` in your input data is null, this will cause benthos panic
```
benthos-test-1    | {"@timestamp":"2022-04-01T06:18:01Z","@service":"benthos","component":"benthos.output","level":"TRACE","message":"Attempting to write 1 messages to 'sql_insert'."}
benthos-test-1    | panic: reflect: call of reflect.Value.Interface on zero Value
benthos-test-1    | 
benthos-test-1    | goroutine 65 [running]:
benthos-test-1    | reflect.valueInterface({0x0, 0x0, 0x221c720}, 0xc0)
benthos-test-1    |     /usr/local/go/src/reflect/value.go:1356 +0x10e
benthos-test-1    | reflect.Value.Interface(...)
benthos-test-1    |     /usr/local/go/src/reflect/value.go:1351
benthos-test-1    | github.com/ClickHouse/clickhouse-go/lib/data.(*Block).AppendRow(0xc00179c140, {0xc000dfb200, 0x59, 0xc0001139d0})
benthos-test-1    |     /go/pkg/mod/github.com/!click!house/clickhouse-go@v1.5.1/lib/data/block.go:149 +0x4d1
benthos-test-1    | github.com/ClickHouse/clickhouse-go.(*stmt).execContext(0xc0015e9110, {0x30a2cb0, 0xc00005c170}, {0xc000dfb200, 0xc000b901b0, 0xc000a9cdc0})
benthos-test-1    |     /go/pkg/mod/github.com/!click!house/clickhouse-go@v1.5.1/stmt.go:56 +0x52
benthos-test-1    | github.com/ClickHouse/clickhouse-go.(*stmt).ExecContext(0xc000b901b0, {0x30a2cb0, 0xc00005c170}, {0xc000a9c000, 0x59, 0xbcd27c})
benthos-test-1    |     /go/pkg/mod/github.com/!click!house/clickhouse-go@v1.5.1/stmt.go:50 +0x85
benthos-test-1    | database/sql.ctxDriverStmtExec({0x30a2cb0, 0xc00005c170}, {0x30a2e70, 0xc0015e9110}, {0xc000a9c000, 0x59, 0x59})
benthos-test-1    |     /usr/local/go/src/database/sql/ctxutil.go:65 +0x132
benthos-test-1    | database/sql.resultFromStatement({0x30a2cb0, 0xc00005c170}, {0x307de88, 0xc000b901b0}, 0xc0001f5cc0, {0xc000dfac00, 0x59, 0x59})
benthos-test-1    |     /usr/local/go/src/database/sql/sql.go:2622 +0x145
benthos-test-1    | database/sql.(*Stmt).ExecContext(0xc000b90120, {0x30a2cb0, 0xc00005c170}, {0xc000dfac00, 0x59, 0x59})
benthos-test-1    |     /usr/local/go/src/database/sql/sql.go:2595 +0x205
benthos-test-1    | database/sql.(*Stmt).Exec(...)
benthos-test-1    |     /usr/local/go/src/database/sql/sql.go:2610
benthos-test-1    | github.com/Jeffail/benthos/v3/internal/impl/sql.(*sqlInsertOutput).WriteBatch(0xc0010305b0, {0x30a2c78, 0xc0001f4540}, {0xc00000f630, 0x1248dbd, 0x1})
benthos-test-1    |     /go/src/github.com/Jeffail/benthos/internal/impl/sql/output_sql_insert.go:229 +0x5db
benthos-test-1    | github.com/Jeffail/benthos/v3/public/service.(*airGapBatchWriter).WriteWithContext(0xc000f4a168, {0x30a2c78, 0xc0001f4540}, {0x30d9040, 0xc0015e85a0})
benthos-test-1    |     /go/src/github.com/Jeffail/benthos/public/service/output.go:137 +0xe2
benthos-test-1    | github.com/Jeffail/benthos/v3/lib/output.(*AsyncWriter).latencyMeasuringWrite(0xc00004ff00, {0x30d9040, 0xc0015e85a0})
benthos-test-1    |     /go/src/github.com/Jeffail/benthos/lib/output/async_writer.go:121 +0xd4
benthos-test-1    | github.com/Jeffail/benthos/v3/lib/output.(*AsyncWriter).loop.func4()
benthos-test-1    |     /go/src/github.com/Jeffail/benthos/lib/output/async_writer.go:269 +0x353
benthos-test-1    | created by github.com/Jeffail/benthos/v3/lib/output.(*AsyncWriter).loop
benthos-test-1    |     /go/src/github.com/Jeffail/benthos/lib/output/async_writer.go:310 +0x5a5
benthos-test-1 exited with code 2

```

Cheers.
