### ISSUE TITLE
The HDFS directory should support interpolation functions

### ISSUE THREAD

**Issue by FourSpaces** [benthosdev/benthos#1195]
Hi! I use the HDFS output plug-in to write data into hive,

This is the configuration of the HDFS output plug-in：
```
output:
  label: ""
  hdfs:
    hosts:
      - localhost:9000
    user: benthos_hdfs
    directory: ""
    path: ${!count("files")}-${!timestamp_unix_nano()}.txt
```

I need to write the data into the `directory` with date, which changes dynamically.

For example:
```
/data/ds=2022-04-02/
/data/ds=2022-04-03/
```

I hope the catalog can realize the interpolation function. I can use the following example to complete my requirements:

`directory：“/data/ds=${!now().format_timestamp(\"2006-01-02\")}/”`

Of course, I can also contribute this part of the code, It looks simple.
