### ISSUE TITLE
The `fallback` output should stop trying to send messages to unreachable outputs

### ISSUE THREAD

**Issue by mihaitodor** [benthosdev/benthos#1210]
The following config will keep trying to send messages to the `kafka_franz` output if it's unavailable, although there's an `stdout` fallback output configured:

```yaml
input:
  generate:
    mapping: |
      root.id = count("foo_counter1")
    interval: 0s
    count: 3

pipeline:
  threads: 1
  processors:
    - bloblang: |
        root = match {
          this.id == 1 => {"msg": "foo"}
          this.id == 2 => {"msg": "bar"}
          _ => throw("UNKNOWN ID")
        }

        root.id = this.id

output:
  switch:
    retry_until_success: true
    cases:
      - check: errored()
        output:
          stdout:
            codec: lines
          processors:
            - log:
                message: "errored message: ${! json()}"

      - output:
          fallback:
            - kafka_franz:
                seed_brokers:
                  - localhost:6666
                topic: test
            - stdout:
                codec: lines
          processors:
            - log:
                message: "successful message: ${! json()}"

logger:
  level: DEBUG
  format: json
  add_timestamp: true
  static_fields:
    "@service": benthos

shutdown_timeout: 3s # Default 20s
```

From the Discord chat, it looks like the solution would be to try and detect connection loss via an enhancement.
