### ISSUE TITLE
Fragmented Tests: Failed to obtain test targets

### ISSUE THREAD

**Issue by davidlday** [benthosdev/benthos#1214]
```bash
benthos --version
Version: 3.65.0
Date: 2022-03-08T05:12:59Z
```

I'm implementing unit tests via [fragmented tests](https://www.benthos.dev/docs/configuration/unit_testing/#fragmented-tests). My project is structures like this:

```bash
.
├── benthos.yaml
├── resources
│   ├── inputs.yaml
│   ├── outputs.yaml
│   ├── processors.yaml
├── streams
│   ├── stream_a.yaml
│   └── stream_b.yaml
└── tests
    ├── stream_a_benthos_test.yaml
    └── stream_b_benthos_test.yaml
```

In my tests, I reference the target processors using JSON pointers, like this:

```yaml
tests:
    - name: Stream A Test
      environment: {}
      target_processors: '../streams/stream_a.yaml#/pipeline/processors'
      input_batch:
        ...
```

I execute my tests in the project root like this:

```bash
benthos -r "./resources/*.yaml" test "./tests/stream_a_tests.yaml"
```

And I get the following error:

```bash
Failed to obtain test targets: unable to access target config file 'tests/stream_a.yaml': stat tests/stream_a.yaml: no such file or directory
```

Even though I use a JSON pointer in the test file, benthos still seems to be looking for the config in the same directory as the test file. I've search through the issues and don't see anything related already, so I'm not sure if this is a bug or if I'm just completely missing something in the docs.
