### ISSUE TITLE
Gracefully exit when configuring multiple metrics processors with the same name but different label count

### ISSUE THREAD

**Issue by mihaitodor** [benthosdev/benthos#1249]
Currently, Benthos panics if we run a config with two metrics processors that have the same name but different label count. I guess this is an invalid config, but we should try to exit gracefully instead.

The issue can be reproduced with Benthos V4 using the following config:

```yaml
input:
  generate:
    mapping: 'root = {}'

pipeline:
  processors:
    - metric:
        type: gauge
        name: kaboom
        labels: {"foo": "bar"}
        value: '${! count("foo") }'

    - metric:
        type: "gauge"
        name: kaboom
        labels: {"foo": "bar", "will": "panic"}
        value: '${! count("bar") }'

output:
  stdout: {}
```

```shell
mihaitodor@brainiac:~$ benthos -c conf.yaml
INFO Launching a benthos instance, use CTRL+C to close.  @service=benthos
panic: inconsistent label cardinality: expected 3 label values but got 4 in []string{"", "root.pipeline.processors.1", "bar", "panic"}

goroutine 46 [running]:
github.com/prometheus/client_golang/prometheus.(*GaugeVec).WithLabelValues(0xc00016fc38?, {0xc000c58080?, 0x104e052?, 0x40?})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/gauge.go:217 +0x85
github.com/benthosdev/benthos/v4/internal/impl/prometheus.(*promGaugeVec).With(0x107dfcf?, {0xc000c58080?, 0x5?, 0xc000146240?})
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/impl/prometheus/metrics_prometheus.go:139 +0x25
github.com/benthosdev/benthos/v4/internal/component/metrics.(*gaugeVecWithStatic).With(0xc000ad3b90, {0xc000146240, 0x2, 0x40?})
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/component/metrics/namespaced.go:133 +0x154
github.com/benthosdev/benthos/v4/internal/old/processor.(*Metric).handleGauge(0xc000bc0000, {0x589b5c8?, 0x4251250?}, 0xc00162e3f0?, 0x100ec3d0?)
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/old/processor/metric.go:319 +0xb3
github.com/benthosdev/benthos/v4/internal/old/processor.(*Metric).ProcessMessage.func1(0x100ec3d0?, 0x2?)
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/old/processor/metric.go:346 +0x67
github.com/benthosdev/benthos/v4/internal/old/processor.iterateParts.func1(0x0)
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/old/processor/util.go:118 +0x1d1
github.com/benthosdev/benthos/v4/internal/old/processor.iterateParts({0x0?, 0x1015766?, 0x0?}, 0xc00162e3f0, 0x0?)
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/old/processor/util.go:122 +0xd0
github.com/benthosdev/benthos/v4/internal/old/processor.(*Metric).ProcessMessage(0x369b3e0?, 0xc00162e3f0)
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/old/processor/metric.go:344 +0x56
github.com/benthosdev/benthos/v4/internal/old/processor.ExecuteAll({0xc000e65bc0, 0x2, 0xc0001aa008?}, {0xc000139720?, 0x1, 0x1?})
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/old/processor/util.go:19 +0x18c
github.com/benthosdev/benthos/v4/internal/pipeline.(*Processor).loop(0xc000bda580)
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/pipeline/processor.go:71 +0x1ff
created by github.com/benthosdev/benthos/v4/internal/pipeline.(*Processor).Consume
	/private/tmp/benthos-20220421-5150-chhvdr/benthos-4.0.0/internal/pipeline/processor.go:141 +0x79
```
