### ISSUE TITLE
config using environment variable in array

### ISSUE THREAD

**Issue by yusufsyaifudin** [benthosdev/benthos#1260]
In the documentation here https://v4.benthos.dev/docs/configuration/resources/#with-environment-variables we can define environment variable using `${ENV_KEY}` such as:

```yaml
pipeline:
  processors:
    - resource: ${FEATURE_REQUEST}

```

and we can call Benthos `FEATURE_REQUEST=get_foo benthos -c ./your_config.yaml`

But, in my use-case I want to add environment variable as an array, for example:

```yaml
input_resources:
  - label: in_kafka
    kafka:
      addresses:
        - ${KAFKA_URL1}
        - ${KAFKA_URL2}
        - ${KAFKA_URL3}
      topics:
        - benthos_topic
```

How could I define only using one env variable of Kafka addresses? By this I mean, how can I define only `KAFKA_URL` and save it as comma separated value (or semicolon, or anything) and then mapped as array in YAML file?

Thank you!
