### ISSUE TITLE
incrbyfloat on redis processor

### ISSUE THREAD

**Issue by yusufsyaifudin** [benthosdev/benthos#1264]
I think `incrby` is not enough for processing float number. Any plan to add `incrbyfloat` on redis processor?
Also, I think it is good if we can pass our own argument such as 

```yaml
processors:
  - redis:
      kind: simple
      url: "redis://localhost:6379"
      cmd: ["HINCRBYFLOAT", "hash_group_key", "$this.key.from.json", "$this.value.from.json" ]
```

`$this` represent that it is the variable from bloblang. 

Using above configuration, developer can easily to do any operation on redis, not limited by the rule of Benthos. I don't know if that possible in current Benthos system design, but I think it is good idea to have capability that closer to that.

Thanks!

**Comment by Jeffail** [comment]
Hey @yusufsyaifudin, I think this is a great idea and makes total sense. I'll probably do a soft-refactor of the `redis` processor so that the old fields will still work but the documentation outlines a new, more generalised, schema.

I think I'd probably opt for some sort of `cmd_mapping` field where you express the array of command arguments as a bloblang mapping that results in an array, so something like this:

```
processors:
  - redis:
      url: TODO
      cmd_mapping: 'root = [ "INCRBYFLOAT", "hash_group_key", meta("foo_key"), this.something.else ]'
```
