### ISSUE TITLE
How do I stop processing a message?

### ISSUE THREAD

**Issue by jajeffries** [benthosdev/benthos#1266]
I want to conditionally stop processing and not output a message. I still want it to be ack'ed in kafka. For example, I have a message like

```
{
  "a": "dropme",
  "b": 1
}
```
and I want to drop messages where `a == "dropme"`. Ideally I would like to do this before my `transform` processor.

```
input:
  label: ""
  kafka:
    addresses: ['mykafkahost:9092']
    topics: ['mytopic']
    target_version: 2.0.0
    consumer_group: "blah"
    checkpoint_limit: 1024
    start_from_oldest: false
    tls:
      enabled: true
    sasl:
      user: user
      password: password
      mechanism: mechanism

pipeline:
  processors:
    - label: transform
      bloblang: |
        root = this
        root.a = deleted()
output:
  label: "stdout"
  stdout:
    codec: lines
```
How would I go about doing this?
