### ISSUE TITLE
How to limit memory usage

### ISSUE THREAD

**Issue by skyoct** [benthosdev/benthos#1282]
Hello!
I use Kafka for input and S3 for output. Output is slower than input. How to use a buffer to limit the total memory used? When the buffer is full, Kafka stops pulling。

**Comment by skyoct** [comment]
Thanks for your help @Jeffail I now use Buffer -> Memory to limit memory growth, This makes my program not appear OOM. But I found promethues error in the process of using it.
```
ERRO Metrics label mismatch 2 versus 3 [label path mechanism] for name 'batch_created', skipping metric  @service=benthos
```
This is my config
```
input:
  kafka:
    addresses:
      - xxxxx:9092
      - xxxxx:9092
      - xxxxx:9092
    checkpoint_limit: 2000
    client_id: xxxxx
    consumer_group: xxxxx
    target_version: 2.2.0
    topics:
      - xxxxx

  label: kafka


output:
  minio:
    endpoint: xxxxx:9000
    bucket_name: xxxxx
    secret_id: xxxxx
    secret_key: xxxxx
    directory: xxxxx
    max_in_flight: 50
    path: xxxxx
  label: minio

buffer:
  memory:
    limit: 377487360
    batch_policy:
      enabled: true
      byte_size: 125829120
      count: 20000
      period: 30s
      processors:
        - archive:
            format: lines
```

**Comment by mihaitodor** [comment]
Confirmed. I can repro that error with:

```yaml
input:
  broker:
    inputs:
      - stdin: {}
    batching:
      count: 1
      byte_size: 0
      period: "1s"
      check: ""

buffer:
  memory: {}

output:
  stdout: {}
```
