### ISSUE TITLE
About using memory

### ISSUE THREAD

**Issue by skyoct** [benthosdev/benthos#1288]
Hello
When I set the quantity of each batch to 2W, Container memory usage approx. 8g. 
Here are some configurations
```
input:
  kafka: xxxx

output:
  minio: xxxx

buffer:
  memory:
    limit: 125829120
    batch_policy:
      enabled: true
      byte_size: 29360128
      count: 20000
      period: 30s
      processors:
        - archive:
            format: lines
```

But when I adjust the batch number to 5000, the memory will reach 16g.
Here are the related configurations
```
input:
  kafka: xxxx

output:
  minio: xxxx

buffer:
  memory:
    limit: 125829120
    batch_policy:
      enabled: true
      byte_size: 29360128
      count: 5000
      period: 30s
      processors:
        - archive:
            format: lines
```
I would like to ask what may have caused this.
Also, why is there such a big difference between the memory used by the buffer limit and the real memory used.
