### ISSUE TITLE
log dose not show full timestamp

### ISSUE THREAD

**Issue by skyoct** [benthosdev/benthos#1305]
this is config
```
input:
  broker:
    inputs:
      - stdin: {}
    batching:
      count: 1
      byte_size: 0
      period: "1s"
      check: ""

buffer:
  memory: {}

output:
  stdout: {}

logger:
  level: INFO
  format: logfmt
  add_timestamp: true
  static_fields:
    '@service': benthos
```

This is the result of the run
![image](https://user-images.githubusercontent.com/24541857/174989958-65757494-73ce-4cba-9474-0369d17435db.png)
