### ISSUE TITLE
Data not flowing into the snowflake table even though benthos CLI is executing fine (no errors)

### ISSUE THREAD

**Issue by rajpaljatin19** [benthosdev/benthos#1319]
Attached is the sample CSV file I am trying to move to the snowflake table. But I am not seeing data being moving to snowflake and also not getting any error in CLI.

[emp.csv](https://github.com/benthosdev/benthos/files/9076485/emp.csv)

```
input:
  csv:
    paths: [/Users/jatinrajpal/workspace/fun_stuff/benthos/emp.csv]
    delimiter: ','

# Common config fields, showing default values
output:
  snowflake_put:
    account: "sr35298.europe-west2.gcp"
    user: "JATINRAJPAL"
    private_key_file: "/Users/jatinrajpal/workspace/fun_stuff/benthos/rsa_key.p8"
    private_key_pass: "Welcome@123"
    role: "ACCOUNTADMIN"
    database: "SNOWDB"
    warehouse: "SNOWWAREHOUSE"
    schema: "Public"
    path: "Snowflake"
    stage: "@%employee"
```

Job execution logs. i am using Benthos CLI mode:
```
atinrajpal@Jatins-MacBook-Air benthos % benthos -c ./api-to-csv.yaml
INFO Running main config from specified file       @service=benthos path=./api-to-csv.yaml
INFO Launching a benthos instance, use CTRL+C to close  @service=benthos
INFO Listening for HTTP requests at: http://0.0.0.0:4195  @service=benthos
INFO Pipeline has terminated. Shutting down the service  @service=benthos
```

Then queried the database but got no records moved
<img width="593" alt="image" src="https://user-images.githubusercontent.com/32235493/178105849-03d6d6c8-3e04-4da9-8a8f-6a0098f5d28a.png">

Let me know if any more information is required. Need your help to resolve this issue.
