### ISSUE TITLE
Unit testing for dropped messages

### ISSUE THREAD

**Issue by Ehcaning** [benthosdev/benthos#1322]
In Benthos 3.x we had the ability to test dropped messages like so:
```yaml
tests:
  - name: Test message is dropped when field b is not present
    environment: {}
    target_processors: ./resources-processors.yaml#/processor_resources/2
    input_batch:
      - content: '{"a":"a"}'
    output_batches:
```
But in Benthos 4.x, it's not possible, it will give us this error:
```
Test message is dropped when field b is not present [line 2]:
wrong batch count, expected 1, got 0
```

Can we have it back? Or is there any workaround for this?
I would be happy to create a PR to resolve it.
