### ISSUE TITLE
Add support for open telemetry collectors

### ISSUE THREAD

**Issue by DaniTulp** [benthosdev/benthos#1343]
To add support for more tracing back-ends it would be great if benthos could support [OpenTelemetry collectors](https://opentelemetry.io/docs/collector/). It would allow services like datadog (which is of interest for me 😛 ) or any other open telemetry collector to be used.

An [example implementation](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/examples/demo) of multiple collectors can be found here. In this example there are multiple collectors used over `grpc`, but there's also support for `http`. I'm not sure if there are any other standards that are supported.

From what I've gathered by looking at the `jaeger` implementation it looks fairly similar.

## Proposed minimal api
The below implementation should allow benthos to add support for multiple collectors over multiple protocols. This might miss some fields (or require some renaming) but I hope it brings the point across.
```yaml
tracer:
  open_telemetry_collector:
    grpc:
      - collector:
          url: ""
          tags: {}
      - collector:
          url: ""
          tags: {}
    http:
      - collector:
          url: ""
          tags: {}
      - collector:
          url: ""
          tags: {}
```
I'd be up for seeing if I could implement this if there aren't any major concerns. Any feedback would be appreciated!
