### ISSUE TITLE
Bloblang interpolation in http jwt claims

### ISSUE THREAD

**Issue by webfrank** [benthosdev/benthos#1350]
Hi, I was trying to use http processor with jwt enabled and I need to set the "iat" claim with current timestamp using this code:

```
jwt:
                  enabled: true
                  private_key_file: private.pem
                  signing_method: RS256
                  claims:
                    iss: iotbuilder
                    sub: benthos
                    iat: ${! timestamp_unix() * 1000 }
```

but on the server the decoded JWT is:

```
{
  iat: '${! timestamp_unix() * 1000 }',
  iss: 'iotbuilder',
  sub: 'benthos'
}
```

The iat claim is not interpolated.
