### ISSUE TITLE
Unit tests mocks ignored when target is a local named resource

### ISSUE THREAD

**Issue by DeusFacticius** [benthosdev/benthos#1356]
(Posting at the request of @Jeffail from benthos discord chat)

### Core issue
Using a mock to target a labeled / named processor resource does not actually apply the mock:

```yaml
# Test case for mocks issue
pipeline:
  processors:
    - resource: http_submit
processor_resources:
  - label: http_submit
    http:
      url: http://nonexistant.foo/
      verb: POST
tests:
  - name: test_case
    target_processors: /pipeline/processors
    mocks:
      http_submit:
        bloblang: 'root = {"abc": 123}'
    input_batch:
      - json_content:
          foo: bar
    output_batches:
      - - json_equals:
            abc: 123
          bloblang: '!errored()'
```
Result:
```shell
$ benthos test mocks_issue.yaml 
Test 'mocks_issue.yaml' failed

Failures:

--- mocks_issue.yaml ---

test_case [line 11]:
batch 0 message 0: bloblang: bloblang expression was false
batch 0 message 0: json_equals: JSON content mismatch
{
    "abc": 123,
    "foo": "bar"
}
batch 0 message 0: http://nonexistant.foo/: Post "http://nonexistant.foo/": dial tcp: lookup nonexistant.foo: no such host
```

As indicated by the error in the last line of the output, the mock did not stop benthos from trying to send an HTTP request to a non-existent URL.

### Partial Workaround # 1

An incomplete workaround (only applicable in simple cases) is to use a JSON pointer to target the mock, e.g.:
```yaml
# ...
tests:
  - name: test_case
    target_processors: /pipeline/processors
    mocks:
      /pipeline/processors/0:  # JSON pointer used instead of label name
        bloblang: 'root = {"abc": 123}'
    input_batch:
      - json_content:
          foo: bar
    output_batches:
      - - json_equals:
            abc: 123
          bloblang: '!errored()'
```
Result:
```shell
$ benthos test mocks_issue.yaml 
Test 'mocks_issue.yaml' succeeded
```
#### Failure case

However, this doesn't work if the target processor is itself referenced by another resource processor, e.g.:

```yaml
# Test case for mocks issue
pipeline:
  processors:
    - resource: my_branch
processor_resources:
  - label: my_branch
    branch:
      processors:
        - resource: http_submit
      result_map: root = this
  - label: http_submit
    http:
      url: http://nonexistant.foo/
      verb: POST
tests:
  - name: test_case
    target_processors: /pipeline/processors
    mocks:
      /processor_resources/1:  # I don't now if this is actually intended to work this way
        bloblang: 'root = {"abc": 123}'
    input_batch:
      - json_content:
          foo: bar
    output_batches:
      - - json_equals:
            abc: 123
          bloblang: '!errored()'
```
Result:
```shell
$ benthos test mocks_issue.yaml 
Test 'mocks_issue.yaml' failed

Failures:

--- mocks_issue.yaml ---

test_case [line 16]:
batch 0 message 0: bloblang: bloblang expression was false
batch 0 message 0: json_equals: JSON content mismatch
{
    "abc": 123,
    "foo": "bar"
}
batch 0 message 0: processors failed: http://nonexistant.foo/: Post "http://nonexistant.foo/": dial tcp: lookup nonexistant.foo: no such host
```
### Partial workaround # 2

By labeling the resource processor itself and using that name as the target for the mock, the mock is successfully applied:
```yaml
# Test case for mocks issue
pipeline:
  processors:
    - label: my_http_submit  # Note label used here
      resource: http_submit
processor_resources:
  - label: http_submit
    http:
      url: http://nonexistant.foo/
      verb: POST
tests:
  - name: test_case
    target_processors: /pipeline/processors
    mocks:
      my_http_submit:  # above label of the 'resource' used here
        bloblang: 'root = {"abc": 123}'
    input_batch:
      - json_content:
          foo: bar
    output_batches:
      - - json_equals:
            abc: 123
          bloblang: '!errored()'
```

However, applying a label to a `resource`  processor reference is considered a linter error, and while the unit test itself passes, the test run as a whole fails due to the lint error:

```shell
$ benthos test mocks_issue.yaml 
Test 'mocks_issue.yaml' failed

Failures:

--- mocks_issue.yaml ---

Lint: line 4: label field should be omitted when pointing to a resource
```

#### Sidenote

The particular context I encountered this in and would like to find a solution for is that of nested resource processors, very much like the scenario described  in the 'Failure case' example.  In the meantime, I've managed to still work through this by using SinatraRb to stub out a micro web API that can be run as a sidecar on localhost during tests, but this is definitely not the ideal solution.

For the record:
```shell
$ benthos --version
Version: 4.3.0
Date: 2022-06-23T18:32:27Z
```
Not tested on v4.4 yet, but I did not see anything in the changelog that suggests it would behave any differently.

**Comment by RafalGoslawski** [comment]
Hi, I've ran into the same issue, and unfortunately the processor I'd like to mock is inside a larger `switch` processor, so I can't seem to address it using the dot notation.

Let's say I want to mock the `bar` processor resource in the config below:

```yaml
pipeline:
  processors:
    - label: main_switch
      switch: 
        - check: content() == "alice"
          processors: 
            - resource: foo
            - resource: bar
            - resource: baz
        - check: content() == "bob"
          processors: 
            - resource: log
            - mapping: root = deleted()
        - processors: 
          - resource: log
          - mapping: root = deleted()

processor_resources:
  - label: foo
    noop: {}
  - label: bar
    noop: {}
  - label: baz
    noop: {}
  - label: log
    noop: {}

tests:
  - name: "a test"
    target_processors: '/pipeline/processors'
    mocks:
      bar:
        mapping: root = "charlie"
        
    input_batch:
      - content: "alice"
    output_batches:
      - - content_equals: "charlie"
```

Results:

```
Test '/benthos.yaml' failed

Failures:

--- /benthos.yaml ---

a test [line 38]:
batch 0 message 0: content_equals: content mismatch
  expected: charlie
  received: alice
```

What's surprising is that the `mocks: {"bar": ...}` directive didn't fail, it just seems it wasn't applied in the `/pipeline/processors` section.

What I ended up mocking:

```yaml
tests:
  - name: "a test"
    target_processors: '/pipeline/processors'
    mocks:
      main_switch: 
        switch:
          - check: content() == "alice"
            processors: 
              - resource: foo
              - mapping: root = "charlie"
              - resource: baz
          - check: content() == "bob"
            processors: 
              - resource: log
              - mapping: root = deleted()
          - processors: 
            - resource: log
            - mapping: root = deleted()
    input_batch:
      - content: "alice"
    output_batches:
      - - content_equals: "charlie"
```

Which works, but doesn't help readability of the test:
```
Test '/benthos.yaml' succeeded
```

I'm on the latest version.

```
$ benthos --version
Version: v4.10.0
Date: 2022-10-26T12:22:44Z
```
