### ISSUE TITLE
Complete pipeline spans not visible in GCP cloudtrace

### ISSUE THREAD

**Issue by dhruvsingh** [benthosdev/benthos#1359]
- After enabling tracing (`tracer`) for my pipeline with `gcp_cloudtrace`, I only see spans on the GCP console for the input resource of my pipeline (no processors/outputs)
The configuration that I used is 

```
tracer:
  gcp_cloudtrace:
    project: top_secret_project
    sampling_ratio: 1
    flush_interval: "30s"
```
![image](https://user-images.githubusercontent.com/1695796/182592499-1c554d2e-9721-41b5-ab6e-a9a47a237a65.png)
- From the [related discord discussion](https://discord.com/channels/746368194196799589/754099840354615296/1004327833138634752) seems like there is a problem when we use `archive` in the processor step of the pipeline
