### ISSUE TITLE
Interpolation errors are not logged by benthos when it fails

### ISSUE THREAD

**Issue by mannharleen** [benthosdev/benthos#1367]
consider the below config:
```
  processors:
    - log:
        level: DEBUG
        message: '${! content() + meta() }'
```
The above will fail; meta().string() should be used instead. 

Expected: benthos should log an error with the appropriate message
Actual: Instead of logging an error, the log processor actually logs an empty msg, like below:
``` 
DEBU                                               @service=benthos label="" path=root.pipeline.processors.0
```
