### ISSUE TITLE
How to correctly get the bytes in the protobuf file

### ISSUE THREAD

**Issue by Counterflowwind** [benthosdev/benthos#1376]
I try to get data from kafka. The messages are protobuf encoded. I am trying to use the Benthos protobuf processor. The type of data in protobuf is bytes, but the output is string, like "data":"CoKgAQp4EAEYAiDk7M2XBii".
## yaml file
```yaml
input:
  kafka:
pipeline:
  processors:
    - protobuf:
        operator: to_json
        message: subscribe.Envelope
        import_paths: [ subscribe/subscribe.proto ]
output:
  stdout: {}
```
## Envelop
```protobuf
message Envelope {
  int32  version = 1; 
  uint32 total = 2;
  uint32 index = 3;
  bytes  data = 4; 
}
```
How can I get bytes in protobuf?

**Comment by mihaitodor** [comment]
Hey @Counterflowwind, I have a feeling it might be due to an implicit base64 conversion from the `stdout` output. Would you mind trying the following:

```yaml
input:
  kafka:
pipeline:
  processors:
    - protobuf:
        operator: to_json
        message: subscribe.Envelope
        import_paths: [ subscribe/subscribe.proto ]
    - bloblang: |
        root.data = this.data.string()
    - log:
        message: ${! content() }
output:
  stdout: {}
```

If the log entry will contain the data in the format you expect, then, depending on the output you actually need to use, you might or might not need to force that conversion of the `data` field to string.

**Comment by Counterflowwind** [comment]
@mihaitodor I tried it and the result is still string, not the expected bytes. The output result like {"data":"Q3JLd0FRcDRFQUVZQWlEd29kS“}

**Comment by mihaitodor** [comment]
OK, I'm not really sure, but it sounds like you're looking for a byte encoding scheme. Would you mind showing what you're expecting the output to look like? Benthos has the [`encode`](https://www.benthos.dev/docs/guides/bloblang/methods#encode) bloblang method which you can use like this: `root.data = this.data.encode("hex")` for example, but we might need to add support for more encoding schemes.

**Comment by Counterflowwind** [comment]
@mihaitodor 
I want to convert the data into json, and then get the specific field information inside. But I got the error message. the error info is 
```
level=error msg="failed assignment (line 1): method decode: failed to parse value as JSON: invalid character '¨' looking for beginning of value" @service=benthos label="" path=root.pipeline.processors.1
level=error msg="failed assignment (line 1): method decode: failed to parse value as JSON: invalid character 'Ø' looking for beginning of value" @service=benthos label="" path=root.pipeline.processors.1
```
## yaml file
```yaml
input:
  kafka:
pipeline:
  processors:
    - protobuf:
        operator: to_json
        message: subscribe.Envelope
        import_paths: [ subscribe/subscribe.proto ]
    - bloblang: |
        root.data = this.data.decode("base64").parse_json()
output: 
  file:
    path: "./result.json"
    codec: lines
output:
  stdout: {}
```
What should I do to convert it to json correctly?
