### ISSUE TITLE
How to concatenate strings in awk？

### ISSUE THREAD

**Issue by Counterflowwind** [benthosdev/benthos#1382]
I try to get the mysql binlog from kafka, and then concatenate it into DML statement or DDL statement. How to concatenate correctly in awk？There doesn't seem to be a function available in awk.

**Comment by mihaitodor** [comment]
Hey @Counterflowwind, I'm not sure I get the issue you're facing and it would help to see an example of how you're trying to use the `awk` processor, maybe with a `generate` input and `stdout` output). I didn't play with it much, but it looks like it should support much of the awk functionality, since it's calling [goawk](https://github.com/benhoyt/goawk) under the hood. Here's an example on how to concatenate strings using awk: https://stackoverflow.com/questions/27028928/awk-concatenate-two-string-variable-and-assign-to-a-third

**Comment by Counterflowwind** [comment]
Hey @mihaitodor, Maybe I didn't make it clear. I hope to be able to concatenate strings in the processors of benthos' awk, how should this be done?

**Comment by mihaitodor** [comment]
> @mihaitodor, Maybe I didn't make it clear. I hope to be able to concatenate strings in the processors of benthos' awk, how should this be done?

I'm still not sure what you're asking or if this is a Benthos or an awk question. Let me share a sample config which uses the `awk` processor to concatenate strings:

```yaml
input:
  generate:
    mapping: |
      root = "foo,bar,baz"
    interval: 0s
    count: 1

pipeline:
  processors:
    - awk:
        codec: "text"
        program: |
          {split($0,a,","); print a[3]"-"a[2]"-"a[1]"-someextrastring"}

output:
  stdout: {}
```

Starting from this, can you illustrate what you'd like to achieve?
