### ISSUE TITLE
issue with the tracing: no Host in request URL

### ISSUE THREAD

**Issue by eleboucher** [benthosdev/benthos#1399]
Hello there, 

I'm running into an issue where I have this error showing in the logs
```
Post "http:///v1/traces": http: no Host in request URL
```
although the tracing works as we receive traces on our collector, I wonder if we may miss some traces.
here is my config:
```
tracer:
  open_telemetry_collector:
    http:
      - url: ${OTEL_HTTP_ENDPOINT:"otel:4318"}
    tags:
      service.name: ${DD_SERVICE:distribuo}
      service.version: ${DD_VERSION:latest}
      deployment.environment: ${DD_ENV:production}
```

benthos version: v4.5.1
thanks for your work, I hope we can find a solution to this issue

Step to reproduce
config.yml
```
input:
  http_server:
    path: /
    allowed_verbs:
      - POST
    timeout: 5s

output:
  redis_streams:
    url: redis://localhost:6379


pipeline:
  processors:
    - resource: process_payload

processor_resources:
  - label: process_payload
    bloblang: |
      root = {}

tracer:
  open_telemetry_collector:
    http:
      - url: 127.0.0.1:4318
 ```
 
 docker-compose.yml
 ```
version: "3.4"
services:
  otel:
    image: otel/opentelemetry-collector-contrib:0.57.2
    ports:
      - 4318:4318
      - 4317:4317
    volumes:
      - ./otel-config.yml:/etc/otelcol-contrib/config.yaml
```
otel-config.yml
```
receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:

exporters:
  logging:
    loglevel: debug

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
```
