### ISSUE TITLE
Using regexp matching in awk porcessor

### ISSUE THREAD

**Issue by Counterflowwind** [benthosdev/benthos#1417]
I want to be able to use regex in awk porcessor. just like this:
```go
pattern := `\s*\/\*.*\*\/\s*`
reg := regexp.MustCompile(pattern)
sql := reg.ReplaceAllString(originSql, "")
```
How to write the above logic in awk processor？

**Comment by mihaitodor** [comment]
Hey @Counterflowwind does this help you?

```yaml
input:
  generate:
    mapping: |
      root = [
        "/**/",
        " /*foobar*/",
        "/*foobar*/ ",
        " /*foobar*/ ",
        "/*foobar*/",
        "won't match",
      ]
    interval: 0s
    count: 1

pipeline:
  processors:
    - unarchive:
        format: json_array
    - awk:
        codec: "text"
        program: |
          {gsub(/\s*\/\*.*\*\/\s*/,"input was matched"); print;}
    - log:
        message: ${! error() }

output:
  stdout: {}
```

It generates the following output with Benthos v4.5.1:

```
"input was matched"
"input was matched"
"input was matched"
"input was matched"
"input was matched"
"won't match"
```
