### ISSUE TITLE
Act as an API adapter (HTTP proxy with response transformation)

### ISSUE THREAD

**Issue by natenho** [benthosdev/benthos#1419]
Hi! Fantastic project. I'm just getting started to it. I'm looking for some way to do the following;

1) Receive an HTTP request X with a given JSON payload A
`{ "fieldA": "foo" }`
2) Transform payload A into payload B
`{"fieldB": "foo-bar"}`
3) Send payload B to a foo-bar-server.com and get the response payload C
`{"response": "ok!"}`
4) Transform payload C into payload D
`{"status": "ok"}`
5) Synchronously reply to the request X with the payload D

Is that an easy use case to perform with Benthos? If so, can it do an even more complex scenario, like getting a JWT auth token before executing step 3?

It is not clear to me how to use [Synchronous Responses](https://www.benthos.dev/docs/guides/sync_responses) for that.

**Comment by Jeffail** [comment]
Hey @natenho, sounds like you want something like this:

```yaml
input:
  http_server:
    path: /post

pipeline:
  processors:
    - mapping: |
        root.fieldB = this.fieldA + "-bar"

    - http:
        url: foo-bar-server.com
        verb: POST

    - mapping: |
        root.status = root.response.trim("!")
  
output:
  sync_response: {}
```

The `sync_response` output is an indication to Benthos that whatever state the message is in is what should be returned back to the input source of the message, in this case the `http_server` request that triggered the message.

For JWT stuff you can potentially use mappings and a request within a [branch processor](https://www.benthos.dev/docs/components/processors/branch) to obtain a token header and store it in metadata, then use it in a subsequent request.

**Comment by natenho** [comment]
@Jeffail it worked!! but I had to change the line 
`root.status = root.response.trim("!")`
to 
`root.status = this.response.trim("!")`

Going one step forward studying benthos, I'm now trying to forward **all** the input request headers to the http processor, but I noticed that `meta` variables are mixed with these headers, so how to fix that?

Given the following config.yaml

```
input:
  http_server:
    path: /post

pipeline:
  processors:
    - mapping: |
        root.fieldB = this.fieldA + "-bar"

    - http:
        url: http://mockaco:5000/
        verb: POST
        metadata:
          include_patterns: [.*]
    - mapping: |
        root.status = this.response.trim("!")

output:
  sync_response: {}
```

Respective request to the http processor (notice the unwanted Http_server_* headers):

```
POST / HTTP/1.1
Host: mockaco:5000
User-Agent: curl/7.68.0
Content-Length: 20
Accept: */*
Content-Type: application/octet-stream
Http_server_remote_ip: 172.18.0.1
Http_server_request_path: /post
Http_server_user_agent: curl/7.68.0
Http_server_verb: POST
X-My-Header: awesome
Accept-Encoding: gzip

{"fieldB":"foo-bar"}HTTP/1.1 200 OK
Content-Type: application/json
Date: Tue, 30 Aug 2022 05:59:07 GMT
Server: Kestrel
Transfer-Encoding: chunked

{
  "response": "ok!"
}
```

**Comment by mihaitodor** [comment]
@natenho I'm not sure which `meta` variables you're referring to, but if it's the metadata that's coming from the `http_server` input, then you can add `meta = deleted()` either in your first `mapping` processor or under `input.processors` in a new `mapping` processor, so smth like this:

```yaml
input:
  http_server:
    path: /post
  processors:
    - mapping: meta = deleted()
```

**Comment by natenho** [comment]
@mihaitodor, thanks, but the problem is that I don't want to remove **all meta**, because there are headers coming from the input that I want to forward them to the http processor. Check the image below:

![image](https://user-images.githubusercontent.com/4236481/188024960-b4d6591e-3b41-488a-a2ed-7dc381097cf1.png)

I only want to send `X-My-Header` to the http processor.

So, it seems that the only way to achieve that is by filtering like this:

```
input:
  http_server:
    path: /post
  processors:
    - mapping: meta = meta().filter(!this.key.has_prefix("http_server_"))
```
But it looks like a hack to me. Is there a better way to forward *only* meta coming from the http_server request headers?
