### ISSUE TITLE
bloblang error logging inconsistencies

### ISSUE THREAD

**Issue by mannharleen** [benthosdev/benthos#1428]
Environment:
- benthos 4.3.0
- stream mode

## Inconsistencies with how bloblang errors are reported on the logs
Below test cases clearly illustrate how logging bloblang errors is inconsistent. 
This is a big hindrance in productionizing benthos ,so hopefully will be considered to be resolved soon.  

  - `{ bloblang: `root = count("b") + "A"` }` 
    - writes an ERROR log `{"label":"","level":"error","msg":"Failed to read message: failed assignment (line 1): cannot add types number (from function count) and string (from string literal)","path":"root.input","stream":"e01387fa-cf52-4ebc-804d-211aa3510982","time":"2022-09-02T12:04:31+10:00","error":{"message":"Failed to read message: failed assignment (line 1): cannot add types number (from function count) and string (from string literal)"}}`
    - message moves forward 
    - message contains the error property

  - `{ bloblang: 'root = "a">1' }` 
    - writes an INFO level log `{"level":"info","msg":"Stream 'e83e436a-98fd-42c5-ad43-0a47b6b8acdc' config: line 1: line 1 char 8: cannot compare types string (from string literal) and number (from number literal)\n  |\n1 | root = \"a\">1\n  |        ^---","time":"2022-09-02T11:57:52+10:00"}`
    - message is dropped, i.e. doesnt move forward
    - message doesn't contains the error property, as it doesnt move forward

  - `{ bloblang: 'root = a>1' }` 
    - writes an ERRORlevel log `{"label":"","level":"error","msg":"failed assignment (line 1): cannot compare types null (from field `this.a`) and number (from number literal)","path":"root.pipeline.processors.0","stream":"f7dd8d62-db37-4967-99bf-39de89d7f209","time":"2022-09-02T12:17:53+10:00","error":{"message":"failed assignment (line 1): cannot compare types null (from field `this.a`) and number (from number literal)"}}`
    - message moves forward 
    - message contains the error property

  - `{ bloblang: 'root = this.doesntexit' }` 
    - **doesn't** write anything to the logs
    - message moves forward 
    - message doesn't contains the error property

  - `{ bloblang: 'root = throw("blablabla")' }` 
    - writes an ERROR level log `{"label":"","level":"error","msg":"failed assignment (line 1): blablabla","path":"root.pipeline.processors.0","stream":"60d16479-d079-4097-baf8-6e01510cdbae","time":"2022-09-02T12:02:11+10:00","error":{"message":"failed assignment (line 1): blablabla"}}`
    - message moves forward 
    - message contains the error property

## ASK
To provide consistent logging on bloblang errors.

## Reference config

This is the config I used for testing. I am making changes to the bloblang processor at `pipeline.processors[0]`

```yaml
---
input:
  label: ''
  broker:
    copies: 1
    inputs:
    - label: ''
      generate:
        mapping: root = count("gen")
        interval: 1s
        count: 2
pipeline:
  processors:
  - label: ''
    bloblang: root = throw("blablabla")
  - label: ''
    log:
      level: INFO
      fields_mapping: root = {}
      message: '${! "ERROR IS: " + error().string() }'
output:
  label: ''
  broker:
    copies: 1
    pattern: fan_out
    outputs:
    - stdout: {}
    batching:
      count: 0
      byte_size: 0
      period: ''
      check: ''
      processors: []

```
