### ISSUE TITLE
awk file operations

### ISSUE THREAD

**Issue by Counterflowwind** [benthosdev/benthos#1442]
I want to append content to specific file in awk processor. Just like this:
```yaml
processors:
    - awk:
        codec: "json"
        program: |
          {
            data_value = json_get("items.data")
            print data_value >> ./result.json   #It's wrong to write
          }
```
How should this be achieved?

**Comment by mihaitodor** [comment]
Hey @Counterflowwind, try the following config. I think you're missing the double quotes around the output file.

```yaml
input:
  generate:
    mapping: |
      root.items.data = {"foo": "bar"}
    interval: 0s
    count: 1

pipeline:
  processors:
    - awk:
        codec: "text"
        program: |
          {
            data_value = json_get("items.data")
            print data_value >> "./result.json"
          }
output:
  stdout: {}
```

**Comment by Counterflowwind** [comment]
@mihaitodor thanks for your reply. I still have some confuse about file operations in awk processor.
In awk processor can I delete a file or the contents of a file?
In awk processor can i append the content to the file to the same line, remove '\n'?
In awk processor can I read file content and assign it to a variable?
Can I skip this data stream processing in the processor when the conditions are met, and perform the next data stream processing?

**Comment by mihaitodor** [comment]
That's a lot of issues in one :)

> In awk processor can I delete a file or the contents of a file?

Yep! Try `>` instead of `>>`, namely `print data_value > "./result.json"`

> In awk processor can i append the content to the file to the same line, remove '\n'?

Yep! Use `printf` instead of `print`, namely: `printf data_value >> "./result.json"`

> In awk processor can I read file content and assign it to a variable?

Yep, but it sure is awkward (no pun intended 😅)

```yaml
input:
  generate:
    mapping: |
      root = {}
    interval: 0s
    count: 1

pipeline:
  processors:
    - awk:
        codec: "text"
        program: |
          function readfile(file, tmp, save_rs)
          {
              save_rs = RS
              RS = "^$"
              getline tmp < file
              close(file)
              RS = save_rs

              return tmp
          }
          BEGIN {print readfile("/Users/mihaitodor/Projects/jeffail/benthos/tmp/_result.json")}

output:
  stdout: {}
```

Inspired from here: https://www.gnu.org/software/gawk/manual/html_node/Readfile-Function.html

> Can I skip this data stream processing in the processor when the conditions are met, and perform the next data stream processing?

I'm not really sure what you mean... Are you looking to implement conditional operations inside the awk program? If yes, does this help? https://www.thegeekstuff.com/2010/02/awk-conditional-statements/

**Comment by Counterflowwind** [comment]
@mihaitodor Thank you very much for your reply. Your reply helped me solve my problem.My last question may be that I didn't make it clear. Just like bloblang's throw function.
```yaml
input:
  generate:
    mapping: |
      root = {"index":1,"total":2}
    interval: 0s
    count: 1
pipeline:
  processors:
    - try: 
      - bloblang: |
          if this.index < this.total {
            throw("index < total")
          }
      - awk:
          codec: "json"
          program: |
            {
              print "this is test"
            }
output:
  stdout: {}
```
If I want to exit the whole processors, I can throw an exception via throw . Are there any other implementations that can help quit the whole processors?

**Comment by mihaitodor** [comment]
@Counterflowwind I'm still not sure I get what you're looking to do... The `throw()` mechanism you used there is a good way to skip subsequent processors (until a `catch` processor is encountered which resets the `error()` on the current message). An alternative would be to set some metadata field instead of calling `throw()` and then read it in one of the `check`s of a [`switch()`](https://www.benthos.dev/docs/components/processors/switch) processor.

Are you looking to achieve something similar *inside* the `awk` processor?

**Comment by Counterflowwind** [comment]
@mihaitodor yes.I want to achieve something similar inside the awk processor. How to write in awk processor?

**Comment by mihaitodor** [comment]
@Counterflowwind I don't think awk supports throwing exceptions, but you can emulate that with conditional statements as described in [the link](https://www.thegeekstuff.com/2010/02/awk-conditional-statements/) I provided above.

Here's an example:

```yaml
input:
  generate:
    mapping: |
      root.foo = count("test")
    interval: 0s
    count: 2

pipeline:
  processors:
    - branch:
        processors:
          - awk:
              codec: "text"
              program: |
                {
                  foo = json_get("foo")
                  if (foo == 1 )
                    print foo + 1;
                  else
                    print foo - 1;
                }
        result_map: |
          root.bar = content().string()
    - log:
        message: ${! error() }

output:
  stdout: {}
```
