### ISSUE TITLE
TLS issue with google services

### ISSUE THREAD

**Issue by packman80** [benthosdev/benthos#1475]
I have that config:

```
input:
  generate:
    interval: '5s'
    mapping: 'root = {}'

pipeline:
  threads: 1
  processors:
    - http:
        url: "https://googleapis.com"
        verb: GET
        timeout: 5s
        retries: 1
    - bloblang: | 
        root = this
output:
  stdout: {} 

logger:
  level: all
  format: json
  add_timestamp: true
  static_fields:
    '@service': hive
```

If i try to execute this, i will recive error every 3-5 requests:

> "HTTP request to 'https://googleapis.com' failed: https://googleapis.com: stream error: stream ID 3; PROTOCOL_ERROR; received from peer"

---

Clear golang code **has no** this issue:

```
resp, err := http.Get("https://googleapis.com")
	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()

	fmt.Println("Response status:", resp.Status)

	scanner := bufio.NewScanner(resp.Body)
	for i := 0; scanner.Scan() && i < 5; i++ {
		fmt.Println(scanner.Text())
	}
	if err := scanner.Err(); err != nil {
		panic(err)
	}
```

**Comment by Jeffail** [comment]
Hey @packman80, because you're using `'root = {}'` as the generate input the body of the GET request won't be empty, it'll be the document serialized as JSON (`{}`). If you want an empty body replace it with `root = ""`.

**Comment by massyah** [comment]
For reference, encountered a similar error, 

Here’s a minimal workflow demonstrating the error :

```
input:
  stdin: {}

pipeline:
  threads: -1
  processors:
    - http:
        # url : https://maps.googleapis.com/maps/api/geocode/json?address=Test&key=REDACTED_KEY
        # url : https://maps.googleapis.com/maps/api/geocode/json?address=${! content().escape_url_query() }&key=REDACTED_KEY
        # url : https://httpbin.org/get?address=foo&address=foo&address=foo
        url : https://httpbin.org/get?address=${! content().escape_url_query() }&key=FAKE_KEY        
        verb: GET
        retries: 0

output:
  stdout:
    codec: lines
```

* when the http sends a request to googleapis AND that the stdin message is not empty, I get the following errors :
```
ERRO HTTP request to 'https://maps.googleapis.com/maps/api/geocode/json?address=foo' failed: https://maps.googleapis.com/maps/api/geocode/json?address=foo: Get "https://maps.googleapis.com/maps/api/geocode/json?address=foo": stream error: stream ID 1; INTERNAL_ERROR; received from peer  @service=redpanda-connect label="" path=root.pipeline.processors.0
ERRO HTTP request to 'https://maps.googleapis.com/maps/api/geocode/json?address=foo' failed: https://maps.googleapis.com/maps/api/geocode/json?address=foo: stream error: stream ID 3; PROTOCOL_ERROR; received from peer  @service=redpanda-connect label="" path=root.pipeline.processors.0
```
* when the http sends a request to googleapis AND that the stdin message is empty, I get a normal error (bad request from googleapis, which is expexted as the API key is not recognized or I’m missing the address)
* when the http sends a request to httpin, it always work, regardless of the stdin message and if I pass query parameters
I’ve only encountered this calling googleapis.

The issue originates from the http GET sending the message content in the body (not accepted by googleapis). 

The workaround I found is to store the content in a meta variable before clearing the root document : 
```
    - mapping: |
        meta address = content()
        root = ""
[...]
    url : https://maps.googleapis.com/maps/api/geocode/json?address=${! meta("address").escape_url_query() }&key=REDACTED
```
