### ISSUE TITLE
Set custom labels for built in metrics dynamically during pipeline execution 

### ISSUE THREAD

**Issue by tragiclifestories** [benthosdev/benthos#1490]
Just a little feature request - it would be nice to have a processor available that could add extra labels to built in metrics. You would define something like:

```yaml
processors:
  - metric_label:
      key: 'my_thing'
      value: ${! meta("my_thing") }
```

And then all timeseries emitted in a subsequent step in pipeline execution would have `{my_thing="somevalue"}` added in there.

## Motivation

This comes from a particular use case I have, where we output to PubSub, but which topic depends on specific things about the input. The PubSub topics all have schema validations, and in any case distributed systems are hard:tm:, so that final call may or may not succeed. As a result, I want to know two things:

1. Are messages of a given type/output topic making it to the 'happy path' output branch?
2. If they are, are they publishing successfully?

I can get 1. by adding a processor to the output with a custom metric, but not 2 (or not easily, anyway). Whereas, if I could have

```yaml
processors:
  - metric_label:
      key: 'pubsub_topic'
      value: ${! meta("pubsub_topic") }
```

then the labels would appear in the standard `output_sent`/`output_error` timeseries and I would be able to answer both with a little PromQL prestidigitation. 

Not sure how feasible this is but thought it would be a nice enhancement to the o11y features in Benthos!
