### ISSUE TITLE
Multi SQL insert 

### ISSUE THREAD

**Issue by zwolsman** [benthosdev/benthos#1495]
Right now the [SQL insert](https://www.benthos.dev/docs/components/outputs/sql_insert) output only supports 1 item. I would like to have an option that will accept an array of items from the `args_mapping` that can than be expanded in the following manner.

```sql
INSERT INTO table(a, b, c) VALUES (j, k, l), (x, y, z);
```

This way it will be done in 1 statement instead of multiple INSERTS.

**Comment by mihaitodor** [comment]
It does support [batching](https://www.benthos.dev/docs/components/outputs/sql_insert/#batching), though. See the code [here](https://github.com/benthosdev/benthos/blob/be16b6572e3c3838d4702f861534dade0435ba0a/internal/impl/sql/output_sql_insert.go#L235-L267). So if you send a batch of messages to this output, it should run a single `INSERT` statement. Please let me know if you need more details.

**Comment by zwolsman** [comment]
Yeah batching is an option but it doesn't come with guarantees I would like to have.

We have a message coming in from pubsub with an order & order items embedded in it. We would like to have the guarantee that all order items are inserted before acking and thus having a single `INSERT` with multiple `VALUES` would help here.

With the batching it could be split between multiple batches and that is not what we want.

**Comment by mihaitodor** [comment]
OK, I think I follow. I'll mark it as an enhancement request.

As a workaround, would the `sql_raw` output help you? You can set `unsafe_dynamic_query` to `true` which will allow you to construct the `query` dynamically using [interpolation functions](https://www.benthos.dev/docs/configuration/interpolation/#bloblang-queries) if that's needed.

**Comment by intech** [comment]
@mihaitodor Could you leave an example of such an implementation here?

**Comment by mihaitodor** [comment]
Sure! I guess you can start with something like this:

```yaml
input:
  generate:
    mapping: |
      root.type = if count("type") % 3 == 1 { "order" } else { "item" }
      root.id = uuid_v4()
    count: 9
    interval: 0s
    batch_size: 3
  processors:
    - archive:
        format: json_array
    - mapping: |
        root.order = this.filter(item -> item.type == "order").index(0)
        root.items = this.filter(item -> item.type == "item")

output:
  sql_raw:
    driver: sqlite
    dsn: file:./foobar.db
    query: |
      BEGIN TRANSACTION;
      INSERT INTO orders (id) VALUES (?);
      INSERT INTO order_items (id, order_id) VALUES ${! json("items").map_each(i -> "(?, ?)").join(",") };
      COMMIT;
    unsafe_dynamic_query: true
    args_mapping: |
      root = [ this.order.id ].append(this.items.map_each(i -> [this.order.id, i.id]).flatten()).flatten()
    conn_max_idle: 1
    conn_max_open: 1
    init_statement: |
      CREATE TABLE IF NOT EXISTS orders (
        id varchar
      );
      CREATE TABLE IF NOT EXISTS order_items (
        id varchar,
        order_id varchar
      );
```

I'm making some possibly undesired assumptions in there:
- Each batch contains exactly one order and multiple items which have to be inserted in one single transaction
- An order is inserted together with its items in a single transaction
- There's just a single column in each of the two tables called `id`, but you can change that by adjusting the `query` and `args_mapping` fields
