### ISSUE TITLE
The output `gcp_cloud_storage` doesn't handles errors

### ISSUE THREAD

**Issue by andynog** [benthosdev/benthos#1525]
I'm trying to upload a file to Google Cloud Plataform (GCP) storage and it is not working.

I'm sure the `file.json` is generated because if I use file output it saves it locally. 

In my pipeline.yaml I have:
```
output:
  gcp_cloud_storage:
    bucket: "my_unique_bucket_data"
    path: file.json
    content_type: application/octet-stream
    collision_mode: overwrite
    max_in_flight: 64
    batching:
      count: 0
      byte_size: 0
      period: ""
      check: ""
```

I think I properly set up the authentication but the file is not showing up on gcp storage. 

If I run benthos with `log.level=trace` I see these message that says it was successful but didn't work

```
TRAC Attempting to write 1 messages to 'gcp_cloud_storage'.  @service=benthos label="" path=root.output
TRAC Successfully wrote 1 messages to 'gcp_cloud_storage'.  @service=benthos label="" path=root.output
```

As a test I've changed the bucket to an invalid bucket name (doesn't exist) and I get the same successful message as above.
