### ISSUE TITLE
Failed to decompress compressed json file with arrays

### ISSUE THREAD

**Issue by AzlinII** [benthosdev/benthos#1527]
I don't know if this is a bug or just me creating the config incorrectly. I found that when I used the `decompress` processor like so, 
```
input:
  file:
    paths: ["./tests/resources/testing.gz"]
    codec: lines
pipeline:
  processors:
    - label: unzip_file
      decompress:
        algorithm: "gzip"
```
It failed to decompress gzip json files that have arrays in them. For example:
```
{"id": "12345", "item": ["1234"]}
```
It gives me the following error message 
```
ERRO Failed to decompress message part: gzip: invalid header  @service=benthos label=unzip_file path=root.pipeline.processors.0
ERRO Failed to decompress message part: unexpected EOF  @service=benthos label=unzip_file path=root.pipeline.processors.0
path=root.pipeline.processors.0
```
I have tried all of the decompression algorithm and none of them work. 

When I remove the array in the json (example below) and gzip it back up, I doesn't give that error anymore.
```
{"id": "12345", "item": "1234"}
```

I'm using Benthos version 
```
Version: 4.9.1
Date: 2022-10-06T16:19:29Z
```
