### ISSUE TITLE
Redis Stream delete entries 

### ISSUE THREAD

**Issue by rangesh-gupta** [benthosdev/benthos#1533]
Current benthos Redis stream input plugin, read the messages and acknowledges back to Redis stream. 

Redis stream doesn't delete the message and it stays in the Redis memory indefinitely until explicitly asked to delete it. Check the below link for it.  https://redis.io/docs/data-types/streams-tutorial/#listening-for-new-items-with-xread

For deleting we have to send XDEL <key> <id> command to Redis stream. [https://redis.io/commands/xdel/](url)

Can we add new behavior to Redis stream input plug to perform XDEL after reading the messages? We can control the behavior by introducing a new input parameter to Redis stream input plug to perform XDEL or not?

**Below is the sample benthos config file:**
```

input:
  broker:
    copies: 1
    inputs:
        - redis_streams:
            url: "redis://localhost:6379"
            streams: ["key"]
            body_key: "body"
            limit: 1
            client_id: "c2"
output:
  label: ""
  file:
    path: 'result/data.log'
    codec: lines

```
