### ISSUE TITLE
output file name same as input file

### ISSUE THREAD

**Issue by dhaldergit** [benthosdev/benthos#1536]
Please suggest me how to create/rename output file name same as input file name.

**Comment by mihaitodor** [comment]
Hey @dhaldergit, try this:

```yaml
input:
  file:
    paths:
      - ./test.txt

output:
  file:
    path: ${! meta("path").filepath_split().index(-1) }
```
