### ISSUE TITLE
`benthos test` erroneously fails tests with non-string metadata values

### ISSUE THREAD

**Issue by andimiller** [benthosdev/benthos#1554]
When running a test with complex metadata values, the linter will say something like:
```
Lint: (11,1) expected string value
Lint: (14,1) expected string value
```
and cause the test to fail, unless you add `# BENTHOS LINT DISABLE` to the start of the file.

For a full example, try running this with `benthos test` with and without the line 0 comment:
```yaml
# BENTHOS LINT DISABLE
pipeline:
  processors:
    - label: hello_detector
      bloblang: root.foo = meta("foo").contains("hello")
tests:
  - name: example test
    target_processors: 'hello_detector'
    input_batch:
      - content: ''
        metadata:
          foo: ["hello", "world"]
      - content: ''
        metadata:
          foo: []
    output_batches:
    -
      - json_equals: { "foo": true }
      - json_equals: { "foo": false }
```

**Comment by Jeffail** [comment]
Should be fixed with: https://github.com/benthosdev/benthos/commit/cb8007aa1740d53f47a37650b7b420223b3ecd7f

I'm also getting some feedback on the new metadata access in bloblang: https://github.com/benthosdev/benthos/issues/1558

**Comment by sasanrose** [comment]
I'm getting the same error with `json_contains` and I'm on latest release (v4.11.0). Here are two samples that fail with the same error if `# BENTHOS LINT DISABLE` is removed:

```yaml
# BENTHOS LINT DISABLE
processor_resources:
  - label: nel_drop
    mapping: |
      root = if this.resource."service.name" == "nel-reports" { deleted() }

tests:
  - name: nel drop test
    target_processors: 'nel_drop'
    input_batch:
      - file_content: ./test_data/nel_drop_input.log
    output_batches:
      -
        - json_contains: { "resource": { "cloud.platform": "aws_eks", "host.id": "i-GB11CLEZ09534466896610" } }
```

```yaml
# BENTHOS LINT DISABLE
processor_resources:
  - label: kpl_deaggregator
    kpl:

tests:
  - name: kpl deaggregator
    target_processors: 'kpl_deaggregator'
    input_batch:
      - file_content: ./test_data/kpl_deaggregate_input.log
    output_batches:
      -
        - json_contains: { "resource": { "host.id": "i-GB98GKHE62443539461912" } }
        - json_contains: { "resource": { "host.id": "i-GB72OBQH42215361736950" } }
        - json_contains: { "resource": { "host.id": "i-GB83YWID98872826021272" } }
        - json_contains: { "resource": { "host.id": "i-GB25CLLB92662630245036" } }
        - json_contains: { "resource": { "host.id": "i-GB17OSSA22658722758649" } }
```

Should I create a new issue for this?
