### ISSUE TITLE
help with regex quoting/escaping 

### ISSUE THREAD

**Issue by fundef1** [benthosdev/benthos#1592]
Hi, 
I'm pretty new to Benthos so if this is answered/explained elsewhere please point me in the right direction and I'll be on my merry way.

I'm trying to construct a switch with a re_match.
my regex is ``` ^AB\d{10} ``` i.e. starts with a capital A, capital B followed by 10 digits

corresponding snippet of my config.yaml
```
    - label: "parse_memo"
      switch: 
        - check: this.memo.re_match("^AB\d{10}")
          processors:
            - label: "do_something"
```
however I'm getting the following linter error
```
ERRO Config lint error                             @service=benthos lint="config.yaml(74,38) line 1 char 20: failed to unescape quoted string contents: invalid syntax\n  |\n1 | this.memo.re_match(\"^AB\\d{10}\")\n
```

I'm guessing it trips on the \ but I'm not clear on how to escape it properly in yaml. 
any help much appreciated.
