### ISSUE TITLE
Sort Output

### ISSUE THREAD

**Issue by Varkal** [benthosdev/benthos#1600]
Hello, 

I have a CSV file.

I try to process each line to add a new field, then, i want to output the line sorted in a new csv file. 
I don't understand how can i sort my output 

For example, with this input csv: 

```csv
first_name;last_name
Bruce;Banner
Tony;Stark
Bruce;Wayne
Barry;Allen
Jason;Todd
Dick;Grayson
```
I want to output this csv : 

```csv
first_name;last_name;full_name
Barry;Allen;Bruce Wayne
Bruce;Banner;Dick Grayson
Bruce;Wayne;Barry Allen
Dick;Grayson;Bruce Banner
Jason;Todd;Tony Stark
Tony;Stark;Jason Todd
```

Currently, i have this config

```yaml
input:
  csv:
    paths: [./benthos.csv]
    delimiter: ";"
    parse_header_row: true

pipeline:
  processors:
    - bloblang: |
        root = this
        root.full_name = this.first_name + " " + this.last_name      
        
output:
  file:
    path: ./benthos_output.csv
```    

But don't understand how i can sort the full batch of line, and not something inside each line

**Comment by mihaitodor** [comment]
Hey @Varkal, Benthos is a data streaming processor, meaning that it's not really intended for use cases where the entire input data needs to end up in a certain order. Having said that, there are workarounds with various caveats, such as this one:

```yaml
input:
  csv:
    paths: [./benthos.csv]
    delimiter: ";"
    parse_header_row: true

buffer:
  memory:
    limit: 1048576 # 100MB - Something larger than the total size of your input data
    batch_policy:
      enabled: true
      count: 1000000 # 1 million - Something larger than the total number of rows you can possibly have in your input

pipeline:
  processors:
    - archive:
        format: json_array
    - mapping: |
        map escape_csv {
          root = if this.re_match("[\"\n,]+") {
            "\"" + this.replace_all("\"", "\"\"") + "\""
          } else {
            this
          }
        }

        let rows = this.sort_by(i -> i.first_name).map_each(i -> i.merge({"full_name": i.first_name + " " + i.last_name}))
        let cols = $rows.index(0).keys().sort() # Sort here to ensure the order of the columns in the output is deterministic
        let header = $cols.map_each(kv -> kv.apply("escape_csv")).join(",") + "\n"

        root = $header + $rows.map_each(row -> $cols.map_each(c -> row.get(c).string().apply("escape_csv")).join(",")).join("\n")

output:
  file:
    path: ./benthos_output.csv
```

Caveats:
- We must force Benthos to read all the input data in memory. Since you need a custom delimiter, we can't just use the `file` input with `codec: all-bytes` because the [`unarchive` processor](https://www.benthos.dev/docs/components/processors/unarchive) doesn't support custom delimiters when specifying `format: csv` and the [`parse_csv` bloblang method](https://www.benthos.dev/docs/guides/bloblang/methods#parse_csv) has the same limitation right now, but I'll send a PR soon to extend the latter. Until then, using a large enough in-memory buffer will do the trick. Alternatively, parsing the CSV manually using various string functions in bloblang is possible, but I'd rather not go down that route... If needed, you could write your own [custom plugin](https://github.com/benthosdev/benthos-plugin-example).
- The in-memory buffer batches all the rows (messages) into a batch which we need to collapse into a single message using the `archive` processor, so we can then use the [`sort_by` bloblang method](https://www.benthos.dev/docs/guides/bloblang/methods#sort_by).
- Since JSON objects don't have any column order, then we must manually sort the columns too if we want the final output CSV to be deterministic. Currently, the `csv` input doesn't store the original column order anywhere, so that information is lost. If it's mandatory to preserve the column order from the input, I have that code almost ready.
- There's no `format_csv` bloblang method / processor or `csv` output yet because it's a bit unclear how to make it generic, but, as explained [here](https://www.benthos.dev/docs/guides/bloblang/advanced#creating-csv) there are some workarounds. The mapping I created above is one way, but definitely not the most efficient possible.

Having said that, there are other tools out there which might be more suitable for achieving your goal, such as [xsv](https://github.com/BurntSushi/xsv), [miller](https://github.com/johnkerl/miller), [q](http://github.com/harelba/q), etc.
