### ISSUE TITLE
Output subprocess dynamic

### ISSUE THREAD

**Issue by malveslobo** [benthosdev/benthos#1601]
Hello all,
I try to use subprocess output but i don't know if it's the best way for implement my use case.

My config.yml

```
input:
  label: ""
  kafka:
    addresses: ["ip:29092"]
    topics: ["topic"]
    target_version: 2.0.0
    consumer_group: "group_name"
    checkpoint_limit: 1024
    
- mapping: |
        root.param1 = this.id

output:
  broker:
    outputs:
    - subprocess:
        name: "node"
        args: ["run"]
        codec: lines
```

I want to run dynamic command like 

`node run {"param1": "value1"}`

where the value of the hash key "param1" is the result of a mapping processor 'root.param1'
