### ISSUE TITLE
gcp_pubsub recource doesn't close gracefully

### ISSUE THREAD

**Issue by alex-user-go** [benthosdev/benthos#1620]
When running benthos with a [config](https://www.benthos.dev/docs/components/inputs/resource) from the site:
```
input:
  broker:
    inputs:
      - resource: bar

input_resources:
  - label: bar
    gcp_pubsub:
      project: project_name
      subscription: benthos-sub
```
it doesn't close gracefully (even thought there no messages on pubsub):
```
INFO Received SIGINT, the service is closing       @service=benthos
ERRO Encountered error whilst shutting down: context deadline exceeded  @service=benthos
```
But when using gcp_pubsub directly everything is fine:
 ```
input:
  broker:
    inputs:
      -  gcp_pubsub:
          project: project_name
          subscription: benthos-sub
```
