### ISSUE TITLE
Failed to align branch result

### ISSUE THREAD

**Issue by alexesDev** [benthosdev/benthos#1623]
I'm trying to create a pipeline and it's a minimal example:
```yaml
input:
  # generate 1+ static messages
  generate:
    interval: ""
    count: 1
    mapping: |
      root = [{ "base_url": "a" }, { "base_url": "b" }]

pipeline:
  processors:
    - unarchive:
        format: json_array

    - branch:
        # generate variadic "urls"
        request_map: root = [2, 3].map_each(p -> "%s?page=%d".format(this.base_url, p))

        processors:
          - unarchive:
              format: json_array

          # load data by url from message
          - mapping: |
              root = { "url": this }

          - archive:
              format: json_array

        result_map: root.items = this

    - archive:
        format: json_array

output:
  stdout: {}
```

And got an unexpected `unarchive + branch` error:
```
ERRO Failed to align branch result: message count from branch processors does not match request, started with 1 messages, finished with 2. Avoid using filters or archive/unarchive processors within your branch, or anything that increases or reduces the number of messages. These processors should instead be applied before or after the branch processor.  @service=benthos label="" path=root.pipeline.processors.0
```

What am I doing wrong? I can remove `unarchive` or `branch` and it works. But together it produce the error.

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/1255344/207671402-1ab09ae6-b46f-4056-8018-954f2d34a7de.png">

**Comment by Jeffail** [comment]
Hey @alexesDev this is a good question as it's a challenging topic to document, I believe what you need is this:

```yaml
input:
  # generate 1+ static messages
  generate:
    interval: ""
    count: 1
    mapping: |
      root = [{ "base_url": "a" }, { "base_url": "b" }]

pipeline:
  processors:
    - unarchive:
        format: json_array

    - for_each:
      - branch:
          # generate variadic "urls"
          request_map: root = [2, 3].map_each(p -> "%s?page=%d".format(this.base_url, p))

          processors:
            - unarchive:
                format: json_array

            # load data by url from message
            - mapping: |
                root = { "url": this }

            - archive:
                format: json_array

          result_map: root.items = this

    - archive:
        format: json_array

output:
  stdout: {}
```

The issue is that your data starts off as a batch of size two (after the first unarchive), and then within the branch it's expanded into a batch of 4 with the next unarchive, and then the final archive merges it back into a single batch of 1 message. This is an invalid action within a branch as it makes it impossible to relate the messages back into the original at the result mapping stage.

In the answer above I've placed the entirety of the branch into a `for_each` with means each of the original 2 messages will instead be processed in isolation.
