### ISSUE TITLE
read_until doesn't work with gcp_cloud_storage

### ISSUE THREAD

**Issue by alex-user-go** [benthosdev/benthos#1624]
Hello!
When I try this config it works:
```
input:
  read_until:
    check: meta("filename") == "222"
    input:
        generate:
           count: 1
        processors:
        - sleep:
           duration: "2s"
    restart_input: true
```
But if I use gcp_cloud_storage it doesn't consume files from the bucket
```
input:
  read_until:
    check: meta("filename") == "222"
    input:
        gcp_cloud_storage:
            bucket: "benthos-bucket"
            codec: gzip/csv
            delete_objects: true
        processors:
        - sleep:
           duration: "2s"
    restart_input: true
```
