### ISSUE TITLE
Cached Question with Custom Batch Processor

### ISSUE THREAD

**Issue by praetorian-thendrickson** [benthosdev/benthos#1625]
I am trying to use a cached resource with a custom processing heavy Batch Processor (https://pkg.go.dev/github.com/benthosdev/benthos/v4@v4.10.0/public/service#BatchProcessor). The Batch processor can return multiple output events for each input event. Attempting to use a branch processor and a request mapping gives this error: `Failed to align branch result: message count from branch processors does not match request, started with 3 messages, finished with 1. Avoid using filters or archive/unarchive processors within your branch, or anything that increases or reduces the number of messages. These processors should instead be applied before or after the branch processor.` which seems to be due to the fact that 3 messages are cached for the key. The following benthos config behavior is what I'm looking to do, but when I use the custom batch processor during the `cached` step  any metadata set in previous steps gets blown away. Is there a different way to keep a meta value set during a one to many processor mapping? 

```yaml
cache_resources:
  - label: memcache
    memory:
      default_ttl: 60m
      compaction_interval: 5m
      init_values: {}
input:
  stdin:
    codec: lines
pipeline:
  threads: 1
  processors:
    - bloblang: |
        meta precached = this.header.id
    - cached:
        key: ${! this.payload.name }
        cache: memcache
        processors:
          - custom_batch_processor: {}
    - bloblang: |
        root = this
        root.header.id = meta().precached
output:
  stdout:
    codec: lines
```

**Comment by praetorian-thendrickson** [comment]
It looks like this can work around it, but it feels a little silly:
```yaml
pipeline:
  threads: 1
  processors:
    - bloblang: |
       meta precached = this.header.id
    - cached:
        key: ${! this.payload.name }
        cache: memcache
        processors:
          - custom_batch_processor: {}
          - archive:
              format: json_array
    - unarchive:
        format: json_array
    - bloblang: |
        root = this
        root.header.id = if meta().precached != null {
          meta().precached
        }
```
