### ISSUE TITLE
gcp_cloud_storage metadata

### ISSUE THREAD

**Issue by alex-user-go** [benthosdev/benthos#1635]
Hello!
Is there a way to add a new custom metadata field to the gcp_cloud_storage output file?

**Comment by Jeffail** [comment]
Hey @alex-user-go you can use metadata assignments to add headers to data, using the mapping processor it'd look something like this:
```yaml
output:
  gcp_cloud_storage:
    bucket: TODO
    path: ${!count("files")}-${!timestamp_unix_nano()}.tar.gz
  processors:
    - mapping: 'meta foo = "hello world"'
```

**Comment by alex-user-go** [comment]
Thanks @Jeffail!
But it doesn't seem to work in 'append' mode:
```
output:
  gcp_cloud_storage:
    bucket: TODO
    collision_mode: append
    path: fixedFileName.ndjson
  processors:
    - mapping: 'meta foo = "hello world"'
```
