### ISSUE TITLE
AWS S3 Input error - bufio.Scanner: token too long

### ISSUE THREAD

**Issue by reflection** [benthosdev/benthos#1636]
We are rarely seeing these errors in logs:
```
level=error msg="Failed to read message: bufio.Scanner: token too long" @service=benthos label=<redacted> path=root.input
level=debug msg="Pushing SQS notification back into the queue due to error: bufio.Scanner: token too long" @service=benthos label=<redacted> path=root.input
```
Is this because the json log line is too long?

Input config:
```
input:
    label: <redacted>
    aws_s3:
      bucket: <redacted>
      region: us-east-1
      delete_objects: false
      codec: lines
      sqs:
        url: <redacted>
```
