### ISSUE TITLE
MongoDB polling query

### ISSUE THREAD

**Issue by webfrank** [benthosdev/benthos#1646]
Hi,
  I would like to receive a suggestion on how to poll a MongoDB collection every x.

I was trying code like this:

```
input:
  read_until:
    check: false
    restart_input: true
    input:
      mongodb:
        url: ${MONGODB_URL:mongodb://127.0.0.1:27017/db}
        database: ${MONGODB_DB:db}
        operation: find
        collection: configs
        query: |
          root = {
            "devices": {"$exists": 1}
          }
```

but the query is executed continuously. What I would like to achieve is to query MongoDB every x time, for example, using a generate as input and mongoldb processor but cannot use "find" in processor.

Any idea?

**Comment by webfrank** [comment]
This is the last working workaround:

```
input:
  read_until:
    check: false
    restart_input: true
    input:
      batched:
        child:
          mongodb:
            url: ${MONGODB_URL:mongodb://127.0.0.1:27017/db}
            database: ${MONGODB_DB:db}
            operation: find
            collection: configs
            query: |
              root = {
                "devices": {"$exists": 1}
              }
        policy:
          period: 30s
```

**Comment by mihaitodor** [comment]
Hey @webfrank! Unless you're fetching a lot of data from MongoDB, you can leverage the [`generate` input](https://www.benthos.dev/docs/components/inputs/generate) and the [`mongodb` processor](https://www.benthos.dev/docs/components/processors/mongodb) as an alternative. However, if your query is returning many rows, then you'll likely want to use the [`mongodb` input](https://www.benthos.dev/docs/components/inputs/mongodb), since it uses a cursor under the hood to stream the selected rows. In this case, you can combine the [`read_until`](https://www.benthos.dev/docs/components/inputs/read_until), [`sequence`](https://www.benthos.dev/docs/components/inputs/sequence) and [`generate`](https://www.benthos.dev/docs/components/inputs/generate) utility inputs to achieve your goal:

```yaml
input:
  read_until:
    restart_input: true
    check: false
    input:
      sequence:
        inputs:
          - mongodb:
              url: ${MONGODB_URL:mongodb://127.0.0.1:27017/db}
              database: ${MONGODB_DB:db}
              operation: find
              collection: configs
              query: |
                root = {
                  "devices": {"$exists": 1}
                }
          - generate:
              count: 1
              # Note: Using a cron expression is important to avoid generating
              # the first message immediately. If that's an issue, we can also
              # set `count` to 2
              interval: "@every 30s"
              mapping: root = ""
            processors:
              # Get rid of the message produced by the `generate` input
              - mapping: root = deleted()
```
