### ISSUE TITLE
Block shutdown if processors are still doing work

### ISSUE THREAD

**Issue by mihaitodor** [benthosdev/benthos#1655]
Try running this config:

```yaml
input:
  read_until:
    input:
      generate:
        mapping: root = ""
        count: 0
        interval: 0s

    check: count("generate") > 1
    restart_input: false
  processors:
    - mapping: root = if count("read_until") > 1 { deleted() }

pipeline:
  threads: 2
  processors:
    - sleep:
        duration: 3s

    - sql_raw:
        driver: sqlite
        dsn: file::memory:?cache=shared
        query: SELECT 1;

    - catch:
        - log:
            message: |
              Error selecting data: ${! error() }
        - mapping: root = deleted()

output:
  stdout: {}
```
If you set `threads: 1`, it should work as expected and output `[{"1":1}]`. However, when `threads: 2`, it errors out with `Error selecting data: sql: database is closed`.

Workaround: Moving the `sql_raw` processor under `processor_resources` seems to prevent the eager shutdown.
