### ISSUE TITLE
wrong argument type: included map fails while inlining mapping works

### ISSUE THREAD

**Issue by fundef1** [benthosdev/benthos#1656]
Hi, 
I've observed a difference in behaviour between included mappings and inlined ones.
test case is a bit convoluted (cfr previous PR) , hopefully the gist is still clear.

```curl -X POST --data-binary @./test3.csv http://127.0.0.1:4195/benthos/post``` 

test3.csv
```
"numtest";"1,23"
"numtestneg";"-3,21"
```
config.yaml
```
input:
  label: "http_post"
  http_server:
    address: ""
    path: /post
    allowed_verbs:
      - POST
buffer:
  none: {}
pipeline:
  threads: 1
  processors:
    # - resource: "latin1_to_utf8"
    - resource: "split_by_linefeed"
    - resource: "parse_csv_lines"
    - resource: "numtest_inline"
    - resource: "numtest_include"
output:
  label: "to_stdout"
  stdout:
    codec: lines
```
resources.yaml
```
  - label: "parse_csv_lines"
    mutation: |
      let t = content().string().parse_csv(parse_header_row:false,delimiter:";",lazy_quotes:false) 
      let tmp = $t.string().parse_json() #PR1654
      root.err = error() | deleted()
      root.line = $tmp.index(0)
  - label: "numtest_inline"
    mutation: |
      let tmp = this.line
      root.test_inline = $tmp.index(0) #numtest
      root.num_inline = $tmp.index(1).replace_all_many([
        " ","",   
        ".", "",  
        ",", "."  
      ]).number()
  - label: "numtest_include"
    mutation: |
      import "./maps/db.yaml" 
      let tmp = this.line
      root.test_include = $tmp.index(0) #numtest
      root.num_include = $tmp.index(1).apply(numconv) #fails
```
maps/db.yaml
```
# poor man's locale conversion to POSIX(?) 1.234,56 -> 1234.56
map "numconv" {
  root = this.replace_all_many([
    " ","",   #remove whitespace
    ".", "",  #LC_NUMERIC locale thousands_sep 
    ",", "."  ##LC_NUMERIC locale decimal_point to POSIX decimal_point 
  ]).number()
```
benthos -r ./resources/resources.yaml -c config.yaml
```
ERRO failed assignment (line 4): failed to extract input arg mapping: wrong argument type, expected string, got null  @service=benthos label=numtest_include path=root.processor_resources
ERRO failed assignment (line 4): failed to extract input arg mapping: wrong argument type, expected string, got null  @service=benthos label=numtest_include path=root.processor_resources
{"line":["numtest","1,23"],"num_inline":1.23,"test_include":"numtest","test_inline":"numtest"}
{"line":["numtestneg","-3,21"],"num_inline":-3.21,"test_include":"numtestneg","test_inline":"numtestneg"}
```

the included mapping from maps/db.yaml via .apply(numconv) fails... eventhough the type is string.
