### ISSUE TITLE
invalid header field value for \"X-Amz-Meta-Kafka_key\"

### ISSUE THREAD

**Issue by MarcinGinszt** [benthosdev/benthos#1666]
Hello! 
I'm afraid the thing I'm reporting is not a bug per se, but I find it exceptionally difficult to figure out the reason for the error. 
I'm using pretty standard configuration to consume messages from Kafka (attached below), but I'm getting rather cryptic error 
```
Failed to send message to aws_s3: RequestError: send request failed
caused by: Put \"<HTTP S3 URL>\": net/http: invalid header field value for \"X-Amz-Meta-Kafka_key\"
```
I'm using `jeffail/benthos:4.9.1`. 

Can it be caused by unprocessable keys for key/value pairs in Kafka? 

```
    input:
      kafka:
        addresses:
          - ${KAFKA_ADDRESSES}
        client_id: ${CLIENT_ID}
        commit_period: 3s
        consumer_group: ${CONSUMER_GROUP}
        group:
          heartbeat_interval: 3s
          rebalance_timeout: 60s
          session_timeout: 10s
        checkpoint_limit: 1
        batching:
          count: 1024
          period: 1s
        max_processing_period: 2s
        start_from_oldest: true
        target_version: 3.2.0
        topics:
          - ${INPUT_TOPIC}

    pipeline:
      processors:
        - group_by_value:
            value: ${! meta("kafka_partition") }
        - archive:
            format: binary

    output:
      aws_s3:
        bucket: ${S3_BUCKET}
        content_encoding: ""
        content_type: application/octet-stream
        credentials:
          id: ${AWS_ACCESS_KEY_ID}
          profile: ""
          role: ""
          role_external_id: ""
          secret: ${AWS_SECRET_ACCESS_KEY}
          token: ""
        endpoint: ""
        force_path_style_urls: false
        path: ${S3_PATH}
        region: ${AWS_REGION}
        timeout: 5s
```
