### ISSUE TITLE
Prometheus metrics don't show real state of input/output

### ISSUE THREAD

**Issue by miguescri** [benthosdev/benthos#1667]
I am running the `jeffail/benthos:4.11` image (previously also tried 4.9) in streams mode in a Kubernetes deployment, and scrapping the `/metrics` endpoint from a Prometheus instance.

When I use a correct configuration and process events I see the expected metrics. However, when I purposely use a wrong configuration, the `input_connection_up`, `input_connection_failed`, `input_connection_lost` and their output counterparts do not reflect the failures.

YAML configuration (there is a second stream pipeline that is exactly the same but with a "2" suffix instead of "1" in the URLs):

```yaml
input:
    aws_sqs:
        credentials:
            id: AK-12345
            secret: qwerty
        endpoint: http://example-sqs-endpoint.com
        max_number_of_messages: 10
        region: example-region
        url: https://example-queue-domain.com/queue-1
        wait_time_seconds: 20
output:
    http_client:
        max_in_flight: 1000
        timeout: 5s
        url: https://example-function-domain.com/func-1
        verb: POST
```

Benthos logs report the failures to connect to SQS:

```
{"@service":"benthos","level":"info","msg":"Running main config from file found in a default path","path":"/benthos.yaml"}
{"@service":"benthos","level":"info","msg":"Launching benthos in streams mode, use CTRL+C to close"}
{"@service":"benthos","label":"","level":"info","msg":"Sending messages via HTTP requests to: https://example-function-domain.com/func-2","path":"root.output","stream":"1"}
{"@service":"benthos","label":"","level":"info","msg":"Receiving Amazon SQS messages from URL: https://example-queue-domain.com/queue-1","path":"root.input","stream":"0"}
{"@service":"benthos","label":"","level":"info","msg":"Sending messages via HTTP requests to: https://example-function-domain.com/func-1","path":"root.output","stream":"0"}
{"@service":"benthos","label":"","level":"info","msg":"Receiving Amazon SQS messages from URL: https://example-queue-domain.com/queue-2","path":"root.input","stream":"1"}
{"@service":"benthos","level":"info","msg":"Listening for HTTP requests at: http://0.0.0.0:4195"}
{"@service":"benthos","label":"","level":"error","msg":"Failed to pull new SQS messages: RequestError: send request failed\ncaused by: Post \"http://example-sqs-endpoint.com/\": dial tcp: lookup example-sqs-endpoint.com on 10.96.0.10:53: no such host","path":"root.input","stream":"0"}
{"@service":"benthos","label":"","level":"error","msg":"Failed to pull new SQS messages: RequestError: send request failed\ncaused by: Post \"http://example-sqs-endpoint.com/\": dial tcp: lookup example-sqs-endpoint.com on 10.96.0.10:53: no such host","path":"root.input","stream":"1"}
{"@service":"benthos","label":"","level":"error","msg":"Failed to pull new SQS messages: RequestError: send request failed\ncaused by: Post \"http://example-sqs-endpoint.com/\": dial tcp: lookup example-sqs-endpoint.com on 10.96.0.10:53: no such host","path":"root.input","stream":"1"}
{"@service":"benthos","label":"","level":"error","msg":"Failed to pull new SQS messages: RequestError: send request failed\ncaused by: Post \"http://example-sqs-endpoint.com/\": dial tcp: lookup example-sqs-endpoint.com on 10.96.0.10:53: no such host","path":"root.input","stream":"0"}

...
```

But metrics report everything okey:

![image](https://user-images.githubusercontent.com/24360431/211590639-179506b5-e777-4391-8afe-3d3143bdec01.png)
![image](https://user-images.githubusercontent.com/24360431/211590786-34be4245-8ca6-4566-a42f-a989eea2d591.png)
![image](https://user-images.githubusercontent.com/24360431/211590904-e5e6cb67-8660-43d6-9c17-40f82ecb4f0c.png)
