### ISSUE TITLE
SQL output processor slow after upgrading to 4.10 from 3.65

### ISSUE THREAD

**Issue by florind** [benthosdev/benthos#1677]
I have a processing pipeline that takes a few Kafka topic inputs and upserts the records in a Postgres database. There is a `switch` output config that selects the output resource by the input topic. When using Benthos 3.65 this pipeline is very fast, it upserts more than one million Kafka records in the DB in a few minutes. After upgrading to Benthos 4.11 the processing became much slower and I also see errors after a few tens of thousands records are processed.

The input for Benthos 3.65 is configured like this:
```
resources:
  inputs:
    input-topics:
      kafka:
      ...
        topics: T1, T2
        checkpoint_limit: 1
        batching:
          count: 1500
          period: 100ms      

```

The output for Benthos 3.65 is configured using a `sql` configuration like this:

```
  outputs:
    output-table1:
      retry:
        max_retries: 2
        backoff:
          initial_interval: 500ms
          max_interval: 3s
        output:
          sql:
            max_in_flight: 1
            driver: postgres
            data_source_name: postgres://...
           query: INSERT INTO output_table1 (..) VALUES (..) ON CONFLICT(pk) DO UPDATE SET(..) = (..)
     output-table2:
```

After upgrading to Benthos 4.11 we had to change the output config since `sql` output config is not supported anymore:
```
  outputs:
    output-table1:
      retry:
        max_retries: 2
        backoff:
          initial_interval: 500ms
          max_interval: 3s
        output:
          sql_raw:
            max_in_flight: 1
            batching:
              count: 1500
              period: 1s
            driver: postgres
            dsn: postgres://...
            query: INSERT INTO output_table (..) VALUES (..) ON CONFLICT(pk) DO UPDATE SET(..) = (..)

    output-table2:
         ...
```
I've set `max_in_flight=1` to ensure the upserts are correctly ordered. I also tried using the `sql_insert` configuration but I don't know how to correctly configure an `ON CONFLICT.. DO UPDATE SET` with params and also I am seeing errors when multiple records with the same key are part of a batch (since it's not possible to have a batch insert in a DB tx for records having the same key).

What am I doing wrong? Is there a config option that could bring this config to the 3.65 performance level?
Thanks!
florin

**Comment by Jeffail** [comment]
Hey @florind

> and I also see errors after a few tens of thousands records are processed

What's the error message? And it looks as though you don't have an `args_mapping` specified, what's the full query you're executing?

There's a significant difference between the old `sql` output and the new `sql_raw` one which is that transactions or batched sends are no longer used due to the fact that queries themselves could be anything (even dynamic). Ideally you'll want to rework your query to use `sql_insert`, I believe that param placeholders should work the same in the `suffix` as they do in the `query` field.

We could potentially expand the implementation of `sql_raw` to support batched/transactional sends but the logic is a bit messy as there's lots of factors as to whether it's possible and/or beneficial depending on the configuration.

**Comment by florind** [comment]
Hi @Jeffail actually `args_mapping` is specified, I omitted it here to keep the code brief. The error is `kafka: client has run out of available brokers to talk to (Is your cluster reachable?)` followed by errors related to the json parser reporting nulls (there is one configured as the kafka records are json).
I actually tried `sql_insert` but there were two issues: first there is an `ON CONFLICT (pk1, pk2, pk3) DO UPDATE SET(arg1, arg2, arg3) = ($1, $2, $3)` clause that didn't seem to work then there is the issue of having multiple records with the same PK in the same batch that would require first a deduplication (by taking the most recent record and not the first) before the sql output which further complicates this configuration.

**Comment by Jeffail** [comment]
Okay I'm going to adapt this issue as an enhancement to `sql_raw`, I think it should be possible to match the old performance without restricting features.

**Comment by mihaitodor** [comment]
Dunno if this helps in any way, but there was a recent [discussion](https://discord.com/channels/746368194196799589/754099840354615296/1062438042574524426) on [Discord](https://www.benthos.dev/community/) regarding `checkpoint_limit: 1`. `1` used to be the default value [in v3](https://v3.benthos.dev/docs/components/inputs/kafka#checkpoint_limit), but in v4 [it's 1024](https://www.benthos.dev/docs/components/inputs/kafka#checkpoint_limit). You might want to try adjusting that.

**Comment by florind** [comment]
I did try that as well and didn't make a difference. The only config that made it faster was increasing `max_in_flight` but then the I don't know if the record order is preserved when performing parallel upserts.

**Comment by miklosbarabas** [comment]
I had a similar issue with the `sql_raw` output not batching inserts.
Im using benthos version 4.11.0 and the following config:

```
input:
  label: "pipeline_in"
  generate:
    mapping: root = {"name":hostname(),"id":uuid_v4(),"random_number":random_int()}
    interval: 100ms
    count: 5000
output:
  label: "pipeline_out"
  sql_raw:
    driver: mysql
    dsn: mysqldsnbla
    query: "INSERT INTO employee (id, name, random_number) VALUES (?, ?, ?)"
    unsafe_dynamic_query: true
    args_mapping: |
      root = [
        this.id,
        this.name,
        this.random_number,
      ]
    max_in_flight: 4
    batching:
      count: 10
      period: 2000ms
```

I could observe that the inserts are one by one per each message compared to using `sql_insert output` where there are multiple values used for one statement. I also am restricted to use `sql_raw output` because my query eventually need to use some advanced syntax.

Is there any way or some workaround in bloblang that could be used in the query so it'd start doing batching? Or batching is simply not supported by the `sql_raw output` component at this point?

**Comment by miklosbarabas** [comment]
hey @Jeffail! could you please advise on the above? is there any way to make a batched insert for `sql_raw output` working in the current version?

**Comment by mihaitodor** [comment]
This issue has been raised for a while and I thought I'd leave a bloblang-based workaround here with `unsafe_dynamic_query: true` until someone gets a chance to figure out a way to address it in the `sql_raw` processor and output code:

```yaml
input:
  generate:
    mapping: |
      root.id = counter()
      root.name = fake("name")
      root.email = fake("email")
    count: 10
    interval: 0s

output:
  sql_raw:
    driver: sqlite
    dsn: file:./test.db
    query: insert into test(id, name, email) values ${! json().map_each(i -> "(?, ?, ?)").join(",")};
    unsafe_dynamic_query: true
    args_mapping: |
      root = this.map_each(i -> [i.id, i.name, i.email]).flatten()
    init_statement: |
      create table test(
        id integer,
        name varchar(50),
        email varchar(50),
        primary key ("id")
      );
    batching:
      count: 10
      period: 2s
      processors:
        - archive:
            format: json_array
```
