### ISSUE TITLE
Test fails due to linting issues

### ISSUE THREAD

**Issue by sasanrose** [benthosdev/benthos#1694]
This seems related to https://github.com/benthosdev/benthos/issues/1554.
The only difference is I'm using `json_contains`
My following tests fail with `Lint: expected string value` errors if I remove the `# BENTHOS LINT DISABLE`

```yaml
# BENTHOS LINT DISABLE
processor_resources:
  - label: nel_drop
    mapping: |
      root = if this.resource."service.name" == "nel-reports" { deleted() }

tests:
  - name: nel drop test
    target_processors: 'nel_drop'
    input_batch:
      - file_content: ./test_data/nel_drop_input.log
    output_batches:
      -
        - json_contains: { "resource": { "cloud.platform": "aws_eks", "host.id": "i-GB11CLEZ09534466896610" } }
```

```yaml
# BENTHOS LINT DISABLE
processor_resources:
  - label: kpl_deaggregator
    kpl:

tests:
  - name: kpl deaggregator
    target_processors: 'kpl_deaggregator'
    input_batch:
      - file_content: ./test_data/kpl_deaggregate_input.log
    output_batches:
      -
        - json_contains: { "resource": { "host.id": "i-GB98GKHE62443539461912" } }
        - json_contains: { "resource": { "host.id": "i-GB72OBQH42215361736950" } }
        - json_contains: { "resource": { "host.id": "i-GB83YWID98872826021272" } }
        - json_contains: { "resource": { "host.id": "i-GB25CLLB92662630245036" } }
        - json_contains: { "resource": { "host.id": "i-GB17OSSA22658722758649" } }
```
