### ISSUE TITLE
How to log the request/response dump and request time in http components

### ISSUE THREAD

**Issue by natenho** [benthosdev/benthos#1716]
Hello! What is the simplest way to log the request time in http components?

I'd like a log similar to `{"timestamp":"2022-09-22T16:51:57.326Z", "request_dump":"POST /", "took_ms": 213}`

Regarding the request/response dump, I noticed https://github.com/benthosdev/benthos/pull/1633
It is great, but it would be even useful to have a meta with this information, so I can interpolate and control where it will be logged (in a log component).

**Comment by mihaitodor** [comment]
Hey @natenho that sounds like a handy enhancement.

In the mean time, would this help you?

```yaml
input:
  generate:
    count: 1
    interval: 0s
    mapping: root = ""
  processors:
    - mapping: |
        meta start = timestamp_unix_nano()
    - http:
        url: https://random-data-api.com/api/dessert/random_dessert
        verb: GET
    - log:
        message: ${! "%.3fms".format((timestamp_unix_nano() - @start) / 1000000) }

output:
  stdout: {}
```
