### ISSUE TITLE
Using buffer with archive->lines processor swallows line breaks on batch flushes

### ISSUE THREAD

**Issue by pulsar256** [benthosdev/benthos#1718]
### `test.json`

```json
{"record": 1}
{"record": 2}
{"record": 3}
{"record": 4}
{"record": 5}
{"record": 6}
{"record": 7}
{"record": 8}
{"record": 9}
{"record": 10}
```

### `pipeline.yaml`

```yaml
input:
  file:
    paths:
      - test.json
    codec: lines
output:
  stdout:
    codec: append
buffer:
  memory:
    limit: 10485760
    batch_policy:
      enabled: true
      byte_size: 20
      processors:
        - archive:
            format: lines
```

## Expected Output

Identical to input / `test.json`

## Actual output

```
ᐅ benthos --log.level=error -c pipeline.yaml
{"record": 1}
{"record": 2}{"record": 3}
{"record": 4}{"record": 5}
{"record": 6}{"record": 7}
{"record": 8}{"record": 9}
{"record": 10}%
```

## workaround

adding a `root = content() + "\n"` to the buffer processors list makes the pipeline yield expected output. 

```yaml

input:
  file:
    paths:
      - test.json
    codec: lines
output:
  stdout:
    codec: append
buffer:
  memory:
    limit: 10485760
    batch_policy:
      enabled: true
      byte_size: 20
      processors:
        - archive:
            format: lines
        - mapping: |
            root = content() + "\n"
```
