### ISSUE TITLE
Watcher mode with stdin/stdout swallows first message after reload

### ISSUE THREAD

**Issue by mihaitodor** [benthosdev/benthos#1733]
Running `benthos -w -c config.yaml` with the following `config.yaml`:

```yaml
input:
  stdin: {}
  processors:
    - mapping: |
        root = content().uppercase()
```

and replacing `uppercase()` with `capitalize()` triggers a config reload in Benthos but the first message that gets sent via stdin after that gets swallowed silently.
