### ISSUE TITLE
How to log after output?

### ISSUE THREAD

**Issue by natenho** [benthosdev/benthos#1771]
Hello!

I'm looking for a way to use the log processor *after* a succeeded output (like sending an event to aws_sqs output. Could you give me some ideas on how to achieve that?

The stdout is not an option because the ideia is to have timestamp and other static fields exactly as other logs.

Thanks

**Comment by mfamador** [comment]
Hello.

You can probably use a `broker` output likes this:

```yml
      output:
        broker:
          pattern: fan_out_sequential
          outputs:
          - any_output: {}
          - drop: {}
             processors:
             -  log:
```

**Comment by natenho** [comment]
@mfamador thank you! 

it works, but you may agree with me that it seems more like a workaround...

- The log component could be an output component, so the drop would not be needed
- Another suggestion is that we could attach a global "logger" to every component, the log component might not be needed everywhere along the configuration - it could be a cross-cutting component, that could be enriched along a pipeline.

@mihaitodor what do you think?


@mfamador using your suggestion, I'm also trying to **not** consider the "unsupported" case below as a success, would suggest anything in that case?

```yml
output:
  switch:
    cases:
      - check: errored() || content() == ""
        output:
          label: "drop_invalid"
          drop: {} # Drop invalid messages
      - output:
          broker:
            pattern: fan_out_sequential
            outputs:
              - switch: 
                  cases:
                    - check: meta("queue") == "A" # Send to SQS A
                      output:
                        aws_sqs:
                          url: https://sqs.us-east-1.amazonaws.com/AAAAAAAAAAAAAAAAA
                    - check: meta("queue") == "B" # Send to SQS B
                      output:
                        aws_sqs:
                          url: https://sqs.us-east-1.amazonaws.com/BBBBBBBBBBBBBBBBBB
                    - output:
                        processors:
                          - log:
                              message: "unsupported"
                              level: ERROR
                          - mapping: root = throw("unsupported")
                        label: "drop_unsupported"
                        drop: {} # Drop unsupported <----------- the success output is called anyway
              - label: "success"
                processors:
                  - log:
                      message: "message sent successfully"
```

**Comment by mihaitodor** [comment]
I'd probably move that `success` processor inside the relevant `switch` cases, which adds a bit of duplication, but that's not the end of the world, I suppose. There might be more elegant ways to tackle this and, also, there might be a case for enhancing logging, but I'll have to defer that conversation to Ash.

On the other hand, I do think it's worth questioning any heavy reliance on logging. Consider a metrics-driven approach if possible. Attempting to log everything is usually not a recipe for success, not that you can't do it, but you'll likely find them cumbersome when it comes to extracting the signals that you wish to derive from them and they might also impact performance.

**Comment by natenho** [comment]
Thanks @mihaitodor, I think there is one more problem though. The `aws_sqs` output will never exit in case of error. So the success will never be reached in that case (as expected), but...what if I wanted to drop the message after a certain time (i.e. use the `drop_on` output)?

I understand your concern about logging. In my case I need to track some detailed information to have evidences of a given message being sent or not (and why).

**Comment by mihaitodor** [comment]
> The `aws_sqs` output will never exit in case of error. 

The [fallback](https://www.benthos.dev/docs/components/outputs/fallback) output might help you in such scenarios.

> what if I wanted to drop the message after a certain time (i.e. use the drop_on output)? It would consider as a succeeded output, right?

I believe so, but hey, if you have such stringent requirements, you should spend the time to design test setups for each of the workflows and error scenarios that your pipeline needs to handle.

**Comment by natenho** [comment]
@mihaitodor sorry to bother with that, I'm struggling with something that seems to be simple - would you mind to write a  example? Benthos has a potential to be a game changer for my team and I've been investing some effort to understand how far can we go with it.

My requirement is to run a log processor when an sqs output succeeded and run another when an sqs output fail, both including the message that was processed.

**Comment by mihaitodor** [comment]
Hey @natenho, I couldn't come up with a reasonable way to switch between two processors based on the outcome of the output, so what I think you should go for is something like the following:

```yaml
input:
  generate:
    count: 1
    interval: 1s
    mapping: root = ""

output:
  broker:
    pattern: fan_out_sequential
    outputs:
      - fallback:
          - aws_sqs:
              url: ...
          - drop: {}
            processors:
              - log:
                  message: |
                    Failed ${! @uuid } with error: ${! @fallback_error }

      - drop: {}
        processors:
          - log:
              message: |
                Finished ${! @uuid }

  processors:
    - mapping: |
        meta uuid = uuid_v4()
```

The idea here is that I'm setting a metadata field called `uuid` which gets printed by both `log` processors. However, the one from inside the `fallback` output will only get triggered when the `aws_sqs` output fails. I guess this might not be ideal, since it sounds like you'd rather not get the `Finished: ... ` log at all in the case of failures, but there isn't any way currently to get that to work at the output level, even if you try inverting the `broker` and the `fallback`.

One potential workaround would be to add an `aws_sqs` processor. If you think this unblocks you, feel free to raise an issue for it and, until someone gets a chance to add it, you can maintain your own as a custom plugin (see [here](https://github.com/benthosdev/benthos-plugin-example)).

**Comment by natenho** [comment]
Hello @mihaitodor, thank you for your time. I see that you arrived at a similar conclusion.

I have a suggestion that I am elaborating on: creating try, log, and catch components as output components, so that they would function exactly like they do in the processor. This would make the configuration below valid:

```yml
input:
  generate:
    count: 1
    interval: 1s
    mapping: root = ""

output:
  broker:
    pattern: fan_out_sequential
    outputs:
      - try:
          - aws_sqs:
              url: ...
          - log:
              message: |
                Success ${! @uuid }
          - catch:
              - log:
                  message: |
                    Failed ${! @uuid } with error: ${! error() }

  processors:
    - mapping: |
        meta uuid = uuid_v4()
```

To make it more idiomatic, I suggest removing the broker and assuming that `try` is a "group of sequential outputs". This would make it behave exactly like `broker` output with the pattern fan_out_sequential. Here is an example of what it could look like:

```yml
input:
  generate:
    count: 1
    interval: 1s
    mapping: root = ""

output:
  try:
    - aws_sqs:
        url: ...
    - log:
        message: |
          Success ${! @uuid }
    - catch:
      - log:
          message: |
            Failed ${! @uuid } with error: ${! error() }

  processors:
    - mapping: |
        meta uuid = uuid_v4()
```

What do you think about that?
I'm willing to try writing them as plugins. At least, adding the log output component would be a useful addition.

**Comment by mihaitodor** [comment]
There are multiple non-trivial enhancement proposals in there and I don't have the background to say how they fit in the overall design and workflow. Consider breaking those down into individual proposals in distinct issues and provide some examples of how they'd be used. Personally, I feel that `try` isn't very expressive as an alternative to `broker` with `fan_out_sequential`, but dunno how to make it better, so I'll defer to Ash for future feedback to avoid noise.

**Comment by natenho** [comment]
Okay, you're probably right that this could be non-trivial, as I haven't considered the code involved. I admit that I haven't studied the internals of Benthos enough to fully understand the feasibility of this approach.

Regarding the design, I agree that we should discuss it further with @Jeffail. As I mentioned before, this issue isn't a major blocker for me, and using plugins could be a way to avoid relying too tightly on core features.

**Comment by narzdavid** [comment]
@Jeffail  could we maybe support `log` as an output  or add  `post-processors` to outputs? I think this is an important use case where we need to log downstream calls to measure latency for a specific transaction

I followed the advice here and it involved a massive refactor of our pipelines 😅

**Comment by mihaitodor** [comment]
@narzdavid As a workaround, you can use the `stdout` output with an associated `mapping` processor to emulate a `log` output. The downside is that it wouldn't take the [`logger config`](https://www.benthos.dev/docs/components/logger/about) into account

**Comment by mfamador** [comment]
>  measure latency for a specific transaction

Maybe you can measure your outputs latency using the available metrics?https://www.benthos.dev/docs/components/metrics/about/#outputs

**Comment by narzdavid** [comment]
Hey @mihaitodor @mfamador! Thanks for your suggestions! 

Actually, we do use and monitor the latency metrics. But we do need in some cases to look what happened to a specific transaction, not just the aggregate latency.

> LE: You can always use processors as a outputs via the pattern defined here: https://www.benthos.dev/docs/components/processors/about#using-processors-as-outputs. In this case, the [log processor](https://www.benthos.dev/docs/components/processors/log) should do the trick

Yes, that is actually our implementation, but note that processors are run before the output is executed:
```yaml
output_processors:
  - label: log_success
    drop: {}
    processors: 
      - log:
          message: 'published successfully'
``` 
or
```yaml
output_processors:
  - label: log_success
    subprocess:
       command: "cat" 
    processors: 
      - log:
          message: 'published successfully'
``` 

But I would say this looks verbose, and it would be better to have the log attached to the output resource itself rather than making an aritificial output, like this one

```yaml
  switch:
    cases:
      - check: erorred() != true
        resource: http_client
            processors: # i want this called before http_client
              - resource: log_before
            post-processors: # i want this called after
              - resource: log_after
      - check: errored()
        resource: something else
``` 

rather than the complex switch:
```yaml
  switch:
    cases:
      - check: erorred() != true
        resource: http_client
            processors: # i want this called before http_client
              - resource: log_before
        continue: true
      - check: errored() != true
        drop: {} # artificial drop just to log it
        processors:
          - resource: log_after
      - check: errored()
        resource: something else
```

Additionally it's generating extra outputs which are annoying in the metrics list.

**Comment by mihaitodor** [comment]
> Actually, we do use and monitor the latency metrics. But we do need in some cases to look what happened to a specific transaction, not just the aggregate latency.

OK, then how about a [`broker` output](https://www.benthos.dev/docs/components/outputs/broker) with [`pattern: fan_out_sequential`](https://www.benthos.dev/docs/components/outputs/broker#fan_out_sequential) like I demoed [above](https://github.com/benthosdev/benthos/issues/1771#issuecomment-1447520515). Replace the `fallback` output I have there with your output together with a `log` processor and then the second output in the broker is a `drop` output with another `log` processor. That way, the second `log` processor will run immediately after the real output finishes writing the message.

> But I would say this looks verbose, and it would be better to have the log attached to the output resource itself rather than making an aritificial output, like this one

That would require some non-trivial code changes which might not be aligned with the current pipeline design. I'll have to defer to Ash for thoughts on that

**Comment by natenho** [comment]
@narzdavid you can use templates to abstract the log component, I agree that we could have a post processor or the log output itself though.

I'm currently working on some templates to reuse in my configuration while there is no "official" component for that:

# Log
This hides the workaround on drop/stdout output to run the log processor.
```
name: log
type: output
status: experimental
summary:

fields:
  - name: level
    type: string
    default: INFO
    description: |-
       The log level to use.
       Options: FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL.

  - name: fields_mapping
    type: string
    default: "root = this"
    description: |-
      An optional Bloblang mapping that can be used to specify extra fields to add to the log.
      If log fields are also added with the fields field then those values will override matching keys from this mapping.

  - name: message
    type: string
    default: ""
    description: |-
      The message to print. This field supports interpolation functions.

mapping: |-
  root.stdout = {}
  root.processors = [
    {
      "log": {
        "level": this.level,
        "message": this.message,
        "fields_mapping": this.fields_mapping
      }
    },
    {
      "mapping": "root = deleted()"
    }
  ]
```

# Try
This is an attempt to hide the verbosity when doing the fan_out_sequential pattern suggested by @mihaitodor:

```
name: try
type: output
status: experimental
summary: Behaves exactly like `broker` output with the pattern `fan_out_sequential`

fields:
  - name: outputs
    type: unknown
    kind: list
    description: |-
      List of child outputs

  - name: processors
    type: unknown
    kind: list
    default: []
    description: |-
      List of processors to run before output

mapping: |-
  root.broker = {
    "pattern": "fan_out_sequential",
    "outputs": this.outputs,
    "processors": this.processors
  }
```

Together, they can be used like this

```
output:
  try:
    outputs:
      - sync_response: {}
      - http_client:
          url: http://localhost:5000/ping
          verb: POST
      - log:
          message: success
```

So the success message can be done that way, if you are ok to accept the back pressure on error, that will be indefinitely logging an error message and the success log will never be printed.

What I could not figure out is a way to log a "failure" message (dropping on first error). The problem is that it is not possible to skip the "success" log when you dropped the message, like this:


```
output:
  try:
    outputs:
      - sync_response: {}
      - fallback:
        - http_client:
              url: http://localhost:5000/ping
              verb: POST
        - log: # This output causes the "success" log to also run, because it finishes the fallback with success
            level: ERROR
            message: failure 
      - log:
          message: success
```

**Comment by narzdavid** [comment]
Hi @natenho, 

> So the success message can be done that way, if you are ok to accept the back pressure on error, that will be indefinitely logging an error message and the success log will never be printed.
I certainly had this issue with the `fan_out_sequential` broker, which is not acceptable to our use case, since we expect some failures in our downstream services. 

The thing I went with that will meaningfully log on success and error is to use switch-continue (i.e. fallthrough) logic. 

```
  switch:
    cases:
      - check: erorred() != true
        output:
          resource: http_client
          processors: # i want this called before http_client
            - resource: log_before
        continue: true ## this will evaluate the next checks regardless of http_client outcome
      - check: errored() != true
        output:
          drop: {} # artificial drop just to log it
          processors:
            - resource: log_after_http_success
      - output:
           drop: {}
           processors:
             - resource: log_after_http_error
```

**Comment by rasnes** [comment]
Hi. I am also struggling to get this as I'd like, to have full control over logging (or any other `output`) conditional on the "main" `output`'s success or failure. I've tried the above in different combinations, but can't get it exactly as I want, my use case is pretty identical to yours @natenho. Please share if anyone has had any progress on this, thanks!

**Comment by rasnes** [comment]
Found something that seems to work as I want it to in my case, but I have not tested all edge cases. It does _not_ `drop` the messages that fail to be delivered, this solution applies backpressure. By using [reject](https://www.benthos.dev/docs/components/outputs/reject/) in the `fallback` for logging failure when `message_sink` fails, it seems the `fallback` will not succeed and hence not jump to "next step" in the `fan_out_sequential` broker (`drop_n_log_success) but rather apply backpressure in the `fallback` until it (perhaps never) succeeds.

```yaml
output:
  broker:
    pattern: fan_out_sequential
    outputs:
      - fallback:
        - resource: message_sink
        - resource: reject_n_log_failure
      - resource: drop_n_log_success

output_resources:
  - label: reject_n_log_failure
    reject: "rejecting message"
    processors:
      - log:
          level: ERROR
          message: failure
  - label: drop_n_log_success
    drop: {}
    processors:
      - log:
          level: INFO
          message: success
  - label: message_sink
     any_benthos_output: {}
```

I tried to `drop` the message via a `mapping` processor step in the `reject`, but this for some reason then evaluates as a "success" in the `fallback`, so then we're back to where we started :D 

```yaml
  - label: reject_n_log_failure
    reject: "rejecting message"
    processors:
      - log:
          level: ERROR
          message: failure
      - mapping: |
          root = deleted() # This drops the message, but the reject_n_log_failure resource now succeeds
```
In my current case I can live with backpressure, but it is certainly not always the case.
