### ISSUE TITLE
Unconnected inproc output causes pipeline to stall

### ISSUE THREAD

**Issue by disintegrator** [benthosdev/benthos#1780]
I think there's an issue in Benthos - well not sure it's an issue - where an unconnected inproc output fails quietly. As in, it doesn't even trigger fallback to go to next output. Minimal repro:

```yaml
input:
  generate:
    mapping: |
      root = nanoid()
    interval: 3s

output:
  fallback:
    - inproc: nonexistent
    - stdout: {}
```

Run this with streams mode.

Expected behaviour: there's an immediate error at the inproc output that triggers a fallback to stdout.
Actual behaviour: the benthos pipeline stalls indefintely due to backpressure while it waits for in-flight messages to be processed by `inproc`.

**Comment by Jeffail** [comment]
I think I might solve this by making https://www.benthos.dev/docs/components/outputs/drop_on more powerful. Right now the back pressure mechanism only cancels on the transaction delivery, which means there could always be a single transaction fully blocked on send while subsequent transactions are immediately rejected.

It wasn't really possible to solve this in V3 because using contexts in write methods was opt-in, whereas now all delivery mechanisms for transactions have the potential to honour cancellation. I think it makes sense to add a deadline to all transaction contexts delivered from a `reject_on` to child outputs so that in events like this where the behaviour is to wait for availability we can customise an exit from that via composure. The long play here is that composure is more powerful than having a new `inproc` output with a `timeout` field as you can potentially add mechanisms that do cleverer things like rate limiting or whatever.

^ Just notes for me really, in short the outcome would be that:

```yaml
output:
  fallback:
    - reject_on:
        back_pressure: 10ms
        output:
          inproc: foo
    - something_else: {}
```

Would attempt to send messages to `foo` but if nothing is connected then we fall back to the next thing. Right now this would kind of work except the first message would get stuck forever within `inproc: foo` waiting for something to connect to it.
