### ISSUE TITLE
Mapping message to a `string` causes error

### ISSUE THREAD

**Issue by krazylek** [benthosdev/benthos#1781]
Using a simple mapping pipeline like this:

```yml
input:
  generate:
    count: 1
    interval: 0s
    mapping: |
      root = { "hello": "world" }

pipeline:
  processors:
    - mapping: |
        root = "test"
    - log:
        level: INFO
        message: '${! this }'
```

Will generate the correct output, but the `log` processor will fail with a `Message interpolation error: context was undefined` error.
Here the error is actually caused by the `log`, but the underlying problem would also make a `branch` processor fail:

```yml
input:
  generate:
    count: 1
    interval: 0s
    mapping: |
      root = { "hello": "world" }

pipeline:
  processors:
    - branch:
        processors:
          - mapping: |
              root = "test"
        result_map: |
          root.test_value = this
```

It will cause a `Branch error: result mapping failed: failed assignment` and `test_value` won't be set.

Last insight, it happens whatever the source input component is, and for all type of message. From what I see, even from a `string`! 
Example:

```yml
input:
  generate:
    count: 1
    interval: 0s
    mapping: |
      root = "hello world"

pipeline:
  processors:
    - mapping: |
        root = this
```

Here I get a `failed assignment (line 1): unable to reference message as structured (with 'this'): parse as json: invalid character 'h' looking for beginning of value"`. 
Please note that the `'h'` mentioned is the first letter in the `"hello world"` input.

**Comment by peczenyj** [comment]
I think the issue is: `this` is common used when handling json like messages: 

https://www.benthos.dev/docs/guides/bloblang/about#trouble-shooting 

you can substitute `this` by `content()` and it should works

```
pipeline:
  processors:
    - mapping: |
        root = "test"
    - log:
        level: INFO
        message: '${! content() }'
```

**Comment by krazylek** [comment]
Yes indeed, that makes sense... I guess this automatic parsing brings some nice magic in some cases!

Also my  `branch` example would be solved with the `content()` solution:

```yml
pipeline:
  processors:
    - branch:
        processors:
          - mapping: |
              root = "test"
        result_map: |
          root.test_value = content()
```

Gives me the expected output.

Thank you for you help and sorry for the false issue!
