### ISSUE TITLE
Test failing for matching object metadata

### ISSUE THREAD

**Issue by natenho** [benthosdev/benthos#1791]
Given the following example config:

benthos.yml
```yml
input:
  stdin:
    codec: lines
pipeline:
  processors:
    - mapping: |
        meta foo = { "bar": "hello" }
output:
  stdout:
    codec: lines
```

benthos_benthos_test.yml

```yml
tests:
  - name: Should not fail
    target_processors: "/pipeline/processors"
    mocks:
    input_batch:
      - content: hello
    output_batches:
      - - metadata_equals:
            foo: { "bar": "hello" }
```

Running 

```shell
$ benthos test benthos.yml
Test 'benthos.yml' failed

Failures:

--- benthos.yml ---

Should not fail [line 2]:
batch 0 message 0: metadata_equals: metadata key 'foo' mismatch
  expected: map[bar:hello]
  received: map[bar:hello]
```

Notice the content is the same, althought the test fails anyway
