### ISSUE TITLE
[BUG] Custom INPUT HTTP_SERVER doesn't support path variables.

### ISSUE THREAD

**Issue by silvioramalho** [benthosdev/benthos#1797]
## Context

Setting up a scenario with INPUT/HTTP_SERVER, with a variable in the first parameter of the path. 

* Example: "/{varName}"

For this, in the YAML file, it was necessary to assign an ADDRESS to the HTTP_SERVER, where Benthos creates a new HTTP_SERVER, different from the wide server.

```
http_server:
    address: 0.0.0.0:4197
    path: /{costomer_id}
    timeout: 5s
    allowed_verbs:
      - POST
    sync_response:
      status: "200"
      headers:
        Content-Type: application/json
```

Upon reviewing the code, I identified that this new HTTP_SERVER does not use the Gorilla Mux ROUTER to create routes. As a result, there is no extraction of variables included in the PATH. Therefore, the behavior of the wide server is different from that of an alternative HTTP_SERVER.
