### ISSUE TITLE
Refactor drop_on output to use the new APIs and support batching in the underlying output

### ISSUE THREAD

**Issue by mihaitodor** [benthosdev/benthos#1798]
Currently, the following config will block forever:

```yaml
input:
  generate:
    count: 10
    mapping: root = count("test")
    interval: 250ms

output:
  drop_on:
    back_pressure: 0s
    error: false
    output:
      sql_raw:
        driver: sqlite
        dsn: file::memory:?cache=shared
        query: SELECT 1
        batching:
          count: 2 # Change this to 1 to unblock
          processors:
            - log:
                message: ${! batch_index() } - ${! batch_size() }
```
