### ISSUE TITLE
bloblang's 'ts_tz' function returns a time.Time object instead of a string

### ISSUE THREAD

**Issue by mterron** [benthosdev/benthos#1799]
This is the repro benthos config I'm using:
`stdout.yml`
```yaml
input:
  stdin: {}

pipeline:
  processors:
    - mapping: |-
          root.seen = this.data.seen.ts_tz("Local")

output:
    stdout:
      codec: lines
    processors:
      - jq:
          query: '"\u001b[38;5;247m" + .seen'
          output_raw: true
```

Input line:
```sh
$ cat input.json
{"seen":1675039636.87296}
```

Output:
```sh
$ cat input.json | benthos -c stdout.yml
INFO Running main config from specified file       @service=benthos path=stdout.yml
INFO Launching a benthos instance, use CTRL+C to close  @service=benthos
panic: invalid value: 2023-01-30 13:47:16.874628067 +1300 NZDT

goroutine 67 [running]:
github.com/itchyny/gojq.typeof({0x2f7c260?, 0xc000911788?})
        /home/runner/go/pkg/mod/github.com/itchyny/gojq@v0.12.6/error.go:346 +0x1c5
github.com/itchyny/gojq.typeErrorPreview({0x2f7c260, 0xc000911788})
        /home/runner/go/pkg/mod/github.com/itchyny/gojq@v0.12.6/error.go:328 +0x98
github.com/itchyny/gojq.(*binopTypeError).Error(0xc000a415f0)
        /home/runner/go/pkg/mod/github.com/itchyny/gojq@v0.12.6/error.go:175 +0x65
github.com/benthosdev/benthos/v4/internal/impl/pure.(*jqProc).Process(0xc0009b7f40, {0x54c21c0?, 0x2fdc6d0?}, 0xc000911740)
        /home/runner/work/benthos/benthos/internal/impl/pure/processor_jq.go:174 +0x213
github.com/benthosdev/benthos/v4/internal/component/processor.(*v2ToV1Processor).ProcessBatch.func1(0x40d85f?, 0xc000911740)
        /home/runner/work/benthos/benthos/internal/component/processor/processor_v2.go:80 +0xbb
github.com/benthosdev/benthos/v4/internal/message.Batch.Iter({0xc00011b1f0, 0x1, 0xc0000a0800?}, 0xc001161d48)
        /home/runner/work/benthos/benthos/internal/message/message.go:70 +0x137
github.com/benthosdev/benthos/v4/internal/component/processor.(*v2ToV1Processor).ProcessBatch(0xc000cc8630, {0x398cd28, 0xc000c0ed80}, {0xc00011b1f0, 0x1, 0x1})
        /home/runner/work/benthos/benthos/internal/component/processor/processor_v2.go:77 +0x129
github.com/benthosdev/benthos/v4/internal/component/processor.ExecuteAll({0x398cd28, 0xc000c0ed80}, {0xc000a491e0, 0x1, 0x0?}, {0xc0000726c0?, 0x1, 0x0?})
        /home/runner/work/benthos/benthos/internal/component/processor/execute.go:22 +0x1b6
github.com/benthosdev/benthos/v4/internal/pipeline.(*Processor).loop(0xc00066de00)
        /home/runner/work/benthos/benthos/internal/pipeline/processor.go:69 +0x285
created by github.com/benthosdev/benthos/v4/internal/pipeline.(*Processor).Consume
        /home/runner/work/benthos/benthos/internal/pipeline/processor.go:139 +0x79
```

Now if I remove the processor from the output and instead run it as an external `go-jq` process, everything works as expected.

Benthos config file:
`stdout2.yml`
```yaml
input:
  stdin: {}

pipeline:
  processors:
    - mapping: |-
          root.seen = this.data.seen.ts_tz("Local")

output:
    stdout:
      codec: lines
```
Output:
```sh
$ cat input.json | benthos -c stdout.yml | gojq -r '"\u001b[38;5;247m" + .seen'
INFO Running main config from specified file       @service=benthos path=stdout2.yml
INFO Launching a benthos instance, use CTRL+C to close  @service=benthos
2023-01-30T13:47:16.87296009+13:00
```
