### ISSUE TITLE
`processor_error` metric not incremented for bloblang errors

### ISSUE THREAD

**Issue by disintegrator** [benthosdev/benthos#1805]
Given the following config:
```yaml
input:
  generate:
    mapping: |
      root = {"greeting": "hello"}
      meta request_id = nanoid()

pipeline:
  processors:
    - mapping: |
        root = throw("lolol")
    - log:
        message: 'errored? ${!errored()}'

output:
  drop: {}
```

and corresponding output:
```
ERRO failed assignment (line 1): lolol             @service=benthos label="" path=root.pipeline.processors.0
INFO errored? true                                 @service=benthos label="" path=root.pipeline.processors.1
```

I noticed that the `processor_error` is not getting incremented. I was also able to confirm this issue in other areas like if there's a mapping error `log.fields_mapping`.
