### ISSUE TITLE
sql insert plugins how to use dynamic columns and args_mapping 

### ISSUE THREAD

**Issue by NewSun1999** [benthosdev/benthos#1808]
```
input:
  kafka:
    addresses:
      - 127.0.0.1:9092
    topics: [ test_1 ]
    consumer_group: test
    client_id: test
    checkpoint_limit: 1000
    target_version: 1.0.0
    start_from_oldest: false

pipeline:
  threads: 1
  processors:
    - label: "print_first_log"
      log:
        level: INFO
        message: hello world
    - unarchive:
        format: json_array
    - mapping: |
        root.header = this.keys()
        root.cool = this.keys().map_each(item -> item.trim("#")).join(",")
        root.hot = "this." + this.keys().map_each(item -> item.trim("#")).join(",this.")
output:
    sql_insert:
      driver: mysql
      dsn: xxxxxxxxxxxx
      table: test
      columns: [ Here use root.hot ]
      args_mapping: |
        root = [
          Here use root.cool
        ]     
      batching:
        count: 5000
        period: 5s
```
How to quote？
