### ISSUE TITLE
http_server input path matching changed in 4.13.0

### ISSUE THREAD

**Issue by disintegrator** [benthosdev/benthos#1813]
The switch from `http.ServeMux` to gorilla's `mux.Router` changed the path matching behaviour in the `http_server` input. Given the following config:

```yaml
input:
  http_server:
    address: 0.0.0.0:3000
    allowed_verbs: [GET]
    path: /

output:
  sync_response: {}
  processors:
    - mapping: |
        root = {
          "message": "ok",
          "path": @http_server_request_path
        }
```

With Benthos 4.12.1:

```
❯ curl localhost:3000/hello/world
{"message":"ok","path":"/hello/world"}
```

With Benthos 4.13.0
```
❯ curl localhost:3000/hello/world
404 page not found
```

I expected the behaviour under 4.12.1 and prior versions to be preserved.
