### ISSUE TITLE
Flag `--env-file` doesn't handle Windows line terminators correctly

### ISSUE THREAD

**Issue by mihaitodor** [benthosdev/benthos#1820]
Try running `benthos -c ./test.yaml -e ./test.txt` and use the attached file.

```yaml
input:
  generate:
    count: 1
    interval: 0s
    mapping: |
      let str = "|" + env("FOO") + "|" + env("BAR") + "|"
      root = $str.replace_all("\r", "x")

output:
  stdout: {}
```

The output will be `|abcx|defx|` instead of `|abc|def|`.

[test.txt](https://github.com/benthosdev/benthos/files/11082338/test.txt)
