### ISSUE TITLE
Support interpolation in template fields

### ISSUE THREAD

**Issue by natenho** [benthosdev/benthos#1829]
I'd like to improve the template below by allowing interpolation (i.e. bloblang queries) in message field. How could I do that?

```
name: foo
type: output
status: experimental

fields:
  - name: message # I'd like to enable interpolation for this field
    type: string
    default: ""

mapping: |-
  root.stdout = {}
  root.processors = [
    {
      "mapping": "root = " + this.message
    }
  ]
```

So the config can look like this:

```
output:
  foo:
    message: ${! this.popcorn.uppercase() }
```

**Comment by mihaitodor** [comment]
Hey @natenho, try this:

```yaml
name: foo
type: output
status: experimental

fields:
  - name: message
    type: string
    default: ""

mapping: |
  let isInterpolated = this.message.has_prefix("${!") && this.message.has_suffix("}")
  root.stdout = {}
  root.processors = [
    {
      "mapping": "root = " + if $isInterpolated { this.message.trim_prefix("${!").trim_suffix("}") } else { "\"" + this.message + "\"" }
    }
  ]
```

```yaml
input:
  generate:
    count: 1
    mapping: |
      root.popcorn = "smells nice"
output:
  foo:
    message: ${! this.popcorn.uppercase() }
```

```shell
benthos -t foo.tmpl.yaml -c foo.yaml
```

**Comment by natenho** [comment]
@mihaitodor is that code working in your environment? I've just opened this #1832

**Comment by Jeffail** [comment]
If you ignore the linting part then it's possible to have an interpolated field be translated into another interpolated field as part of the output config, for example if you define a string field `foo` and create an output config with `kafka.topic = this.foo` then it'll be interpolated because the `topic` field is interpolated.

However, it looks like you're asking to interpolate strings within the mapping that translates into the config, I'm not sure we'd want to open that can of worms as there's no concept of a "message" in that mapping.

**Comment by mihaitodor** [comment]
> However it would not have the same behavior as the [interpolation](https://www.benthos.dev/docs/configuration/interpolation/), so this string would not work: dope-${! json("topic") }, it may require a more complex logic to achieve.

![image](https://user-images.githubusercontent.com/788216/229591774-4fcb88ca-4650-49e5-860f-3e3d785dc866.png)

Try this:

```yaml
name: foo
type: output
status: experimental

fields:
  - name: message
    type: string
    default: ""

mapping: |
  map fix_close_brace {
    let segment = this.value
    let isFirst = this.index == 0
    let closePos = match $segment.reverse().index_of("}") {
      -1 => -1,
      _ => $segment.length() - 1 - this
    }
    let suffix = if closePos != -1 { $segment.slice($closePos + 1) } else { "" }

    root = match {
      $closePos != -1 && $isFirst => "\"" + $segment + "\""
      $closePos != -1 && !$isFirst => $segment.slice(0, $closePos) + if $suffix.length() > 0 { "+ \"" + $suffix + "\"" } else { "" }
      $segment.length() > 0 => "\"" + $segment + "\""
    }
  }

  let parsedMessage = this.message.split("${!").enumerated().map_each(segment -> segment.apply("fix_close_brace")).join(" +")

  root.stdout = {}
  root.processors = [
    {
      "mapping": $parsedMessage
    }
  ]
```

@Jeffail I think he just wants to forward the interpolation to the underlying `mapping` processor, but the interpolation gets evaluated at the template level, which seems a bit limiting in this case. Not sure if I'm considering all the potential for abuse, though...

**Comment by natenho** [comment]
😂 Worked perfectly!
Thanks again!

One concrete use case is that I'm developing a Slack bot (which I want to share with you guys as soon as my PoC worked, and hopefully someday it can be part of benthos codebase 😊). I've created a processor template that produces the [Slack API HTTP request body](https://api.slack.com/methods/chat.postMessage) and with, @mihaitodor code its parameters can now be passed as static strings and/or real interpolated strings:

```
    - label: slack
      slack:
        oauth_token: ${! @slack_oauth_token }
        channel: ${! @channel }
        text: >-
            Helloo  ${! content().string() }
```

or static
```
    - label: slack
      slack:
        oauth_token: "AAAAAAAAAAAAAA"
        channel: "XXXXXXXXX"
        text: "Hello popcorn world!"
```
