### ISSUE TITLE
Issue publishing metrics to CloudWatch

### ISSUE THREAD

**Issue by acovaci** [benthosdev/benthos#1830]
Hi.

I'm trying to set up Benthos to publish its metrics into AWS CloudWatch, and I'm running into issues. Looking at the logs I can see:

```log
Failed to send metric data: InvalidParameter: 4 validation error(s) found.
- minimum field size of 1, PutMetricDataInput.MetricData[0].Dimensions[0].Value.
...
```

My `config.yaml` looks pretty straightforward:

```yaml
metrics:
  aws_cloudwatch:
    namespace: "MyAwesomeNamespace"
    region: "us-west-2"
```

Am I missing anything obvious?

Thanks

**Comment by acovaci** [comment]
I'm far from understanding golang, but pitching in in case it helps.

Could it be that when objects like these get instantiated without a dimension, it instantiates to an empty list?

```go
func (c *cwMetrics) GetCounter(path string) metrics.StatCounter {
	return &cloudWatchStat{
		root: c,
		id:   path,
		name: path,
		unit: cloudwatch.StandardUnitCount,
	}
}
```

see: https://github.com/benthosdev/benthos/blob/e31f87c0a1df8f9cbff7f4282f7742d5da7a327a/internal/impl/aws/metrics_cloudwatch.go#LL270-L277C2

**Comment by Jeffail** [comment]
Hey @acovaci, this could be due to dimensions being added with empty values. I haven't got cloudwatch set up to check but a quick way to verify would be to delete empty tags when they get registered with this mapping:

```yaml
metrics:
  aws_cloudwatch:
    namespace: "MyAwesomeNamespace"
    region: "us-west-2"
  mapping: |
    meta = @.map_each(kv -> if kv.value.length() == 0 { deleted() })
```
