### ISSUE TITLE
Idea - Support remote templates

### ISSUE THREAD

**Issue by natenho** [benthosdev/benthos#1838]
Hi!

An idea to improve Templating would be to allow referencing local and remote templates, something like this:

```
input:
  template:
    source: https://raw.githubusercontent.com/benthosdev/benthos/main/config/template_examples/processor_log_message.yaml
    paramters:
        level: DEBUG
```

or to create a template resource:

```
template_resources:
  - label: log_and_drop
    source: https://raw.githubusercontent.com/benthosdev/benthos/main/config/template_examples/processor_log_and_drop.yaml
    paramters:
        level: DEBUG
```

```
template_resources:
  - label: log_and_drop
    source: ./templates/processor_log_and_drop.yaml # could be a remote address as well
    paramters:
        level: DEBUG
```
