### ISSUE TITLE
Upgrade github.com/segmentio/parquet-go

### ISSUE THREAD

**Issue by mihaitodor** [benthosdev/benthos#1855]
Unfortunately, `github.com/segmentio/parquet-go` has introduced some breaking changes and, as uncovered in #1851, upgrading it might not be a trivial task. For example this config:

```yaml
input:
  generate:
    mapping: |
      root = {"A":[{"B":1.0,"C":2.0},{"B":3.0,"C":4.0}]}
    count: 1
    interval: 0s
  processors:
    - parquet_encode:
        schema:
          - name: A
            repeated: true
            fields:
              - name: B
                type: FLOAT
              - name: C
                type: FLOAT
    - log:
        message: |
          Error: ${! error() }

output:
  stdout: {}
```

generates a panic after upgrading `github.com/segmentio/parquet-go` to the latest version (`v0.0.0-20230404173032-05ed5ed000b1`):

```
panic: runtime error: index out of range [2] with length 2

goroutine 69 [running]:
github.com/segmentio/parquet-go.(*writer).WriteRows.func1.2(0x1?, {0xc000882330?, 0x60?, 0x60?})
	/Users/mihaitodor/Projects/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20230404173032-05ed5ed000b1/writer.go:709 +0x14e
github.com/segmentio/parquet-go.Row.Range({0xc000882300, 0x4, 0x4}, 0xc0016c99c8)
	/Users/mihaitodor/Projects/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20230404173032-05ed5ed000b1/row.go:107 +0xa9
github.com/segmentio/parquet-go.(*writer).WriteRows.func1(0xc0008ba240?, 0xc0008822a0?)
	/Users/mihaitodor/Projects/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20230404173032-05ed5ed000b1/writer.go:708 +0xf5
github.com/segmentio/parquet-go.(*writer).writeRows(0xc00089c9a0, 0x1, 0xc0016c9a58)
	/Users/mihaitodor/Projects/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20230404173032-05ed5ed000b1/writer.go:758 +0xbb
github.com/segmentio/parquet-go.(*writer).WriteRows(0x0?, {0xc0005bc9a8?, 0x0?, 0xffffffffffffffff?})
	/Users/mihaitodor/Projects/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20230404173032-05ed5ed000b1/writer.go:695 +0x58
github.com/segmentio/parquet-go.(*Writer).WriteRows(...)
	/Users/mihaitodor/Projects/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20230404173032-05ed5ed000b1/writer.go:157
github.com/segmentio/parquet-go.(*GenericWriter[...]).WriteRows(0xc0015ea0a0?, {0xc0005bc9a8?, 0xc0016c9b68?, 0xc0016c9b08?})
	/Users/mihaitodor/Projects/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20230404173032-05ed5ed000b1/writer_go18.go:176 +0x2b
github.com/benthosdev/benthos/v4/internal/impl/parquet.(*parquetEncodeProcessor).ProcessBatch(0xc0011f74c0, {0x1?, 0xc0008820c0?}, {0xc001a16010, 0x1, 0x1032a9820?})
	/Users/mihaitodor/Projects/jeffail/benthos/internal/impl/parquet/processor_encode.go:256 +0x316
github.com/benthosdev/benthos/v4/public/service.(*airGapBatchProcessor).ProcessBatch(0xc001ad3280, 0xc0008820c0, {0xc0000151e8, 0x1, 0x1})
	/Users/mihaitodor/Projects/jeffail/benthos/public/service/processor.go:112 +0x103
github.com/benthosdev/benthos/v4/internal/component/processor.(*v2BatchedToV1Processor).ProcessBatch(0xc000ca9d40, {0x104007050?, 0xc000de6000}, {0xc0000151e8, 0x1, 0x1})
	/Users/mihaitodor/Projects/jeffail/benthos/internal/component/processor/auto_observed.go:223 +0x288
github.com/benthosdev/benthos/v4/internal/component/processor.ExecuteAll({0x104007050, 0xc000de6000}, {0xc0011f7240, 0x2, 0xc0016ce7c0?}, {0xc0016c9e88?, 0x1, 0x1?})
	/Users/mihaitodor/Projects/jeffail/benthos/internal/component/processor/execute.go:19 +0x1fc
github.com/benthosdev/benthos/v4/internal/pipeline.(*Processor).loop(0xc0006e2080)
	/Users/mihaitodor/Projects/jeffail/benthos/internal/pipeline/processor.go:69 +0x2c5
created by github.com/benthosdev/benthos/v4/internal/pipeline.(*Processor).Consume
	/Users/mihaitodor/Projects/jeffail/benthos/internal/pipeline/processor.go:139 +0x79
```
