### ISSUE TITLE
Check that the input interface data meets the expectations and then request api data

### ISSUE THREAD

**Issue by gaoshenga** [benthosdev/benthos#1859]
hello,Does benthos have the ability to monitor when one interface returns the desired data, and then retrieve the data from another?

**Comment by mihaitodor** [comment]
Hey @gaoshenga, I'm not sure I understand what you're looking to do and it would help to get a detailed example. However, I think you might be looking for the [`sequence` input](https://www.benthos.dev/docs/components/inputs/sequence), which can have, for example, a [`read_until` input](https://www.benthos.dev/docs/components/inputs/read_until/) as its first child. Then, in this `read_until` input, you could use a [`bloblang`](https://www.benthos.dev/docs/guides/bloblang/about) expression to check when a certain condition is met and, when that happens, the `read_until` input will shut down and the `sequence` input will proceed to read from the next child input. Hope this helps

**Comment by gaoshenga** [comment]
I want to request data from an interface first, judge that the return data failed, and then ask for another interface, as input. Like the following example

```
input:
  label: "test1"
  http_client:
    url: "http://172.0.0.1:8080/post"
    verb: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    rate_limit: ""
    timeout: 5s
    payload: '{name=test&telephone=12345678901&passworld=12345678}'
  processors:
    - mapping: |
        root.data = if this.num > 15 {
          this.num
        } else {
          // Request another http_client as the input data
          // this.data
        }
output:
  stdout:
    codec: lines
```
