### ISSUE TITLE
`while` processor ignores a preceding `split` processor

### ISSUE THREAD

**Issue by mihaitodor** [benthosdev/benthos#1861]
The following config:

```yaml
input:
  generate:
    mapping: root = ""
    interval: 0s
    count: 2
    batch_size: 2
  processors:
    - split:
        size: 1
    - while:
        at_least_once: true
        check: false
        processors:
          - log:
              message: In while...
          - sleep:
              duration: 1s
    - log:
        message: Outside of while...
    - sleep:
        duration: 1s
output:
  drop: {}
```

outputs these logs:

```
INFO In while...
INFO In while...
INFO Outside of while...
INFO Outside of while...
```

However, if I set `batch_size: 1`, then I get the following:

```
INFO In while...
INFO Outside of while...
INFO In while...
INFO Outside of while...
```

It looks like the `split` processor isn't able to fully break up a batch, but I'm not sure why...

**Comment by gaoshenga** [comment]
I want to request data from an interface first, judge that the return data failed, and then ask for another interface, as input. Like the following example

```
input:
  label: "test1"
  http_client:
    url: "http://172.0.0.1:8080/post"
    verb: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    rate_limit: ""
    timeout: 5s
    payload: '{name=test&telephone=12345678901&passworld=12345678}'
  processors:
    - mapping: |
        root.data = if this.num > 15 {
          this.num
        } else {
          // Request another http_client as the input data
          // this.data
        }
output:
  stdout:
    codec: lines
```
