### ISSUE TITLE
There's no blobl option currently for batch-aware structured metadata queries

### ISSUE THREAD

**Issue by mihaitodor** [benthosdev/benthos#1882]
Here's a sample config:

```yaml
input:
  generate:
    interval: 0s
    mapping: meta test = count("foo")
    count: 2
    batch_size: 2
  processors:
    - log:
        message: ${! @.test.from(-1) } - ${! meta("test").from(-1) }

output:
  drop: {}
```

It produces the following logs:
```
INFO 1 - 2                                         @service=benthos label="" path=root.input.processors.0
INFO 2 - 2                                         @service=benthos label="" path=root.input.processors.0
```

Also, if this gets addressed, I guess [the docs](https://www.benthos.dev/docs/guides/bloblang/methods#from) for this method should be updated to mention structured metadata too
