### ISSUE TITLE
Log files cannot be generated with the benthos plug-in

### ISSUE THREAD

**Issue by gaoshenga** [benthosdev/benthos#1893]
Hello, when I was using StreamBuilderConfig, I couldn't generate the log to the specified location.
```
logger:
  level: ALL
  format: json
  add_timestamp: true
  file:
    path: /benthos/logs/benthos.log
    rotate: true
```
