### ISSUE TITLE
Redis input

### ISSUE THREAD

**Issue by mfamador** [benthosdev/benthos#1898]
I've created a custom redis input to walk through the keys matching a prefix and get their values.

If it's of interest I can add it to benthos, but before I'd like to discuss a few options:

1. since there's an additional call to get the values, should we have an option to get only the keys?
2. on which format should the messages be created:
2.1. when there's keys and values, return a json message? ex. {"my_key":"a_value"} ? 
2.2. when there's only keys, the message would be only its content? ex. "my_key"?
3. Would `redis` be a good name for the input?

**Comment by mfamador** [comment]
or maybe:
`{"key": "mykey", "value":"a_value"}`
and
`{"key": "mykey"}`

**Comment by Jeffail** [comment]
I'd maybe call it `redis_scan` and use the SCAN command https://redis.io/commands/scan/ to obtain both keys and values. I think the use case for just obtaining the keys alone should be left as a processor as it's not really a pattern you'd expect to see in production pipelines.

**Comment by mfamador** [comment]
Cool, sounds good. Thanks.

**Comment by natenho** [comment]
@mfamador @Jeffail I have a use case for this input, but it would be useful to be a processor aswell: I want to delete keys based on a pattern, depending on the content of an input message.

**Comment by mfamador** [comment]
> @mfamador @Jeffail I have a use case for this input, but it would be useful to be a processor aswell: I want to delete keys based on a pattern, depending on the content of an input message.

It doesn't seem to accept wildcards, but perhaps you could use the existent `cache` processor:
```
      - cache:
          resource: cache
          operator: delete
          key: '${! cacheKey }'
```

**Comment by Jeffail** [comment]
@natenho you might be able to achieve that already as the redis processor now accepts any command with mapping based arguments: https://www.benthos.dev/docs/components/processors/redis

**Comment by natenho** [comment]
@Jeffail @mfamador it is not possible to delete multiple keys using wildcard in Redis, so there is no command to achieve that without reading existing keys. That is the reason I considered this input.

**Comment by mfamador** [comment]
As @Jeffail mentioned, perhaps you can use then the `refis` processor with the `scan` command:
```
      - redis:
          url: 'redis://localhost:6379'
          command: 'scan'
          args_mapping: 'root = [""]'
  ```

**Comment by mfamador** [comment]
Well, actually this example is not working.

**Comment by mfamador** [comment]
this one works:
```
      - redis:
          url: 'redis://localhost:6379'
          operator: 'keys'
          key: '*'
 ```
