### ISSUE TITLE
Streams mode and bloblang count()

### ISSUE THREAD

**Issue by cnelson** [benthosdev/benthos#1909]
Is there a way to reset a counter when in streams mode and a stream is deleted?  

For example:

I have `input.txt` with these contents:
```
one
two
three
```

I create a stream with:
```
curl http://localhost:4195/streams/foo -X POST --data-binary @- <<EOF
input:
  file:
    paths:
    - input.txt
    codec: lines

pipeline:
  processors:
  - bloblang: |
      root.content = content().string()
      root.id = count("lines")

output:
  file:
    path: output.txt
    codec: lines
EOF
```

I then delete it with: `curl -X DELETE http://localhost:4195/streams/foo`

I then recreate the stream again with the same POST command listed above.

What I'd expect int `output.txt`

```
{"content":"one","id":1}
{"content":"two","id":2}
{"content":"three","id":3}
{"content":"one","id":1}
{"content":"two","id":2}
{"content":"three","id":3}
```

What's actually in output.txt
```
{"content":"one","id":1}
{"content":"two","id":2}
{"content":"three","id":3}
{"content":"one","id":4}
{"content":"two","id":5}
{"content":"three","id":6}
```

Is there anyway to get a counter that only exists for the lifetime of a stream and not the benthos process?
