### ISSUE TITLE
Unable to decode AVRO message: cannot decode binary record

### ISSUE THREAD

**Issue by robinhuiser** [benthosdev/benthos#1917]
Hi,

I have build a simple Benthos config:
* **input**: read CSV file
* **processors**:
  * Bloblang - creating a JSON object from the CSV file columns (using `root.COLUMN_NAME = this.index(n)`)
  * Avro - convert `from_json` to Avro binary, based upon a local schema file
* **output**: write to kafka topic (no other configuration then `addresses` and `topic`)

Initially this seems to go really well and fast, but once I configured a consumer on the topic trying to read the message data in Avro binary format it seems the actual message data is in clear text containing the human-readable JSON object.

Config snippet:

```
pipeline:
  threads: -1
  processors:
    - label: "map_fields"
      mapping: |
        #!blobl
        root.FEEIDENTIFIER_ = this.index(0)
        root.BILLNUMBER_ = this.index(1)
        root.ACCOUNTIDENTIFIER_ = this.index(2)
        ...

    - label: "convert_to_avro"
      avro:
        operator: from_json
        encoding: binary
        schema_path: `"file://${AVRO_SCHEMA_FILE:/schema.avsc}"
```
I am using `plumber` to read the message data using:

```
plumber read kafka \
  --topics=fee_details \
  --decode-type=avro --avro-schema-file=$(PWD)/schema.avsc \
  --pretty --read-offset=0 -f
```

The error output is:

`>> ERROR: unable to decode message payload for backend 'kafka': unable to decode avro message: cannot decode binary record "com.zafin.zrpe.avro.message.output.FeeDetail" field "FEEIDENTIFIER_": cannot decode binary string: cannot decode binary bytes: negative size: -62`

 When inspecting the message visually using "Kafka Tool" I can clearly see (once the message key and value are set to decode as "string") the JSON object.

Please advice.

Thanks -- Robin
