### ISSUE TITLE
Update documentation for `try` processor and changing batch sizes

### ISSUE THREAD

**Issue by disintegrator** [benthosdev/benthos#1921]
The `try` processor can misbehave if child processors manipulate the input message batch as with the `archive` processor. This behaviour was observed in the config below:

```
input:
  generate:
    count: 100
    interval: 0
    mapping: |
      #!blobl
      root = {}
      root.id = nanoid()
      root.created_at = now()
      root.username = fake("username")
      root.phone_number = fake("phone_number")
      root.email = fake("email")
pipeline:
  processors:
    - label: generate_csv_row
      jq:
        output_raw: true
        query: |
          [
            .id,
            .created_at,
            .username,
            .phone_number,
            .email
          ] | @csv
    - catch:
        - log:
            message: ${! error() }
            level: ERROR

output:
  broker:
    pattern: fan_out
    outputs:
      - gcp_cloud_storage:
          bucket: "${BUCKET}"
          path: foo/batch-${! @batch_hash }.csv
          batching:
            count: 10
            period: 5s
            processors:
              - resource: create_csv
      - gcp_cloud_storage:
          bucket: "${BUCKET}"
          path: bar/batch-${! @batch_hash }.csv
          batching:
            count: 10
            period: 5s
            processors:
              - resource: create_csv

processor_resources:
  - label: create_csv
    try:
      - label: prepend_csv_heading
        insert_part:
          index: 0
          content: "id,created_at,username,phone_number,email"
      - label: concat_csv_rows
        archive:
          format: lines
      - label: calculate_csv_hash
        bloblang: |
          meta batch_hash = content().hash("xxhash64").encode("hex")
```

Instead of creating 10 csv files with 10 messages in `foo/` and `bar/`, this config was creating 100 csv files with 1 message each inside each of those folders. This is because `try` works like the `for_each` processor and executes the chain of processors against each individual message rather from the generated batch rather than passing in the whole batch. In other `archive` is getting one message at a time rather than a whole batch.

We should update the documentation to more explicitly describe about this behaviour since it can be a source of confusion particularly when it used as part of batch processing.
