### ISSUE TITLE
Environment variables in tests

### ISSUE THREAD

**Issue by nevesb** [benthosdev/benthos#1926]
### Discussed in https://github.com/benthosdev/benthos/discussions/1924

<div type='discussions-op-text'>

<sup>Originally posted by **nevesb** May 24, 2023</sup>
Hello, I started using bethos a while ago and now I'm passing some parameters through environment variables. So for example I have this code snippet in my config:
```yaml
input:
  http_client:
    url: ${my_url_with_token}
    verb: GET
  processors:
    - noop: {}
```

When I run my tests now the following error message appears:

```
Test 'config.yaml' failed

Failures:

--- config.yaml ---

Lint: (1,1) required environment variables were not set: [my_url_with_token]
```

I tried to run configure my environment variable in several ways, for example:

```yaml
tests:
  - name: input tokens
    target_processors: '/input/processors'
    environment:
        my_url_with_token: http://dummyurl.com/
```

But no way i put it, it accepts my variable. I think I'm using this field incorrectly. How should I put this?</div>
