### ISSUE TITLE
Implementing a "fire and forget" behavior

### ISSUE THREAD

**Issue by natenho** [benthosdev/benthos#1946]
Hello, I have a situation where an HTTP benthos stream receives a  message and should send a sync response as soon as the pipeline was succeeded. Then it should forward the message to an output http server without caring about the response (although it should keep indefinitely trying in background). Then I came up with the folowing:

I've created 2 streams:

The main.yml stream:
```
input:
  http_server:
    sync_response:
      status: "200"
      headers:
        Content-Type: application/json
pipeline:
  processors:
    - label: some_very_important_processing
      noop: {}

output:
  broker:
    pattern: fan_out
    outputs:
      - sync_response: {}
      - inproc: fire_forget
```

The fire_forget.yml stream:

```
input:
  inproc: fire_forget
buffer:
  memory:
    batch_policy:
      enabled: true
      count: 1
output:
  http_client:
    url: "http://popcorn/some-expensive-endpoint"
    verb: POST
```

The second stream is a buffered inproc that works as an async output.

This solution appears to be an elegant approach to solve the problem, and I would like to share it for others to benefit from it as well (or maybe suggest it to be part of inproc input/output docs). Additionally, I would appreciate any further suggestions or alternative approaches that anyone may have.
