### ISSUE TITLE
Different behavior in JSON environment variable parsing during testing vs. linting

### ISSUE THREAD

**Issue by natenho** [benthosdev/benthos#1965]
Given the files:

.env
```
MY_JSON="[{ \"id\": 1234 }]"
```

benthos_benthos_test.yml
```
tests:
  - name: dummy
    target_processors: "/input/processors"
    environment:
      MY_JSON: '[{ \"id\": 1234 }]'
    input_batch:
      - content: ""
    output_batches:
      - - json_equals: [{ "id": 1234 }]
```

benthos.yml
```
input:
  generate:
    count: 1
    interval: ""
    mapping: |
      root = ""
  processors:
    - mapping: |
        root = "${MY_JSON}".parse_json()
```

# Scenario 1

When I run test
```
$ benthos test ./...
Test 'benthos.yml' succeeded
```

But when I run lint
```
$ benthos -e .env lint ./... && echo succeeded
benthos.yml(9,29) line 1 char 13: expected line break
  |
1 | root = "[{ "id": 1234 }]".parse_json()
  |             ^---
```

# Scenario 2

Changing benthos.yml to
```
input:
  generate:
    count: 1
    interval: ""
    mapping: |
      root = ""
  processors:
    - mapping: |
        root = ${MY_JSON}
```

When I run test:
```
$ benthos test ./...
Failed to execute test target 'benthos.yml': test case 0 failed: failed to initialise processors '/input/processors': failed to initialise processor index '0': failed to init processor <no label>: failed to parse bloblang mapping '': expected query, got: \"id\
```

But when I run lint:
```
$ benthos -e .env lint ./... && echo succeeded
succeeded
```
