### ISSUE TITLE
How to return count of total success as single response to http server

### ISSUE THREAD

**Issue by sananguliyev** [benthosdev/benthos#1973]
Hi, I have a use case that I receive input which has a array field. I split it and emit to kafka. 

Sample input: 
```
{"codes": ["aaa", "bbb"]}
```

Configuration:
```
input:
  http_server:
    address: ":18080"
    allowed_verbs:
      - POST
      - OPTIONS
    # cors:
    #   enabled: true
    #   allowed_origins: ["*"]
    sync_response:
      status: "200"
      headers:
        Content-Type: application/json
        access-control-allow-origin: "*"
        access-control-allow-methods: "*"
        access-control-allow-headers: "*"


pipeline:
  processors:
    - switch:
      - check: meta("http_server_verb").uppercase() == "POST"
        processors:
          - mapping: |
              root = this.codes
          - unarchive:
              format: json_array
          - type: split
          - bloblang: 'root = this.trim("\"")'
  
output:
  switch:
    cases:
      - check: meta("http_server_verb").uppercase() == "POST"
        output:
          broker:
            pattern: fan_out
            outputs:
              - kafka:
                  addresses:
                    - localhost:9092
                  topic: test_topic
              - sync_response: {}

      - output:
          broker:
            pattern: fan_out
            outputs:
              - stdout:
                  codec: lines
              - sync_response: {}
```

**Extra question:** As you also see cors commented out because it does not work as expected and I use hardcoded headers to achieve it.

Expected output:
```
{"status":"ok", "success_count": 2}
```

Is this possible to do this? If yes, how? 

Thanks in advance.

**Comment by sananguliyev** [comment]
And as you see I used a lot of `switch` because there is React UI which needs to make `OPTIONS` request and I need to skip them. Is there any other way to just skip the whole pipeline in case condition met?

**Comment by Jeffail** [comment]
Hey @sananguliyev, the sync_response body is limited to the raw contents of the sync_response data, in order to mutate the response body _after_ all the output destinations are resolved we'd need some form of post-response bloblang mapping.

However, the `sync_response.headers` map is something that can be set with interpolation functions that are resolved _after_ the outputs are resolved. This means you can do stuff like:

```

**Comment by Jeffail** [comment]
Sorry didn't mean to close the issue

**Comment by sananguliyev** [comment]
Firstly, thanks for the quick reply. Success count in the header is something works for me. I can continue with that. 

But the other solution deleting root does not work:
`- mapping: 'root = if meta("http_server_verb").uppercase() == "OPTIONS" { deleted() }'`

If I delete root the pipeline does not continue and due to that reason it does not return a response to the browser which means that I do not get CORS related header, and it causes CORS issue on the browser.
```
access-control-allow-origin: "*"
access-control-allow-methods: "*"
access-control-allow-headers: "*"
 ```
 
 And at the same time I did not find the reason why 
 ```
      cors:
       enabled: true
       allowed_origins: ["*"]
 ```
 does not work. The reason I have added hard-coded sync response was CORS.

**Comment by Jeffail** [comment]
Ah yes you'll need to trigger a sync response before deleting, maybe do something like this:

```
pipeline:
  processors:
    - switch:
      - check: meta("http_server_verb").uppercase() == "POST"
        processors:
          - mapping: |
              root = this.codes
          - unarchive:
              format: json_array
          - split: {}
          - mapping: 'root = this.trim("\"")'
      - check: meta("http_server_verb").uppercase() == "OPTIONS"
        processors:
          - sync_response: {} # ensures a sync response is triggered
          - mapping: 'root = deleted()'
```

For the CORS issues it sounds like that's a bug relating to sync responses on the http_server input, can you open a separate issue for that?
