### ISSUE TITLE
[Bug] Upsert setting does't work for mongodb output plugin

### ISSUE THREAD

**Issue by EverGreen5455** [benthosdev/benthos#1984]
`upsert` setting is always false
```yaml
# Config example
output:
  mongodb:
    ...
    operation: replace-one
    upsert: true
    ...
```

https://github.com/benthosdev/benthos/blob/5225e1a58a1bf102e05d6285e62df24591fb757e/internal/impl/mongodb/common.go#L337-L341

Affected version: >=4.17.0
