### ISSUE TITLE
sql_insert output not compatible with Postgres array columns

### ISSUE THREAD

**Issue by mihaitodor** [benthosdev/benthos#1987]
If you run this config:

```yaml
input:
  generate:
    count: 1
    interval: 0s
    mapping: |
      root.arr = ["2"]

output:
  sql_insert:
    driver: postgres
    dsn: postgres://testuser:testpass@localhost:5432/testdb?sslmode=disable
    table: FOOBAR
    columns: [arr]
    args_mapping: root = [this.arr]
    init_statement: |
      CREATE TABLE IF NOT EXISTS FOOBAR (
        arr text[]
      );

shutdown_timeout: 2s
```

it will fail with the following error:

```
Failed to send message to sql_insert: sql: converting argument $1 type: unsupported type []interface {}, a slice of interface
```

This is due to Postgres requiring that array args are wrapped using `pq.Array()` before being sent to the sql driver as a query argument. However, this is Postgres-specific and I don't think it would be a good approach to sprinkle the Benthos codebase with such driver-specific args wrappers and maybe there's some generic way in the library that's used under the hood to build the query, but that will require some investigation...

As a workaround, one can use the `sql_raw` output and either use one of the custom JSON -> Array conversion functions described [here](https://dba.stackexchange.com/questions/54283/how-to-turn-json-array-into-postgres-array) or craft the entire sql string manually and set `unsafe_dynamic_query: true`. Not the best workaround, but it should do the trick...
