### ISSUE TITLE
Consider setting a default reader codec for decompression codecs

### ISSUE THREAD

**Issue by mihaitodor** [benthosdev/benthos#1998]
The following config:

```yaml
# tar -czvf test.tar.gz ./test.txt
input:
  file:
    paths: ["./test.tar.gz"]
    codec: gzip

output:
  stdout: {}
```
will fail with error "codec was not recognised: [gzip]" and users will have to figure out that they need to use something like `codec: gzip/all-bytes` instead.

I think it might be worth considering setting `all-bytes` as the default part reader if an io reader is present, or at least making the error message more informative
