### ISSUE TITLE
is it possible to create pipeline on azure blob storage account for blob file ?

### ISSUE THREAD

**Issue by Ravi733499** [benthosdev/benthos#2005]
looking for a way to read the file from azure blob storage and push it to snowflake database whenever any new file gets landed in azure blob storage container.

**Comment by mihaitodor** [comment]
Hey! 👋 If you're happy to delete the files from Azure Blob Storage once they've been uploaded and it's not a huge issue to keep polling it for new files every `interval`, then here's a potential solution:

```yaml
input:
  read_until:
    # Keep reading in a loop
    check: false
    restart_input: true
    input:
      sequence:
        inputs:
          - generate:
              mapping: root = ""
              # Specify how frequently you'd like to poll Blob Storage for new
              # files
              interval: 5s
              # Need to emit 2 messages so the configured `interval` lapses once
              # because the first message is emitted immediately
              count: 2
            processors:
              # Get rid of the messages generated by this input, since we don't
              # need them
              - mapping: root = deleted()

          - azure_blob_storage:
              # Delete the read file once it's processed so it won't get picked
              # up during the next iteration
              delete_objects: true
              # TODO

output:
  snowflake_put:
    # TODO
```

A better solution would be to have support for [Event Grid](https://learn.microsoft.com/en-us/azure/event-grid/overview) in the `azure_blob_storage` input similar to the SQS integration in `aws_s3`, but it requires some investigation. PRs are welcome.
