### ISSUE TITLE
Add support for open telemetry metrics

### ISSUE THREAD

**Issue by charlie-haley** [benthosdev/benthos#2007]
[Benthos currently supports OTEL traces ](https://github.com/benthosdev/benthos/issues/1343) but not metrics. We should add support for metrics so Benthos is compatible with the entire Open Telemetry offering.

We can follow the config implementation for traces:
```
metrics:
  open_telemetry_collector:
    http: [] # No default (required)
    grpc: [] # No default (required)
```

If there's no concerns, I can get a PR together
