### ISSUE TITLE
Benthos linter ignores yaml anchors in resources when the file is passed in via the `-r` flag

### ISSUE THREAD

**Issue by mihaitodor** [benthosdev/benthos#2016]
- `res.yaml`
```yaml
input_resources:
  - label: base
    generate: &base
      foo: bar
      count: 1
      interval: 0s
      mapping: root.foo = "bar"
  - label: gen
    generate: *base
```

- `conf.yaml`
```yaml
input:
  resource: gen

output:
  stdout: {}
```

Running `benthos -r res.yaml -c conf.yaml lint` doesn't emit any linter errors, while `benthos lint res.yaml` prints "res.yaml(4,1) field foo not recognised"
