### ISSUE TITLE
Input multiple data sources and output after conversion

### ISSUE THREAD

**Issue by gaoshenga** [benthosdev/benthos#2023]
I want to use benthos to read data from table A and table B in the mysql database, the data in the two tables with id as the foreign key, and then connect the two data within the output to the json file, how to write the yml file?

**Comment by mihaitodor** [comment]
Hey @gaoshenga, sounds like you might want to express a SQL `SELECT ... FROM A INNER JOIN B ON ...` query using the `sql_raw` input. Then you can use the `file` output to write the messages to a file (you'll probably want to use `codec: lines`). If the output json file needs to contain an actual JSON array, then the following hack using the sequence input might suit:

```yaml
input:
  sequence:
    inputs:
      - sql_raw:
          # TODO
      - generate:
          count: 1
          interval: 0s
          mapping: |
            meta done = true
output:
  file:
    path: ./output.json
    codec: append
  processors:
    - mapping: |
        root = if count("messages") == 1 { "[" + content() } else {
          if @done == true { content() + "]" } else { "," + content() }
        }
```

**Comment by gaoshenga** [comment]
If two data sources, one is from pg database table A and the other is from mysql database table B, and both tables use id as the foreign key, how to find the internal or external connection of the data, and how to write benthos's yml?

**Comment by mihaitodor** [comment]
> If two data sources, one is from pg database table A and the other is from mysql database table B, and both tables use id as the foreign key, how to find the internal or external connection of the data, and how to write benthos's yml?

Sounds like you wish to do a join between these two tables... In that case, I guess you can use a `sequence` input like I demoed above, but the first input will be a `sql_select` for Postgres which will have some processors attached to store the data it retrieves into a cache and then do `mapping: root = deleted()` so these messages don't reach the output. Then, the second input will be another `sql_select` for MySQL, which will have some processors attached to query the cache for the foreign key of each message to enrich them. Then the enriched messages can flow to the output.

> and how to write benthos's yml?

I encourage you to give it a shot, but, if you need more detailed support, please see the support options listed [here](https://www.benthos.dev/support).

**Comment by gaoshenga** [comment]
```
input:
  broker:
    inputs:    
      - label: aa
        sequence:
          sharded_join:
            type: outer
            id_path: id
            iterations: 10
            merge_strategy: replace
          inputs:
            - label: sql2
              sql_raw:
                driver: postgres
                dsn: postgres://foouser:foopass@localhost:5432/testdb?sslmode=disable
                query: "SELECT name, count(*) FROM person WHERE last_updated < $1 GROUP BY name;"  
            - label: sql
              sql_raw:
                driver: mysql
                dsn: root:123456@tcp(192.168.146.100:3306)/go_gin_api
                query: SELECT id,name,level FROM menu;
        processors:
          - label: maping
            mapping: root.data = if this.length() == 5 { this } else { deleted()}


pipeline:
  processors:  
    - label: mapping1
      mapping: |
        root.mapping = {"1_tag1":"ns121","1_tag2":"ns122","1_tag3":"ns123","1_tag4":"ns124"}
        root.result = this.data


output:
  broker:
    outputs:
      - file:
          path: /usr/local/hsm-os/data/hsm-io-it/data/benthos/temp/job_bkglqgrj.json
      - label: stdout
        stdout: {}
```
I found that I could not get the data in the input sequence in the pipeline.

```
pipeline:
  processors:  
    - label: mapping1
      mapping: |
        root.mapping = {"1_tag1":"ns121","1_tag2":"ns122","1_tag3":"ns123","1_tag4":"ns124"}
        root.result = this.data
```
