### ISSUE TITLE
send on closed channel

### ISSUE THREAD

**Issue by qingchr** [benthosdev/benthos#2071]
In stream mode, components are configured as resources.
When data flows through a component, a panic occurs when the HTTP REST API is used to update the resource configuration.

**Comment by qingchr** [comment]
版本 v4.18.0

**Comment by qingchr** [comment]
panic: send on closed channel

goroutine 59 [running]:
github.com/benthosdev/benthos/v4/internal/manager.(*outputWrapper).WriteTransaction(0x10?, {0x2fa13b0?, 0xc000677540?}, {{0xc001f5cdd0, 0x1, 0x1}, 0xc00246f800, 0x0, {0x2fa13e8, 0xc000126000}})
        github.com/benthosdev/benthos/v4/internal/manager/output_wrapper.go:33 +0xc5
github.com/benthosdev/benthos/v4/internal/impl/pure.(*resourceOutput).loop.func2({0x2fa82c0?, 0xc00141a480?})
        github.com/benthosdev/benthos/v4/internal/impl/pure/output_resource.go:114 +0xad
github.com/benthosdev/benthos/v4/internal/manager.(*Type).AccessOutput(0xc001494f18?, {0xc001494eb0?, 0xc001494f38?}, {0xc0014499b0, 0x16}, 0xc001005f20)
        github.com/benthosdev/benthos/v4/internal/manager/type.go:743 +0xec
github.com/benthosdev/benthos/v4/internal/impl/pure.(*resourceOutput).loop(0xc001168dc0)
        /github.com/benthosdev/benthos/v4/internal/impl/pure/output_resource.go:113 +0x2ef
created by github.com/benthosdev/benthos/v4/internal/impl/pure.(*resourceOutput).Consume
        github.com/benthosdev/benthos/v4/internal/impl/pure/output_resource.go:136 +0x79

**Comment by Jeffail** [comment]
Hey @qingchr, thanks for raising this, fix should be fairly straight forward so I'll aim to get it out today, out of interest is this with a custom build of benthos or the standard one?

**Comment by qingchr** [comment]
Hey @Jeffail this  is a custom build of benthos.

And there's another problem here.

When there is a lot of data flowing through the resource, using the HTTP REST API to update the resource with a relatively high frequency, deadlock will occasionally occur and the flow will be blocked.

After my investigation, the deadlock also occurs in this code:

```
func (w *outputWrapper) WriteTransaction(ctx context.Context, t message.Transaction) error {
	select {
	case w.tranChan <- t:
	case <-ctx.Done():
		return component.ErrTimeout
	}
	return nil
}
```


Forgive me for my limited skill set. This is as far as I can go.

This problem occurred when I was using version 4.6.0.

However, in version 4.18.0, when I used recover() to catch the above mentioned panic, I tested it again and still encountered the deadlock.

**Comment by Jeffail** [comment]
@qingchr, the panic should be fixed with: https://github.com/benthosdev/benthos/commit/c6bf287f6936580b1212feb0c27f711221058f66

There's definitely a case where recovering from that fixed panic would've caused a deadlock but it can't say for sure that this will fix it without a full stack trace. Let me know if you still see any deadlocks and I'll take another look.

**Comment by qingchr** [comment]
@Jeffail  The deadlock situation appears again. Now, let me talk about the steps to repeat the problem.
## Version used

```
[root@test test]# benthos -version
Version: 4.20.0
Date: 2023-08-22T20:31:39Z
```

## configuration

### config.yaml

```
http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: /benthos
  debug_endpoints: true
  cert_file: ""
  key_file: ""
  cors:
    enabled: false
    allowed_origins: []
  basic_auth:
    enabled: false
    realm: restricted
    username: ""
    password_hash: ""
    algorithm: sha256
    salt: ""


logger:
  level: INFO
  format: json
  add_timestamp: true
  timestamp_name: time
  message_name: msg
  static_fields:
    '@service': goms
  file:
    path: ""
    rotate: false
    rotate_max_age_days: 0
```

### resources.yaml

```
input_resources:
  - label: input_resource_nanomsg
    nanomsg:
      urls:
        - tcp://0.0.0.0:12345
      bind: true
      socket_type: SUB
      sub_filters: ['']

output_resources:
  - label: "output_resource_broker"
    broker:
      pattern: fan_out
      outputs:
          - resource: output_resource_stdout
          - resource: output_resource_drop
  - label: "output_resource_stdout"
    stdout: {}
  - label: "output_resource_drop"
    drop: {}

processor_resources:
  - label: "processor_resource_bloblang"
    bloblang: |
        root.count = count("aaaaaaa")
```


### stream.yaml

```
input:
  resource: input_resource_nanomsg

pipeline:
  processors:
    - resource: processor_resource_bloblang
output:
   resource: output_resource_broker

```

## Start benthos

```
[root@test test]# benthos -c config.yaml -r resources.yaml streams stream.yaml
{"@service":"goms","level":"info","msg":"Running main config from specified file","path":"config.yaml","time":"2023-09-04T14:34:00+08:00"}
{"@service":"goms","label":"output_resource_drop","level":"info","msg":"Dropping messages.","path":"root.output_resources","time":"2023-09-04T14:34:01+08:00"}
{"@service":"goms","level":"info","msg":"Listening for HTTP requests at: http://0.0.0.0:4195","time":"2023-09-04T14:34:01+08:00"}
{"@service":"goms","level":"info","msg":"Launching benthos in streams mode, use CTRL+C to close","time":"2023-09-04T14:34:01+08:00"}
{"@service":"goms","label":"input_resource_nanomsg","level":"info","msg":"Receiving Scalability Protocols messages at bound URLs: [tcp://0.0.0.0:12345]","path":"root.input_resources","time":"2023-09-04T14:34:01+08:00"}
```

## Send data to benthos

Use the following code，run `go run main.go`  to start sending data.

```
package main

import (
	"fmt"

	"go.nanomsg.org/mangos/v3/protocol/pub"

	// register transports
	_ "go.nanomsg.org/mangos/v3/transport/all"
)

func main() {

	socket, err := pub.NewSocket()
	if err != nil {
		fmt.Println(err.Error())
		return
	}
	defer socket.Close()

	if err := socket.Dial("tcp://0.0.0.0:12345"); err != nil {
		fmt.Println(err.Error())
		return
	}
	for {
		if err := socket.Send([]byte(`{}`)); err != nil {
			fmt.Println(err.Error())
			continue
		}
	}
}

```

## Update resource

Use the following script，run `watch -n 0.1 ./update.sh` to update the resource configuration frequently.

```
[root@test test]# cat update.sh
#!/bin/bash

curl -X POST \
     http://0.0.0.0:4195/resources/processor/processor_resource_bloblang \
     -H "Content-Type:application/json" \
     -d '{
                "label":"processor_resource_bloblang",
                "bloblang": "root.count = count(\"aaa\")"
        }'

```

## Finally
In my practice, sending data while updating the resource, soon the data flow will get stuck. 
It should be less than a minute.
You can try.
