### ISSUE TITLE
http_server returns unexpected 404 responses during shutdown

### ISSUE THREAD

**Issue by jojotl** [benthosdev/benthos#2080]
We are using the `http_server` input component to run an HTTP API service. We recently noticed that this service started to return intermittent 404 responses during deployments.

Our tests showed that these 404 errors are returned from benthos for a short period of time after the shutdown procedure of an instance is initiated via `SIGTERM`. 

The issue can be easily reproduced by using the stream config below and some load testing tool like bombardier. 

test.yaml

```
input:
  http_server:
    address: ""
    path: /
    allowed_verbs:
      - GET
    sync_response:
      status: 200

pipeline:
  threads: 1
  processors:
    - sleep:
        duration: 40ms
    - bloblang: |
        root = "OK"

output:
  label: ""
  sync_response: {}

```

Triggering a shutdown during a test run will give you a result like the following:

> bombardier -c 2 -n 100000 http://localhost:4195/test
> Bombarding http://localhost:4195/test with 1000000 request(s) using 2 connection(s)
> ...
> Done!
> Statistics        Avg      Stdev        Max
>   Reqs/sec      3947.29    4729.16   11721.15
>   Latency      507.49us     5.12ms    86.79ms
>   HTTP codes:
>     1xx - 0, 2xx - 77, 3xx - 0, **4xx - 90**, 5xx - 1
>     others - 19158
>   Errors:
>     dial tcp [::1]:4195: connect: connection refused - 19158
>   Throughput:     7.19KB/s
> 
> 

It looks like the issue is caused by the changes in v4.14.0. Running the same tests with v4.13.0 doesn't show any 404 responses:

> bombardier -c 2 -n 100000 http://localhost:4195/test
> Bombarding http://localhost:4195/test with 1000000 request(s) using 2 connection(s)
> ...
> Done!
> Statistics        Avg      Stdev        Max
>   Reqs/sec      3184.19    4568.16   11691.99
>   Latency      629.40us     5.95ms    86.29ms
>   HTTP codes:
>     1xx - 0, 2xx - 122, 3xx - 0, **4xx - 0**, 5xx - 1
>     others - 22450
>   Errors:
>     dial tcp [::1]:4195: connect: connection refused - 22450
>   Throughput:     3.10KB/s
