### ISSUE TITLE
sftp output does not recover from connection lost

### ISSUE THREAD

**Issue by daniel-anova** [benthosdev/benthos#2083]
Using benthos as a report generator to sftp servers.

Reports can take a few minutes to generate and the destination sftp is on [Azure Storage that has a 2m idle timeout](https://learn.microsoft.com/en-us/azure/storage/blobs/secure-file-transfer-protocol-known-issues#networking).

This means by the time the processing ends the output fails with `ERRO Failed to send message to sftp: connection lost` and will not recover.

Example configuration that reproduces the issue:

```yaml
http:
  address: 0.0.0.0:4195
  debug_endpoints: false

input:
  file:
    paths:
    - /home/df/source/snipets/benthos/sample.txt
    codec: all-bytes

pipeline:
  processors:
    - sleep:
        duration: "3m" 

output:
  sftp:
    address: "<redacted>.blob.core.windows.net:22"
    path: "/sample.txt"
    codec: all-bytes
    credentials:
      username: "<redacted>.test"
      password: "<redacted>"

logger:
  level: TRACE
  static_fields:
    '@service': sftp-timeout

shutdown_timeout: 20s
```

```log
❯ benthos -v
Version: 4.20.0
Date: 2023-08-22T17:05:15Z
❯ benthos -c sftp-timeout.yaml
INFO Running main config from specified file       @service=sftp-timeout path=sftp-timeout.yaml
INFO Listening for HTTP requests at: http://0.0.0.0:4195  @service=sftp-timeout
INFO Launching a benthos instance, use CTRL+C to close  @service=sftp-timeout
INFO Consuming from file '/home/df/source/snipets/benthos/sample.txt'  @service=sftp-timeout label="" path=root.input
TRAC Consumed 1 messages from 'file'.              @service=sftp-timeout label="" path=root.input
TRAC Attempting to write 1 messages to 'sftp'.     @service=sftp-timeout label="" path=root.output
ERRO Failed to send message to sftp: connection lost  @service=sftp-timeout label="" path=root.output
TRAC Consumed 1 messages from 'file'.              @service=sftp-timeout label="" path=root.input
TRAC Attempting to write 1 messages to 'sftp'.     @service=sftp-timeout label="" path=root.output
ERRO Failed to send message to sftp: connection lost  @service=sftp-timeout label="" path=root.output
TRAC Consumed 1 messages from 'file'.              @service=sftp-timeout label="" path=root.input
TRAC Attempting to write 1 messages to 'sftp'.     @service=sftp-timeout label="" path=root.output
ERRO Failed to send message to sftp: connection lost  @service=sftp-timeout label="" path=root.output
TRAC Consumed 1 messages from 'file'.              @service=sftp-timeout label="" path=root.input
TRAC Attempting to write 1 messages to 'sftp'.     @service=sftp-timeout label="" path=root.output
ERRO Failed to send message to sftp: connection lost  @service=sftp-timeout label="" path=root.output
TRAC Consumed 1 messages from 'file'.              @service=sftp-timeout label="" path=root.input
```

The output should be able to reconnect to the sftp server.
