### ISSUE TITLE
http processor Bearer Authentication support

### ISSUE THREAD

**Issue by ppawelzak** [benthosdev/benthos#2086]
Hi, could you please add Bearer Authentication support to [http processor](https://www.benthos.dev/docs/components/processors/http/)?

**Comment by mihaitodor** [comment]
@ppawelzak Not sure what you're looking for, but I believe that already works:
```yaml
- http:
     ...
     headers:
       Authorization: "Bearer <your token>"
```
