### ISSUE TITLE
Tracer not recognized in streams

### ISSUE THREAD

**Issue by sananguliyev** [benthosdev/benthos#2103]
Hi,

First of all thanks for quick review and approval of secure mode of open telemetry connector. I was trying to use tracer in streams mode but get an error `"lint":"test.yml(16,1) field tracer not recognised"` when I run `benthos streams test.yml`

Content of `test.yml` file:

```
input:
  http_server: 
    address: 0.0.0.0:8080
    path: /some-endpoint
    allowed_verbs:
      - POST  
    sync_response:
      status: 200
      headers:
        Content-Type: application/json

output:
  sync_response: {}


tracer:
  open_telemetry_collector:
    http:
      - url: "some-collector:4318"
        secure: true
```
