### ISSUE TITLE
Logger destination may be inconsistent - suggestion for a new Logger configuration field

### ISSUE THREAD

**Issue by krazylek** [benthosdev/benthos#2156]
The documentation specifies that 
> Benthos logging prints to stdout (or stderr if your output is stdout) 

Unfortunately this doesn't work if the output uses a `switch`.
Even if the selected case condition is `stdout` output.

To reproduce:

```yml
input:
  generate:
    mapping: |
      root.id = count("foo_counter1")
    interval: 0s
    count: 3

output:
  switch:
    cases:
      - check: false
      - output:
          stdout:
            codec: lines
```

Also, considering the `Logger` doc:
> Use these configuration options to change both the logging formats as well as the destination of logs.

A way of solving this issue could be to "force" the destination with a new field (`destination`? `write_to`?) in the Logger configuration.

Without too much reflection (especially about the `file` output), it could look to something like this:

```yml
logger:
  level: INFO
  format: logfmt
  write_to: stderr # stdout | stderr | file?
```
