### ISSUE TITLE
TCP Retransmission when use http processor

### ISSUE THREAD

**Issue by BugsGuru** [benthosdev/benthos#2180]
Here is the main benthos config:
```yaml
pipeline:
  threads: 8
  processors:
    - try:
      - branch:
          request_map: |
            root = {
              # unimportant
            }
          processors:
            - http:
                url: http://192.168.0.47:20000/api/v1/termapp
          result_map: |
            root.app = this.app
            root.term = this.term
    - label: "catch"
      catch:
        - log:
            message: "Processing failed due to: ${!error()} msg: ${! content()}"
        - mapping: deleted()
```

Here is the pcap in Wireshark :
- tcp.stream in even number are all like this:
     ![image](https://github.com/benthosdev/benthos/assets/53931124/00bc755d-507b-46ee-959f-be6420bbd26e)
- odd  number:
     ![image](https://github.com/benthosdev/benthos/assets/53931124/80ccfb92-2d32-40a5-9d76-edbb988e2f13)

If the information is incomplete, I would be happy to provide more. 
THANKS!
