### ISSUE TITLE
http_client sebsequent GET requests send unexpected body

### ISSUE THREAD

**Issue by tired-engineer** [benthosdev/benthos#2191]
Trying to make Benthos do a trivial thing for the second day, I guess I might have found the possible culprit[^1], but wanted to check first if it is an intended behavior:
HTTP Client input with an attempted pagination (in future, right now that's just the same request every iteration) succeeds the first time and fails on any subsequent request to some servers[^2]. Looks like these servers take GET requests too seriously and return 400 if there is a body present. And the code, responsible for the interpolation, which is/was intended for the pagination I want to use, just copies the body[^3], if I understand correctly.

I tried workarounds with various payloads[^4] ("", "${! content().string() }") to override that behavior, but everything I found produces some content and even non-zero Content-Length makes these servers go 400.

Is there a way to satisfy these servers by sending GET requests with Content-Length: 0 and without body?

Benthos version: 4.22.0.
Config file:
```yaml
input:
  http_client:
    url: http://localhost:8000/test.json
    verb: GET
    rate_limit: ct_rate_limit
    dump_request_log_level: TRACE
    drop_empty_bodies: true
    payload: ""

pipeline:
  processors:
    - label: "no"
      noop: {}

output:
  label: ""
  drop: {}
logger:
  level: TRACE
  format: logfmt
```

Tcpdump to local server:
```
GET /test.json HTTP/1.1
Host: localhost:8000
User-Agent: Go-http-client/1.1
Content-Type: application/octet-stream
Accept-Encoding: gzip


HTTP/1.0 200 OK
Server: SimpleHTTP/0.6 Python/3.11.6
Date: Fri, 27 Oct 2023 21:11:22 GMT
Content-type: application/json
Content-Length: 13761
Last-Modified: Thu, 26 Oct 2023 18:42:59 GMT

<Content>


GET /test.json HTTP/1.1
Host: localhost:8000
User-Agent: Go-http-client/1.1
Content-Length: 13761
Content-Type: application/octet-stream
Accept-Encoding: gzip

<Content>
```

[^1]: https://github.com/benthosdev/benthos/blob/9820711f2832637581996469fe64367c1bd5e583/internal/httpclient/request.go#L176
[^2]: https://ct.googleapis.com/logs/solera2018/ct/v1/get-entries?start=0&end=1&limit=1
[^3]: https://github.com/benthosdev/benthos/blob/9820711f2832637581996469fe64367c1bd5e583/internal/httpclient/request.go#L176
[^4]: https://github.com/benthosdev/benthos/blob/9820711f2832637581996469fe64367c1bd5e583/internal/httpclient/request.go#L158
