### ISSUE TITLE
Unable to start benthos with kafka output in 4.23.0

### ISSUE THREAD

**Issue by fredrikwangberg** [benthosdev/benthos#2199]
Hi, 

I have an issue where I fail to start a `4.23.0` benthos that uses the `kafka` output, see error message below.

```json
{"@service":"benthos","level":"error","msg":"Service closing due to: failed to init output 'my_output' path root.output: kafka: client has run out of available brokers to talk to: 3 errors occurred:\n\t* unexpected EOF\n\t* unexpected EOF\n\t* unexpected EOF\n"}
```

The same configuration works in version `4.22.0`. For reference, the kafka cluster version is `2.8.1`.

This is output part of the benthos configuration:

```yaml
output:
  label: "my_output"
  kafka:
    addresses:
      - b-1.redacted.eu-west-1.amazonaws.com:9094,b-2.redacted.eu-west-1.amazonaws.com:9094,b-3.redacted.amazonaws.com:9094
    topic: my_topic
    client_id: "my_client"
    tls:
      enabled: true
      root_cas_file: /path/cacert.crt
      skip_cert_verify: true
      client_certs:
        - cert_file: /path/client.crt
          key_file: /path/client.key
```

I have tried splitting the `addresses` myself into a itemized list (a `-` and newline for every broker), but with the same result. I do not know how to investigate this further, but I am keen to provide more details about the environment/deployment or to try out other ideas that potentially could generate more insights on why the error occurs.

Fredrik
