### ISSUE TITLE
Update read_until to close the input after an idle timeout

### ISSUE THREAD

**Issue by eduardodbr** [benthosdev/benthos#2249]
`read_until` closes the input once a consumed message passes a specific condition based on a query. Here I propose a new field `idle_timeout` that specifies the maximum amount of time without receiving new messages after which the input is closed.

```
input:
  label: ""
  read_until:
    input: null
    check: ""
    restart_input: false
    idle_timeout: "5s"
```

The configuration of 'check' and 'idle_timeout' could be used either independently or collectively, resulting in the termination of the input upon the first occurrence.
