### ISSUE TITLE
Kafka franz returns ready OK even when it can't connect

### ISSUE THREAD

**Issue by pedrovsg** [benthosdev/benthos#2272]
Example code 

`input:
  kafka_franz:
    seed_brokers: [ "localhost:6666" ]
    topics: [ "foobar" ]
    consumer_group: "benthos"
`
ready endpoint returns OK

App dies with sigterm after a few secods

**Comment by mihaitodor** [comment]
Steps to reproduce:

- Run Benthos with this config:

```yaml
input:
  kafka_franz:
    seed_brokers: [ "localhost:6666" ]
    topics: [ "foobar" ]
    consumer_group: "benthos"
```

- Run `curl -v http://localhost:4195/ready` and you'll get status 200.
