### ISSUE TITLE
Input pointing to resource has no metric label

### ISSUE THREAD

**Issue by marshauf** [benthosdev/benthos#2284]
Streams with an input pointing to a resources have no metric label.

The following generates metrics with a label:
```yaml
input:
  label: abc
  sftp: {}
```

The following does not generates metrics with a label:
```yaml
input:
  resource: "ftp"

input_resources:
  - label: ftp
    sftp: {}
```

Adding a label besides the pointer to the resources like
```yaml
input:
  label: "ftp"
  resource: "ftp"

input_resources:
  - label: ftp
    sftp: {}
``` 
results in `label field should be omitted when pointing to a resource` error.

It would be nice to set a label or the metric uses the resource label as a metric label value.
