### ISSUE TITLE
Assigning to metadata using the @-syntax in `branch` processor's `result_map` yields `null`

### ISSUE THREAD

**Issue by torfjor** [benthosdev/benthos#2293]
This works:

```yaml
logger:
  level: fatal
input:
  generate:
    mapping: root = {}
    count: 1
pipeline:
  processors:
    - branch:
        processors:
          - http:
              url: https://www.google.com/does-not-exist
          - catch: []
        result_map: meta http_status_code = meta("http_status_code")
    - mapping: root.http_status_code = @http_status_code
output:
  stdout:
    codec: lines
```

```sh
$ benthos -c pipeline.yaml
{"http_status_code":"404"}
```

Whereas this does not:
```yaml
logger:
  level: fatal
input:
  generate:
    mapping: root = {}
    count: 1
pipeline:
  processors:
    - branch:
        processors:
          - http:
              url: https://www.google.com/does-not-exist
          - catch: []
        result_map: meta http_status_code = @http_status_code
    - mapping: root.http_status_code = @http_status_code
output:
  stdout:
    codec: lines
```

```sh
$ benthos -c pipeline.yaml
{"http_status_code":null}
```

Am I holding the tool wrong, or is this a bug?
