### ISSUE TITLE
mongodb processor does not throw duplicate key errors

### ISSUE THREAD

**Issue by zzl221000** [benthosdev/benthos#2298]
## Description
We have multiple data sources and use mongodb's _id field to filter for duplicates and then make the data available for downstream consumption. Here mongodb also acts as our data log.
However, now that we're using mongodb processor insert-one to insert the same _id, it doesn't fail. mongodb's insert failures are ignored, and we can't use error handling to resolve them.

```yaml
input:
  http_server:
    address: "0.0.0.0:8889"

pipeline:
  processors:
    - mutation: |
        root._id = "1"
        root.source = "test"
    - mongodb:
        url: mongodb://root:root@localhost:3717/admin
        database: test
        collection: "test_log"
        operation: insert-one
        document_map: root = this
        upsert: false
    - mapping: root = if errored() { deleted() }
output:
  stdout:
    codec: lines
```

## Version
```
Platform: Windows 11 amd64
Version: 4.24.0
Date: 2023-11-24T10:00:58Z
```
