### ISSUE TITLE
usecase where a batching-policy "all" would make sense

### ISSUE THREAD

**Issue by Someone894** [benthosdev/benthos#2301]
Hi,

currently I am writing a Benthos `config.yaml` which is supposed to read data from a database and store it as 1 parquet file a day in the azure blob storage. During this I realized that Benthos is missing a feature:

There is no batching-policy "all" within the [input borker](https://www.benthos.dev/docs/components/inputs/broker#batching-1). I want to `SQL SELECT` __all__ data between the given dates and then split it into days via the [`group_by_value`](https://www.benthos.dev/docs/components/processors/group_by_value) processor.  The `group_by_value` processor only works with allready batched data so I need a way to "pre-batch" __all__ of the data I got from the database and as far as I know this is currently not possible.

Below is a MWE I got from [here](https://stackoverflow.com/q/71084761). With a "all" policy this MWE would be way nicer since now we need to know the exact number of messages per batch (40 in this example) which is rather hindering to my case since I want all avalibale data from the database and dont know how may entries this might be for a given time period.

```yaml
input:
  broker:
    inputs:
      - generate:
          interval: ""
          count: 40
          mapping: |
            root = count("test")
    batching: 
      count: 40
      byte_size: 0
      period: 10s
      check: ""
     #all

pipeline:
  processors:
    - group_by_value:
        value: ${! (this % 2 == 0) }
    - log:    
        level: INFO
        message: 'Test! ${! (this) } ${! (this % 2 == 0) } ${! batch_size() }'
    - bloblang: |
        meta name = (this) % 2 == 0
    - archive:
        format: tar
        path: ${! (this) }

output:
  file:
    path: test/${! (meta("name")) }.tar
    codec: all-bytes
```
