### ISSUE TITLE
SFTP connection is being dropped before benthos is being able to delete the file

### ISSUE THREAD

**Issue by Nymrinae** [benthosdev/benthos#2302]
Hi,
I have the current configuration which consumes csv files from a SFTP server parsing the data (only input displayed here for the sake of simplicity) and adding the content to my postgresql database.

```
input:
  sftp:
    address:  
    credentials:
      username:  
      password: 
    paths: ["NIR/*.csv"]
    codec: lines
    delete_on_finish: true
output:
  sql_insert:
    driver: postgres
    dsn:
    table: record_data
    columns:
      - value
      - criteria
      - is_active
      - context
      - measured_at
      - client_id
      - site_id
      - created_at
    args_mapping: >-
      root = [ this.value, this.criteria, this.is_active, this.context,
      this.measured_at, this.client_id, this.site_id, this.created_at ]
```

However, the last file is consumed properly (which means data is effectively added on my database) but the file isn't deleted because the SFTP connection drops before benthos is able to delete the file, which leads to potential duplicates if i'm doing the same operation minutes later

![image](https://github.com/benthosdev/benthos/assets/52325682/e4536a84-677e-4f59-b0a0-94fb46091e08)

I tried using sql_raw instead of sql_insert on the output with conflict handling to avoid duplicates

```
output:
  sql_raw:
    driver: postgres
    dsn: 
    query: >- 
      INSERT INTO record_data (value, criteria, is_active, context, measured_at, client_id, site_id, created_at)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
      ON CONFLICT (client_id, site_id, criteria, value, measured_at)
      DO NOTHING
    args_mapping: >-
      root = [ this.value, this.criteria, this.is_active, this.context,
      this.measured_at, this.client_id, this.site_id, this.created_at ]
```
and it probably leads to the same issue?

![image](https://github.com/benthosdev/benthos/assets/52325682/a78aa503-8f80-47b5-9be6-75f4bf6e1a42)
