### ISSUE TITLE
checkpoint_limit behavior for kafka vs kafka_franz inputs

### ISSUE THREAD

**Issue by joshgarrett-hellofresh** [benthosdev/benthos#2319]
I am looking to migrate an input from kafka to kafka_franz and noticed a difference in behavior of the `checkpoint_limit`.
Given the following demo stream yamls:
kafka.yaml:
```yaml
input:
  kafka:
    addresses:
      - ${KAFKA_DSN}
    tls:
      enabled: ${TLS_ENABLED:true}
      root_cas_file: ${KAFKA_CA_CERT_FILE}
    sasl:
      mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
      user: ${KAFKA_USERNAME}
      password: ${KAFKA_PASSWORD}
    target_version: 3.4.1
    topics:
      - test.topic.kafka
    consumer_group: test-group-kafka
    start_from_oldest: false
    max_processing_period: 10m
    checkpoint_limit: 1

pipeline:
  processors:
    - log:
        level: DEBUG
        message: 'kafka: before sleep'
        fields_mapping: |-
          root.partition = meta("kafka_partition")
          root.offset = meta("kafka_offset")
    - sleep:
        duration: 5s
    - log:
        level: DEBUG
        message: 'kafka: after sleep'
        fields_mapping: |-
          root.partition = meta("kafka_partition")
          root.offset = meta("kafka_offset")

output:
  stdout: {}
```
kafka_franz.yaml:
```yaml
input:
  kafka_franz:
    seed_brokers:
      - ${KAFKA_DSN}
    tls:
      enabled: ${TLS_ENABLED:true}
      root_cas_file: ${KAFKA_CA_CERT_FILE}
    sasl:
      - mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
        username: ${KAFKA_USERNAME}
        password: ${KAFKA_PASSWORD}
    topics:
      - test.topic.kafka.franz
    consumer_group: test-group-kafka-franz
    start_from_oldest: false
    checkpoint_limit: 1

pipeline:
  processors:
    - log:
        level: DEBUG
        message: 'kafka franz: before sleep'
        fields_mapping: |-
          root.partition = meta("kafka_partition")
          root.offset = meta("kafka_offset")
    - sleep:
        duration: 5s
    - log:
        level: DEBUG
        message: 'kafka franz: after sleep'
        fields_mapping: |-
          root.partition = meta("kafka_partition")
          root.offset = meta("kafka_offset")

output:
  stdout: {}
```
and a producer, produce_test.go:
```golang
package producertest

import (
	"context"
	"testing"
	"github.com/stretchr/testify/require"
	"github.com/twmb/franz-go/pkg/kgo"
	"github.com/twmb/franz-go/pkg/kversion"
)

func TestProduce(t *testing.T) {
	t.Parallel()

	client, err := kgo.NewClient(kgo.MaxVersions(kversion.V2_4_0()), )
	require.NoError(t, err)

	ctx := context.Background()

	for i := 0; i < 10; i++ {
		err = client.ProduceSync(ctx, &kgo.Record{
			Topic: "test.topic.kafka",
			Value: []byte(`{"uuid":"00000000-0000-0000-0000-000000000001"}`),
			Key:   []byte("kafka key"),
		}).FirstErr()
		require.NoError(t, err)

		err = client.ProduceSync(ctx, &kgo.Record{
			Topic: "test.topic.kafka.franz",
			Value: []byte(`{"uuid":"00000000-0000-0000-0000-000000000002"}`),
			Key:   []byte("kafka franz key"),
		}).FirstErr()
		require.NoError(t, err)
	}
}
```

For the kafka input, I see a `before sleep` log, then an `after sleep` log 5s later, repeated 10 times, as expected.  [kafka_logs.txt](https://github.com/benthosdev/benthos/files/13835450/kafka_logs.txt)

However, for the kafka_franz input, I see a `before sleep` log, then an `after sleep` log 5s later, then 8 (running on an 8-core CPU Apple M1 Pro) `before sleep` logs at the same time.  [kafka_franz_logs.txt](https://github.com/benthosdev/benthos/files/13835449/kafka_franz_logs.txt)

Is this behavior expected, or perhaps I am missing something in my kafka_franz configuration?  Is checkpoint_limit  intended to do something different on franz_kafka than on kafka?
