### ISSUE TITLE
Issue in benthos plugin

### ISSUE THREAD

**Issue by mittal-jatin** [benthosdev/benthos#2338]
I'm referring https://www.benthos.dev/blog/2019/08/20/write-a-benthos-plugin/ to create a custom processor and run locally. 

```
pipeline:
  processors:
    - json:
        operator: copy
        path: x
        value: y
    - process_field:
        path: y
        result_type: int
        processors:
          - type: fnv_hash
    - bloblang: |
        root = this
        root.x = this.x.trim()
        root.y = "task" + ((this.y % 64) % 3).string()
    - log:
        level: INFO
        message: 'test'
```

When I'm just having above part, its running fine and giving results as expected but when I'm adding input as 
```
input:
  label: "bq_input_benthos"
  gcp_bigquery_select:
    project: test-project
    table: test-dataset.test-table
    columns:
      - col1
      - col2
      - col3
    where: time BETWEEN DATETIME("2024-01-15") AND DATETIME("2024-01-25")

```
I'm getting below error - 
`line 5: unable to infer input type, candidates were: [gcp_bigquery_select]`
