### ISSUE TITLE
The behavior of error with the generate input. 

### ISSUE THREAD

**Issue by pigri** [benthosdev/benthos#2348]
Error:
It is always wrong with a one sec.

Expectations:
The counter always ends at the same time.

Reproduce:
```
input:
  label: interval
  generate:
    interval: "@every 1s"
    mapping: |
      root.current_time = timestamp_unix()

output:
  stdout: {}
```

My test config:  https://gist.github.com/pigri/17cb1ed7b09890495bb54f4b66ca2756
Results: https://docs.google.com/spreadsheets/d/1aR6ecZH6Gi4P-V_oStkszQShCt_TJ4rT57aUNYTC9ms/edit#gid=0

Discoussion on discord: https://discord.com/channels/746368194196799589/754099840354615296/1200820770734080041
