### ISSUE TITLE
Metric mapping not working in main branch

### ISSUE THREAD

**Issue by ZachTB123** [benthosdev/benthos#2373]
I have a config like:

```yaml
input:
  http_server: {}

output:
  stdout: {}

metrics:
  prometheus: {}
  mapping: |
    meta foo = "bar"
```

which I am using in v4.24.0.

This results in metrics like:

<img width="683" alt="Screenshot 2024-02-09 at 5 17 01 PM" src="https://github.com/benthosdev/benthos/assets/17228033/9729aff6-18b1-4a1a-8792-548abbd0b1fd">

The `foo` label is added to all metrics.

I'm trying out changes in the main branch (which is https://github.com/benthosdev/benthos/commit/8a488565ca56ee45a7f4d4e28216052819367228) as of writing this, but that same functionality no longer seems to work:

<img width="564" alt="Screenshot 2024-02-09 at 5 14 58 PM" src="https://github.com/benthosdev/benthos/assets/17228033/ff48ed81-244a-4421-9683-da4954225767">

Based on the docs in main, this should still work?
