### ISSUE TITLE
Increase tracing coverage throughout our components

### ISSUE THREAD

**Issue by lucasoares** [benthosdev/benthos#2387]
Currently, all the tracing data are generated by our manual instrumentation.

We should add instrumentation for modules that provide opentelemetry's middlewares for instrumentation, adding more value to the tracing data we provide.

For example, with the following simple config file:
```
# Common config fields, showing default values
input:
  label: "my_test"
  http_server:
    path: /post/{test}

# Config fields, showing default values
output:
  stdout:
    codec: lines

tracer:
  open_telemetry_collector:
    tags: { "service.name": "my_test" }
    grpc: 
      - url: localhost:4317
```

The following trace data is currently generated:

![image](https://github.com/benthosdev/benthos/assets/10624972/65c9ed42-50d0-4afa-bf89-baee5f3de960)

But when we added the [gorilla otelmux](https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux) instrumentation, we started to notice a bigger time that benthos took to process the request:

![image](https://github.com/benthosdev/benthos/assets/10624972/4cde447f-fa6a-4346-8f2f-13bdeecb6640)

It will also bring useful information about the request itself (currently all of our spans don't have any tag):

![image](https://github.com/benthosdev/benthos/assets/10624972/fa8bd279-a7ba-454e-9813-4deac1a28702)

Usually, this is the default approach when adding tracing to the applications, and additional data should be handled by the users, either sampling or dropping spans in the open telemetry collector itself.

The instrumentation by itself will not add any overhead when users don't have trace enabled since most of them use the noop trace provider when the tracer is not configured.
