### ISSUE TITLE
Memory leak issue with Benthos memory cache

### ISSUE THREAD

**Issue by youngjosh** [benthosdev/benthos#2404]
Benthos Version: 4.24.0 (As pulled from the jeffail/benthos docker repo)

We have had an issue recently where our high volume Benthos dedupe pods (in the realm of ~2-3k messages per second) will slowly use more and more memory until eventually crashing. This does escalate slowly, for example below is this graph of memory usage over a 12 hour period for a pair of pods that dedupe ~1.5-2k messages per second, and as such are making 1.5k-2k dedupe checks against the cache each.
![Screenshot 2024-02-29 at 08 16 01](https://github.com/benthosdev/benthos/assets/43736836/fb7ac4f2-47ca-415c-9b63-4833c9e8d0fe)

These pods have very little running on them beside a dedupe against the kafka key, I have given an example of our benthos configs below, removing specifics about our input/output and two (simple) bloblang processors. We have several very similar pipelines with slightly different bloblang processors, but all use this style of cache and all suffer the slow growth of memory usage until an OOM occurs.

```
cache_resources:
  - label: dedupe
    memory:
      default_ttl: 800s

input:
  kafka:
    # A standard kafka input is used

pipeline:
  threads: ${THREADS:8}
  processors:
    - for_each:
        - dedupe:
            cache: dedupe
            drop_on_err: false
            key: ${!meta("kafka_key")}
        - switch:
            # Two simple bloblang processors just for adjusting simple fields are contained here

output:
  kafka:
    # A standard kafka output is used

```

In trying to diagnose why this was happening we spun the pods up in debug mode and ran pprof against the debug endpoints to track memory usage over time. The culprit was the memory cache, as I've shown below. It sits at 147.75MB in this screenshot but on leaving overnight went up by well over a hundred megabytes in this scenario despite the TTL on the cache being ~15 minutes (unfortunately I did not screenshot the later high memory usage. I can spin the pods back up in debug if this would help)
<img width="857" alt="Screenshot 2024-02-29 at 08 29 41" src="https://github.com/benthosdev/benthos/assets/43736836/ff5989a6-4a2d-40dd-ab48-5a729334d4db">

We tried messing with the memory cache resources (i.e. explicitly setting a compaction interval) but we did not see any change in the growth of the cache size. I also looked at one of our other benthos pods which performs a much larger set of operations and used a small memory cache (at around 40/s message throughput) and after tracking for a day, noticed that it grew too - although at a much, much slower rate. 

In this way, I believe (unless I've missed something stupid, please correct me if so) that there is some form of memory leak in the [Benthos memory cache](https://www.benthos.dev/docs/components/caches/memory/) which is directly proportional to the throughput utilising the cache.
