### ISSUE TITLE
Cannot decompress HTTP POST gzipped JSON

### ISSUE THREAD

**Issue by webfrank** [benthosdev/benthos#2427]
Hi,
  I was trying to send a gzipped JSON to an HTTP server endpoint.

```
input:
  http_server: 
    path: /{tenant}
    timeout: 30s
    sync_response:
      status: "200"

pipeline:
  processors:
  - switch:
    - check: meta("Content-Encoding") == "gzip"
      processors:
      - decompress:
          algorithm: gzip
```

Sending a simple JSON file gzipped with: `gzip sample.json`

I've tried all other algorithms with no success, this is the error:

`ERRO Failed to decompress message part: unexpected EOF  @service=benthos label="" path=root.pipeline.processors.0.switch.0.processors.0`

POST is done from within VSCode REST plugin:

```
POST http://localhost:4195/demo
Content-Type: application/json
Content-Encoding: gzip

< ./sample.json.gz
```
