### ISSUE TITLE
Bloblang interpolation with custom binary plugin

### ISSUE THREAD

**Issue by Arenash13** [benthosdev/benthos#2440]
Hello,

I have a case where I need to assign messages to a specific Kafka topic in the same style as https://www.benthos.dev/docs/configuration/interpolation#bloblang-queries

```
output:
  kafka:
    addresses: [ "TODO:6379" ]
    topic: 'dope-${! json("topic") }'
```

The only difference is that these are binary payloads where I search for specific bytes to determine the route. 
I started to write a bloblang plugin but I'm not sure if it works out of the box and if I have to do anything to keep the original payload "untouched".

Is there a specific example I can rely on with similar constraints ?

Thanks in advance
