### ISSUE TITLE
GCP cloud storage output error with Failed to delete temporary file used for merging: context canceled

### ISSUE THREAD

**Issue by anthonycorbacho** [benthosdev/benthos#2522]
## Context

I am reading bunch of event coming from a MQTT broker 

```yaml
input:
  label: "benthos_mqtt_test"
  mqtt:
    urls:
      - localhost:1883
    client_id: benthos-reader
    connect_timeout: 30s
    topics:
      - $share/benthos/XXXX/#
```

and I am trying to process and save the output into  blobstorage (GCP cloud storage).
The processing is relatively simple, I am taking an mqtt message (slice of events) and outputting to a CSV like format
```yaml
buffer:
  none: {}
pipeline:
  threads: -1
  processors: 
    - unarchive:
        format: "json_map"
    - bloblang: |
        let csv = match {
             this.value.type() == "bool" => ",,"+this.value.string()
             this.value.type() == "number" => this.value.string()+",,"
             _ =>  ","+this.value.string()+","
        }
        root = this.ts.ts_strftime("%Y-%m-%dT%H:%M:%S%z").string() + "," + meta("archive_key") + "," + $csv +"\n"
        meta dt = this.ts.ts_strftime("%Y-%m-%d", "UTC")
        meta id = meta("archive_key").escape_url_query()
```
the output logic is to create folder partition by date (`dt=YYYY/MM/DD`) and id (`id=ID`)
```yaml
output:
  label: "blobstorage"
  #stdout: {}
  gcp_cloud_storage:
    bucket: "abucket" 
    path: benthos/dt=${!@dt}/id=${!@id}/file.csv
    collision_mode: append
    timeout: 60s
    max_in_flight: 64
```

when running Benthos with the config, I am seeing quite often this error
```
ERRO Failed to delete temporary file used for merging: context canceled  @service=benthos label=blobstorage path=root.output
```

I am not 100% sure if this is false positive since I have quite a lot of event comming per sec (~1000 events) and the error doesn't tell me much about the path timing out so I cannot really check if the temp file has been merged or not.
i tried to change timeout 20s, 30s 60s but seems to always error.

**Comment by mihaitodor** [comment]
Hey @anthonycorbacho, thank you for raising this issue! While I think setting `timeout: 60s` should be more than enough time for the Google APIs to delete a file, what might be happening is either that the write fails and [we try to remove the file](https://github.com/benthosdev/benthos/blob/d60c647c7ebfcfad9df722eee1c184aa79978778/internal/impl/gcp/output_cloud_storage.go#L310) anyway or that [writes](https://github.com/benthosdev/benthos/blob/d60c647c7ebfcfad9df722eee1c184aa79978778/internal/impl/gcp/output_cloud_storage.go#L301) take too long and they don't leave enough time in the same context to also do the deletion part (but I think the latter is unlikely).

Not sure what's the best way to address this, but I'd consider skipping the deletion if the write fails. Also, it might be worth either reducing the level of that "Failed to delete temporary file used for merging" log or introducing a flag which users can enable to silence this error.

Additionally, I think there's some opportunity for performance gains by passing more than one object in the `ComposerFrom()` call. The docs [say](https://cloud.google.com/storage/docs/composing-objects) that up to 32 are supported, so that could be a good future enhancement.

**Comment by anthonycorbacho** [comment]
Hi @mihaitodor thank you for the answer.

I tested different settings and am still having issues. I cloned the repo and added more debug to see the folder where the merge failed. The funny thing is that the file that was supposed to have a bunch of entries inside one has 1.

I tried with batch and having multiple file instead and same issue happen
```yaml
  gcp_cloud_storage:
     bucket: "abucket"
     path: benthos/dt=${!@dt}/id=${!@id}/file-${!timestamp_unix_nano()}.csv
     content_type: binary/octet-stream
     collision_mode: append
     timeout: 60s
     max_in_flight: 64
     batching:
       count: 100
```

Maybe my pipeline is causing the issue because each event I get generally has a bunch of IDs in the message.
e.g
```
{
  "ID1": {ts: xxx, value: xxx},
  "ID2": {ts: xxx, value: xxx},
  "ID3": {ts: xxx, value: xxx},
  "ID4": {ts: xxx, value: xxx},
}
```
and I am trying to 
 - explode the message as single line via `unarchive: format: json_map` so that I can work with individual message and then output them to the gcp cloud storage.


I tired to put every messages into a single file but I get a rate limit error.

**Comment by mihaitodor** [comment]
I'm not sure what's going on there, but if you do `path: benthos/dt=${!@dt}/id=${!@id}/file-${!timestamp_unix_nano()}.csv`, then that forces the output to create a new file for every write, ignoring the batching, because `${!timestamp_unix_nano()}` will resolve to a unique path for each message. One way around it is to add an `archive` processor in the batching section with `format: lines` and then you'll get a unique file per batch if the generated path is always different. If not, `collision_mode: append` should result in an append.

PS: When configuring `batching` with a `count` you likely also want to add a `period`, since your input will not always fill the last batch and then Benthos will keep waiting and waiting for the batch to fill up before emitting it.

**Comment by anthonycorbacho** [comment]
@mihaitodor i followed your recommendation with the batching and the good new is that I don't get the error anymore, so I think this help.

But this bring a new issue, now with the following gcp output setting
```yaml
batching:
       period: 1s
       processors:
        - archive:
            format: lines
```

each folder (dt=YYYY/MM/DD/id=XXXX) contain a mix of ids not the one I am targeting with the path.

so if the id in the path is `id=ID1` I am expecting to have only id1 in the file but its a mix of all the ids (id1, id2, etc)

**Comment by mihaitodor** [comment]
@anthonycorbacho That's great to hear! Regarding the path, it sounds like you don't want to mix IDs across multiple files, so just have a file for each ID value if I'm understanding you correctly. If that's what you need, then you can break up the batch into smaller batches by using the `group_by_value` processor before the `archive` one to create batches for each individual ID. However, if the IDs are unique / message, then that will result in batches of size one, which is probably not what you want.

**Comment by anthonycorbacho** [comment]
@mihaitodor I tried with your last recommended way
and still getting the context error, and now it looks like I am loosing data
```yaml
  gcp_cloud_storage:
    bucket: "abucket"
     path: benthos/dt=${!@dt}/file-${!@id}.csv
     content_type: application/octet-stream
     collision_mode: append
     timeout: 60s
     max_in_flight: 64
     batching:
       period: 10s
       processors:
        - group_by_value:
            value: ${! meta("id") }
        - archive:
            format: lines
```

I have a mix of
```
Failed to delete temporary file used for merging: context deadline exceeded
```

and 
```
Failed to delete temporary file used for merging: context canceled
```
