### ISSUE TITLE
`http` processors send body on `GET`

### ISSUE THREAD

**Issue by mskarbek** [benthosdev/benthos#2527]
For:
```
pipeline:
  threads: -1
  processors:
    - branch:
        processors:
          - http:
              url: "https://REDACTED/service/rest/v1/components?repository=${! this.repo}"
              verb: GET
              headers:
                Accept: "application/json"
        result_map: "root.response = this"
```
I received 415 error from Sonatype Nexus server. Adding `TRACE` level of logging revealed that Benthos adds body to the request even if it is a `GET` which in turn upsets Nexus.
Request body should be added only to the `POST` requests.

**Comment by packman80** [comment]
From documentation:

> A [Bloblang mapping](https://www.benthos.dev/docs/guides/bloblang/about) that describes how to create a request payload suitable for the child processors of this branch. If left empty then the branch will begin with an exact copy of the origin message (including metadata).

You need to get empty body (in this case you avoid of sending body in get request). Use it:

```
pipeline:
  threads: -1
  processors:
    - branch:
        request_map: root = "" 
        processors:
          - http:
              url: "https://REDACTED/service/rest/v1/components?repository=${! this.repo}"
              verb: GET
              headers:
                Accept: "application/json"
        result_map: "root.response = this"
```
