### ISSUE TITLE
schema_registry_encode double encodes path params

### ISSUE THREAD

**Issue by paulius-asvydis** [benthosdev/benthos#2584]
When using `schema_registry_encode` processor with subject like:

```yaml
          - schema_registry_encode:
              url: http://my-url
              subject: "main.common"
              refresh_period: 10m
``` 

The offending code seems to be:

```golang
// internal/impl/confluent/client.go

func (c *schemaRegistryClient) doRequest(ctx context.Context, verb, reqPath string) (resCode int, resBody []byte, err error) {
	reqURL := *c.schemaRegistryBaseURL
	if reqURL.Path, err = url.JoinPath(reqURL.Path, reqPath); err != nil {
		return
	}

       var req *http.Request
       // LOG ADDED FOR DEBUGGING
        fmt.Printf("reqURL: %v\n", reqURL.String())
	if req, err = http.NewRequestWithContext(ctx, verb, reqURL.String(), http.NoBody); err != nil {
		return
	}

// reqURL: http://my-url/subjects/main%252Fcommon/versions/latest
```

## Expected Parsed URL:
http://my-url/subjects/main%2Fcommon/versions/latest
## Actual Parse URL:
http://my-url/subjects/main%252Fcommon/versions/latest

Clearly the '/' character is double encoded.
