### ISSUE TITLE
output component fallback not work

### ISSUE THREAD

**Issue by huangpeizhi2018** [benthosdev/benthos#2610]
- The configuration file is as follows:
```
input:
  generate:
    count: 0
    interval: "1s"
    mapping: |
      let seq_no = counter(min:1)
      root = if $seq_no%2 == 0 {
                {"type": "even", "seq": $seq_no }
             } else {
                {"type": "odd", "seq": $seq_no }
             }

pipeline:
  processors:
    - log:
        level: INFO
        message: "pipeline.log ${! content()}"
    - mapping: |
        root = this

output:
  fallback:
    - redis_list:
        url: redis://127.0.0.1:6379
        key: queue.output_retry_01
    - file:
        path: failure.json
```
- When I stopped the Redis service, I didn't find any generated files(failure.json).

- I used fallback to record unsuccessful data insertion when the input was kafka and the output was database, which was feasible. Why is REDIS not working
