### ISSUE TITLE
Don't acknowledge messages when processor fails

### ISSUE THREAD

**Issue by patrobinson** [benthosdev/benthos#635]
I'm trying to configure a pipeline using S3 and SQS. In order to debug failures I'm relying on SQSs inbuilt Dead Letter Queue functionality.
How this works is for any message that's received a certain number of times but doesn't get deleted, it's automatically routed to a secondary SQS queue.
Therefore we need the pipeline to not acknowledge those messages

Our pipeline looks something like this:

```yaml
s3:
  bucket: bucket
  sqs_url: "${SNITCH_INGEST_SQS_URL}"
  sqs_body_path: Records.*.s3.object.key
  sqs_bucket_path: bucket
  region: "${AWS_REGION}"
  download_manager:
    enabled: false
pipeline:
  threads: 1
  processors:
  - switch:
    - condition:
        bloblang: this.exists("digestS3Object")
      processors:
      - filter:
          any: {}
    - condition:
        bloblang: this.exists("Records")
      processors:
      - bloblang: root = this.Records
      - unarchive:
          format: json_array
      - try:
        <some processors>
```

The input is a JSON file with an array, each of which we process separately. Therefore we will have to reject the entire contents even if just one message fails. This is fine, even if some have processed already.

But this is not behaving as expected. In this scenario [the documentation states](https://www.benthos.dev/docs/configuration/error_handling) the message is "abandon". But does that mean the message is acknowledged or not? It seems like it still is.
Is there a way to not acknowledge the entire batch of message even if one fails?
