### ISSUE TITLE
Input: Kafka Output: SQL with retry. Messages being dropped

### ISSUE THREAD

**Issue by mangatmodi** [benthosdev/benthos#673]
We have kafka input with batching
```yaml
resources:
  inputs:
    topic:
      kafka:
        addresses:
          - ${KAFKA_BOOTSTRAP_SERVERS}
        topics: [ topic ]
        consumer_group: ${APP_NAME}
        client_id: ${APP_NAME}
        target_version: 2.5.0
        start_from_oldest: true
        checkpoint_limit: 1
        batching:
          count: 50
          period: 100ms

```

A processor which simply maps

```yaml
pipeline:
  processors:
    - bloblang: |
        root.doc = this.catch([])
        root.key = meta("kafka_key").parse_json()
        root.topic = meta("kafka_topic")
        root = if content().length() == 0 {
          deleted()
        }
    - catch:
        - log:
            message: "Error while processing a message"
            level: ERROR
            fields:
              payload: ${! json() }
              from_topic: ${! meta("kafka_topic")}
              error: ${! error() }
        - bloblang: 'root = deleted()'

```

And output is SQL with retry

```yaml
  outputs:
    expected-inbound-topic:
      retry:
        max_retries: 2
        backoff:
          initial_interval: 500ms
          max_interval: 3s
        output:
          sql:
            max_in_flight: 6
            driver: postgres
            data_source_name: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_SCHEMA}?sslmode=disable
            query: >-
              INSERT QUERY....
            args:
              - ${! json("key.xyz") }

```

However for every run, I see that some of the rows are missing which is present in the input topic. 

Is there a posibility in the above configuration where we can silently swallow a message? I checked that there is no log in the Benthos app. The data also seems ok to me. What happens when we fail to insert after retry? In my understanding we shall send failure back to input, which will then block the kafka consumer from committing the message, and the whole setup should get stuck there.
