### ISSUE TITLE
Support tags in `path_mapping` for statsd

### ISSUE THREAD

**Issue by luck02** [benthosdev/benthos#677]
We generally want all of our metrics to include a standard set of tags, ie `pod_name` and `container_name` etc.

I don't see anything in the statsd section about specifying generic tags (which we'd fill with environment variables in this case).

Is there something not in the docs or that I missed?

Thanks a bunch!

**Comment by Jeffail** [comment]
Hey @luck02, it's not currently possible to add static tags to the `statsd` metrics exporter.

However, there's experimental support for this in the `prometheus` exporter with the field `path_mapping`: https://www.benthos.dev/docs/components/metrics/prometheus/#path_mapping. We could quite easily update `statsd` to work the same way, which would allow you to do stuff like this:

```yaml
metrics:
  statsd:
    address: localhost:4040
    path_mapping: |
      meta pod_name = "foo"
      meta container_name = env("CONTAINER_NAME")
    flush_period: 100ms
    tag_format: datadog
```
