### ISSUE TITLE
Batch loading

### ISSUE THREAD

**Issue by tomsej** [benthosdev/benthos#714]
Hi, I am curious if it is possible to use benthos also for batch loading. E.g. I have table in Postgres and I want to dump it to S3. After the whole table is loaded, benthos gracefully ends with 0 exit code, so I am able to e.g. run it with Airflow. I was not able to find any way. Thanks a lot for this great project.

**Comment by Jeffail** [comment]
Hey @tomsej, you can potentially combine a few components to make this work, this first is to use a `generate` input with an `sql` processor in order to trigger a select for each row of a table. This should be quite easy if you have a sequence of IDs without any breaks, as you can do something like this:

```yaml
input:
  generate:
    interval: ""
    mapping: 'root.id = count("rows")'
  processors:
    - sql:
        driver: postgresql
        result_codec: json_array
        data_source_name: postgres://foouser:foopass@localhost:5432/testdb?sslmode=disable
        query: "SELECT * FROM footable WHERE id = $1;"
        args:
          - ${! json("id") }
```

However, this would continue to run even when you've reached the end of the table, so the next component to introduce is the `read_until` input: https://www.benthos.dev/docs/components/inputs/read_until, which consumes a wrapped input until a given bloblang mapping resolves to `true`.

```yaml
input:
  read_until:
    input:
      generate:
        interval: ""
        mapping: 'root.id = count("rows")'
      processors:
        - sql:
            driver: postgres
            result_codec: json_array
            data_source_name: postgres://testuser:testpass@localhost:5432/testdb?sslmode=disable
            query: "SELECT * FROM foo WHERE id = $1;"
            args:
              - ${! json("id") }
    check: 'this.length() == 0'
    restart_input: false
  processors:
    - bloblang: 'if this.length() == 0 { deleted() }'
```

That's a real basic example that would just end the stream and exit as soon as a message comes through that returns zero rows, where we assume that means we reached the end of the table.
