### ISSUE TITLE
AMQP allow disabling requeue on certain error types

### ISSUE THREAD

**Issue by Jeffail** [benthosdev/benthos#846]
It'd be useful to conditionally disable requeuing certain messages when an `amqp_0_9` input receives a nack of a certain pattern. We could enable this by adding a configuration field containing patterns, where if a pattern matches the nack error then the message is rejected rather than requeued. It would look something like this:

```yaml
input:
  amqp_0_9:
    url: amqp://guest:guest@localhost:5672/
    queue: benthos-queue
    consumer_tag: benthos-consumer
    nack_reject_patterns:
      - "^reject me please:.+$"
```
