### ISSUE TITLE
tls client_certs key_file requires a password to use in http cert based auth

### ISSUE THREAD

**Issue by johnwaldron** [benthosdev/benthos#871]
In an http processor, the server requires cert-based authentication.  The client needs to present a valid public and private key, along with a username and password to successfully call the API.  The username/password is provided in "basic_auth" settings with no issues.   The problem is with the private cert.  It is password protected and there is no where in the "tls" configuration to specify a password.
 
```
    - http:
        url: https://cust0120-test-api.myco.com:443/link-ws/svc/nativeIdQuery
        verb: POST
        basic_auth:
          enabled: true
          username: "myusernam.cust0120-test.2020.11"
          password: "xxxxxkHqLxx6"
        tls:
          enabled: true
          skip_cert_verify: false
          client_certs:
            - cert_file: "/tmp/myco.120.cer"
              key_file: "/tmp/myco.120.pem" 
```

For reference, compare to other clients...Postman and Intersystems Iris... both provide support for password protected private key.

In POSTMAN, I can issue the request successfully with the following Certificates setup (note here we use the "p12" file for the private key):
```
Host:  cust0120-test-api.myco.com
CRT file:
  /home/me/misc/certs/myco.120.cer
PFX file
  /home/me/misc/certs/myco.120.p12
Passphrase: xxxxxkHqLxx6
```

In another client, that has an "SSL/TLS Config", I can use the following (note here we use a "pem" file for the private key...and it requires a password):
```
File containing this client's certificate: /home/me/misc/certs/myco.120.cer
File containing associated private key:  /home/me/misc/certs/myco.120.pem
Private key type:  RSA
Password:  xxxxxkHqLxx6
```

To work-around, I will try to remove the password from the ".pem" private key file using:
```
openssl rsa -in verato.120.pem -out myco.120.nopass.pem
```
