### ISSUE TITLE
Prometheus metrics calculated by a pipeline?

### ISSUE THREAD

**Issue by bittrance** [benthosdev/benthos#894]
We have a use case where we would like to use Benthos for observability. Benthos would listen to an MQTT topic, aggregate what it finds and present an HTTP endpoint for Prometheus to scrape. Broken down, it would look something like this:

 1. receive messages from mqtt topics
 1. aggregate metrics over time with a cache so that we can count occurrences, emitting aggregated messages (possibly also needs a `generate` "strobe" to ensure updates are sent out even if there are no new mqtt messages)
 1. buffer to forward only latest message
 1. serve with http_server

It is my understanding that Benthos cannot solve this issue today because there is no way to ensure that Prometheus will always get the most recent message. That is, even if we managed to achieve an aggregation into a Prometheus payload and manage to drop messages so we only have a single in-flight message, there is no way to update/replace the message that http_server will serve next? A component cannot "cancel" a forwarded message.

Put differently, the http_server output cannot be used to provide a "status" endpoint. The http_server output has the unique (within Benthos) ability that it supports polling, which could allow for scenarios where you want to present a snapshot, rather than individual messages.

This option would expand the http_server with a `mode` parameter which would default to `fan-out` but which could be set to `snapshot` or perhaps `retain-latest`.

- Upside: Generic, potentially widely applicable
- Downside: somewhat obscure; even with e.g. its own cookbook entry, people may not find it.

Alternatively, because our use case is observability, we could also add a `metrics` output, which would name a Benthos metrics resource and add custom netrics to that resource based on a known payload format. This would be presented as a method to create custom metrics from within a pipeline (any pipeline could use `for_each` to produce some metrics as messages flows by.

You would have to emit metrics by transforming messages into a known formatE.g.
```
output:
  metrics:
    destination: prometheus
    extractions:
      - metric: frobs-seen
        type: increment
        extractor: # some bloblang expression resulting in a value to increment with
```
Analysis:

- Upside: Straight-forward, visible, in the spirit
- Doenside: only supports metrics

Have I understood Benthos current limitations correctly? If so, would you be open to a PR on either of those solutions, or is there some other method we have not considered?

**Comment by Jeffail** [comment]
Hey @bittrance, if I've understood your use case properly then I think you might actually be able to do this with the current feature set. You'd start by creating a standard pipeline consuming MQTT where the aggregated result is stored within a cache, then separately you could have a pipeline that creates an http_server input to read the aggregated result from the cache, form a prometheus valid body from it, then return it with the sync_response output.

The mqtt part would look something like this:

```yaml
input:
  mqtt: {}

pipeline:
  processors: [] # TODO: Your aggregation and stuff

output:
  cache:
      target: foocache
      key: myvalue
      value: ${! content() }

cache_resources:
  - label: foocache
    file: {} # TODO
```

The http_server part would look something like this:

```yaml
input:
  http_server: {}

pipeline:
  processors:
    - cache:
        operator: get
        resource: foocache
        key: myvalue

output:
  sync_response: {}

cache_resources:
  - label: foocache
    file: {} # TODO
```
