### ISSUE TITLE
 cannot unmarshal !!str `meta("k...` into processor.confAlias

### ISSUE THREAD

**Issue by brivadeneira** [benthosdev/benthos#995]
Trying to build a test from a `switch-case` structure which verifies a metadata key,
tests seem to having troubles parsing it

streams/check_key.yaml
```yaml
input:
  label: "check_key"
  http_server:
    address: ""
    path: /path
    allowed_verbs:
      - POST
    timeout: 20s

output:
  switch:
    retry_until_success: false
    strict_mode: true
    cases:
      - check: meta("key") == "a_key"
        output:
          type: stdout
          

      - output:
          reject: "Message failed due to: Wrong key"
          processors:
            - log:
                level: ERROR
                message: "Wrong key"
 ```

streams/check_key_benthos_test.yaml
```yaml
parallel: true
tests:
    - name: Wrong key
      environment: {}
      target_processors: check_key.yaml#/output/switch/cases/0/check
      target_mapping: ""
      mocks: {}
      input_batch:
        - content: Hello benthos
          metadata:
            example_key: a wrong key
      output_batches:
        - - content_equals: A SAMPLE DOCUMENT
            metadata_equals:
                example_key: some other value now
``` 

```bash
benthos test ./streams/check_key_benthos_test.yaml 
Failed to execute test target 'streams/check_key.yaml': failed to resolve case processors from 'streams/check_key.yaml': line 15: yaml: unmarshal errors:
  line 15: cannot unmarshal !!str `meta("k...` into processor.confAlias
```
